In [1]:
import os
import glob
import hashlib
from pathlib import Path
import pandas as pd
import numpy as np

# Set directories for Kaggle
DATA_DIR = Path("/kaggle/input/datasets/gopikrisha/custommade")
BASE_OUT = Path("/kaggle/working")

print(f"Reading inputs from: {DATA_DIR}")
print(f"Saving outputs to:   {BASE_OUT}")

# Match training files directly in dataset folder
files = glob.glob(os.path.join(str(DATA_DIR), "*_train*.csv"))

if not files:
    raise FileNotFoundError(f"No training CSV files matching '*_train*.csv' found in {DATA_DIR}")

# Remove byte-identical duplicate uploads
unique_files = {}
for path in files:
    with open(path, "rb") as f:
        file_hash = hashlib.sha256(f.read()).hexdigest()
    if file_hash not in unique_files:
        unique_files[file_hash] = path

files = list(unique_files.values())
print("Unique captures:", len(files))

# Inspect all captures
dataframes = []
capture_summary = []

for path in files:
    name = os.path.basename(path)
    df = pd.read_csv(path, on_bad_lines='skip', low_memory=False)

    lower = name.lower()
    if "benign" in lower:
        family = "Benign"
    elif "arp_spoofing" in lower:
        family = "ARP Spoofing"
    elif "mqtt" in lower:
        family = "MQTT"
    elif "recon" in lower:
        family = "Reconnaissance"
    elif "tcp_ip-dos" in lower:
        family = "TCP/IP DoS"
    elif "tcp_ip-ddos" in lower:
        family = "TCP/IP DDoS"
    else:
        family = "Unknown"

    df["label"] = 0 if family == "Benign" else 1
    df["attack_family"] = family
    df["source_file"] = name

    capture_summary.append({
        "file": name,
        "family": family,
        "rows": len(df),
        "columns": len(df.columns) - 3,
        "duplicates": int(df.duplicated(subset=df.columns[:45]).sum())
    })
    dataframes.append(df)

# Verify common feature schema
feature_columns = [
    c for c in dataframes[0].columns
    if c not in ["label", "attack_family", "source_file"]
]

for df in dataframes:
    assert feature_columns == [
        c for c in df.columns
        if c not in ["label", "attack_family", "source_file"]
    ], "Feature schema mismatch!"

inventory = pd.DataFrame(capture_summary)
print("\nCAPTURE INVENTORY")
display(inventory)

print("\nATTACK FAMILY SUMMARY")
display(
    inventory.groupby("family")
    .agg(
        captures=("file", "count"),
        records=("rows", "sum"),
        duplicates=("duplicates", "sum")
    )
    .reset_index()
)

# Save inventory to Kaggle working directory
inventory.to_csv(BASE_OUT / "ciciomt_capture_inventory.csv", index=False)
print("\nInventory saved successfully.")

Reading inputs from: /kaggle/input/datasets/gopikrisha/custommade
Saving outputs to:   /kaggle/working
Unique captures: 51

CAPTURE INVENTORY

,file,family,rows,columns,duplicates
0,TCP_IP-DoS-TCP4_train.pcap.csv,TCP/IP DoS,93488,45,0
1,TCP_IP-DoS-UDP1_train.pcap.csv,TCP/IP DoS,137011,45,0
2,Benign_train.pcap.csv,Benign,192732,45,0
3,TCP_IP-DDoS-ICMP3_train.pcap.csv,TCP/IP DDoS,189710,45,204
4,MQTT-DDoS-Publish_Flood_train.pcap.csv,MQTT,27623,45,0
5,Recon-Port_Scan_train.pcap.csv,Reconnaissance,83981,45,3734
6,TCP_IP-DDoS-TCP4_train.pcap.csv,TCP/IP DDoS,200998,45,0
7,TCP_IP-DDoS-ICMP1_train.pcap.csv,TCP/IP DDoS,194938,45,0
8,TCP_IP-DoS-SYN3_train.pcap.csv,TCP/IP DoS,108190,45,0
9,TCP_IP-DDoS-UDP2_train.pcap.csv,TCP/IP DDoS,207295,45,0
10,TCP_IP-DoS-TCP3_train.pcap.csv,TCP/IP DoS,95968,45,0
11,TCP_IP-DDoS-UDP1_train.pcap.csv,TCP/IP DDoS,206170,45,0
12,MQTT-DDoS-Connect_Flood_train.pcap.csv,MQTT,173036,45,0
13,Recon-VulScan_train.pcap.csv,Reconnaissance,2173,45,44
14,TCP_IP-DDoS-ICMP4_train.pcap.csv,TCP/IP DDoS,192741,45,202
15,TCP_IP-DoS-TCP2_train.pcap.csv,TCP/IP DoS,95521,45,0
16,TCP_IP-DDoS-ICMP5_train.pcap.csv,TCP/IP DDoS,195032,45,181
17,TCP_IP-DoS-SYN4_train.pcap.csv,TCP/IP DoS,110635,45,0
18,TCP_IP-DDoS-UDP6_train.pcap.csv,TCP/IP DDoS,202247,45,0
19,TCP_IP-DDoS-UDP5_train.pcap.csv,TCP/IP DDoS,205507,45,0
20,TCP_IP-DDoS-SYN4_train.pcap.csv,TCP/IP DDoS,196880,45,0
21,TCP_IP-DDoS-UDP7_train.pcap.csv,TCP/IP DDoS,197685,45,0
22,ARP_Spoofing_train.pcap.csv,ARP Spoofing,16047,45,0
23,TCP_IP-DDoS-TCP2_train.pcap.csv,TCP/IP DDoS,197081,45,0
24,TCP_IP-DoS-UDP4_train.pcap.csv,TCP/IP DoS,143301,45,0
25,TCP_IP-DoS-UDP3_train.pcap.csv,TCP/IP DoS,146146,45,0
26,TCP_IP-DoS-TCP1_train.pcap.csv,TCP/IP DoS,95407,45,0
27,Recon-OS_Scan_train.pcap.csv,Reconnaissance,16832,45,669
28,TCP_IP-DDoS-TCP1_train.pcap.csv,TCP/IP DDoS,202311,45,0
29,TCP_IP-DDoS-ICMP6_train.pcap.csv,TCP/IP DDoS,190875,45,68
30,Recon-Ping_Sweep_train.pcap.csv,Reconnaissance,740,45,0
31,TCP_IP-DoS-ICMP2_train.pcap.csv,TCP/IP DoS,96977,45,0
32,TCP_IP-DDoS-UDP4_train.pcap.csv,TCP/IP DDoS,206343,45,0
33,TCP_IP-DDoS-ICMP8_train.pcap.csv,TCP/IP DDoS,193340,45,0
34,TCP_IP-DDoS-UDP8_train.pcap.csv,TCP/IP DDoS,204105,45,0
35,MQTT-DoS-Publish_Flood_train.pcap.csv,MQTT,44376,45,0
36,TCP_IP-DoS-ICMP4_train.pcap.csv,TCP/IP DoS,106122,45,0
37,TCP_IP-DoS-SYN1_train.pcap.csv,TCP/IP DoS,111431,45,0
38,MQTT-DoS-Connect_Flood_train.pcap.csv,MQTT,12773,45,0
39,TCP_IP-DDoS-SYN2_train.pcap.csv,TCP/IP DDoS,203669,45,6
40,TCP_IP-DoS-ICMP3_train.pcap.csv,TCP/IP DoS,108686,45,0
41,TCP_IP-DoS-UDP2_train.pcap.csv,TCP/IP DoS,140492,45,0
42,MQTT-Malformed_Data_train.pcap.csv,MQTT,5130,45,0
43,TCP_IP-DDoS-SYN3_train.pcap.csv,TCP/IP DDoS,202023,45,10
44,TCP_IP-DDoS-SYN1_train.pcap.csv,TCP/IP DDoS,199390,45,0
45,TCP_IP-DoS-ICMP1_train.pcap.csv,TCP/IP DoS,104507,45,0
46,TCP_IP-DoS-SYN2_train.pcap.csv,TCP/IP DoS,111647,45,0
47,TCP_IP-DDoS-ICMP7_train.pcap.csv,TCP/IP DDoS,186022,45,1
48,TCP_IP-DDoS-TCP3_train.pcap.csv,TCP/IP DDoS,204075,45,0
49,TCP_IP-DDoS-UDP3_train.pcap.csv,TCP/IP DDoS,206604,45,0
50,TCP_IP-DDoS-ICMP2_train.pcap.csv,TCP/IP DDoS,194818,45,0

ATTACK FAMILY SUMMARY

           family  captures  records  duplicates
0    ARP Spoofing         1    16047           0
1          Benign         1   192732           0
2            MQTT         5   262938           0
3  Reconnaissance         4   103726        4447
4     TCP/IP DDoS        24  4779859         672
5      TCP/IP DoS        16  1805529           0

Inventory saved successfully.

In [2]:
# ============================================
# WEAR-CHAIN: STEP 2 - FEATURE ANALYSIS
# ============================================

feature_stats = []
for df in dataframes:
    source = df["source_file"].iloc[0]
    family = df["attack_family"].iloc[0]
    features = df[feature_columns].select_dtypes(include=np.number)

    for col in features.columns:
        s = features[col]
        feature_stats.append({
            "source_file": source,
            "family": family,
            "feature": col,
            "min": s.min(),
            "max": s.max(),
            "mean": s.mean(),
            "std": s.std(),
            "missing": s.isna().sum(),
            "infinite": np.isinf(s).sum(),
            "negative": (s < 0).sum(),
            "unique_values": s.nunique()
        })

stats_df = pd.DataFrame(feature_stats)

# Aggregate feature statistics
global_summary = (
    stats_df.groupby("feature")
    .agg(
        global_min=("min", "min"),
        global_max=("max", "max"),
        average_capture_mean=("mean", "mean"),
        captures_with_constant_feature=("unique_values", lambda x: (x <= 1).sum()),
        total_missing=("missing", "sum"),
        total_infinite=("infinite", "sum"),
        total_negative=("negative", "sum")
    )
    .reset_index()
)

print("GLOBAL FEATURE QUALITY")
display(global_summary)

# Sample representative rows
sampled_data = [df.sample(n=min(5000, len(df)), random_state=42) for df in dataframes]
eda_sample = pd.concat(sampled_data, ignore_index=True)

selected_features = [
    "Duration", "Rate", "Srate", "Header_Length", "Tot size",
    "IAT", "AVG", "Std", "Variance", "Protocol Type"
]
available_features = [col for col in selected_features if col in eda_sample.columns]

for col in available_features:
    eda_sample[col] = pd.to_numeric(eda_sample[col], errors='coerce')

family_medians = (
    eda_sample.groupby("attack_family")[available_features]
    .median()
    .round(4)
)

print("\nFEATURE MEDIANS BY ATTACK FAMILY")
display(family_medians)

# Correlation analysis
for col in feature_columns:
    eda_sample[col] = pd.to_numeric(eda_sample[col], errors='coerce')

numeric_features = eda_sample[feature_columns].select_dtypes(include=np.number)
correlation_matrix = numeric_features.corr()

upper_triangle = correlation_matrix.where(
    np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool)
)

correlation_pairs = upper_triangle.stack().reset_index()
correlation_pairs.columns = ["Feature_1", "Feature_2", "Correlation"]
correlation_pairs["Absolute_Correlation"] = correlation_pairs["Correlation"].abs()
correlation_pairs = correlation_pairs.sort_values("Absolute_Correlation", ascending=False)

print("\nTOP 20 CORRELATED FEATURES")
display(correlation_pairs.head(20))

# Save reports to BASE_OUT
global_summary.to_csv(BASE_OUT / "WEAR_CHAIN_feature_quality.csv", index=False)
family_medians.to_csv(BASE_OUT / "WEAR_CHAIN_family_medians.csv")
correlation_pairs.to_csv(BASE_OUT / "WEAR_CHAIN_correlations.csv", index=False)

print("\nEDA reports saved successfully.")

GLOBAL FEATURE QUALITY

,feature,global_min,global_max,average_capture_mean,captures_with_constant_feature,total_missing,total_infinite,total_negative
0,ARP,0.000000,1.000000e+00,1.525384e-02,0,0,0,0
1,AVG,42.000000,1.514000e+03,9.370684e+01,0,0,0,0
2,Covariance,0.000000,5.204379e+05,1.026158e+04,0,0,0,0
3,DHCP,0.000000,6.000000e-01,3.622514e-06,17,0,0,0
4,DNS,0.000000,1.000000e+00,4.089751e-04,0,0,0,0
5,Drate,0.000000,0.000000e+00,0.000000e+00,51,0,0,0
6,Duration,0.000000,2.550000e+02,6.544193e+01,0,0,0,0
7,HTTP,0.000000,1.000000e+00,5.922314e-04,8,0,0,0
8,HTTPS,0.000000,1.000000e+00,2.379560e-02,0,0,0,0
9,Header_Length,0.000000,9.895636e+06,1.221125e+05,0,0,0,0
10,IAT,-1.282061,1.694694e+08,8.468215e+07,0,0,0,1
11,ICMP,0.000000,1.000000e+00,2.354243e-01,9,0,0,0
12,IGMP,0.000000,7.000000e-01,8.656529e-06,26,0,0,0
13,IPv,0.000000,1.000000e+00,9.847462e-01,0,0,0,0
14,IRC,0.000000,1.111111e-01,4.292206e-05,32,0,0,0
15,LLC,0.000000,1.000000e+00,9.847462e-01,0,0,0,0
16,Magnitue,9.165151,5.502727e+01,1.180723e+01,0,0,0,0
17,Max,42.000000,1.514000e+03,1.302824e+02,0,0,0,0
18,Min,42.000000,1.514000e+03,7.119322e+01,0,0,0,0
19,Number,1.000000,1.500000e+01,9.498907e+00,0,0,0,0
20,Protocol Type,0.000000,1.700000e+01,7.511000e+00,0,0,0,0
21,Radius,0.000000,1.020232e+03,3.145260e+01,0,0,0,0
22,Rate,0.000000,2.097152e+06,1.184330e+04,0,0,0,0
23,SMTP,0.000000,1.000000e-01,4.383662e-05,32,0,0,0
24,SSH,0.000000,9.000000e-01,5.111556e-05,31,0,0,0
25,Srate,0.000000,2.097152e+06,1.184330e+04,0,0,0,0
26,Std,0.000000,7.211509e+02,2.226581e+01,0,0,0,0
27,TCP,0.000000,1.000000e+00,4.966152e-01,0,0,0,0
28,Telnet,0.000000,1.000000e-01,4.295770e-05,32,0,0,0
29,Tot size,42.000000,1.514000e+03,9.368936e+01,0,0,0,0
30,Tot sum,42.000000,2.346700e+04,9.833845e+02,0,0,0,0
31,UDP,0.000000,1.000000e+00,2.526977e-01,0,0,0,0
32,Variance,0.000000,1.000000e+00,1.701244e-01,0,0,0,0
33,Weight,1.000000,2.446000e+02,1.415208e+02,0,0,0,0
34,ack_count,0.000000,1.120000e+01,4.467508e-02,0,0,0,0
35,ack_flag_number,0.000000,1.000000e+00,1.723293e-01,0,0,0,0
36,cwr_flag_number,0.000000,1.000000e-01,1.079945e-05,28,0,0,0
37,ece_flag_number,0.000000,2.000000e-01,1.717336e-05,31,0,0,0
38,fin_count,0.000000,1.517400e+02,2.570097e-01,0,0,0,0
39,fin_flag_number,0.000000,1.000000e+00,6.423230e-03,0,0,0,0
40,psh_flag_number,0.000000,1.000000e+00,4.545969e-02,0,0,0,0
41,rst_count,0.000000,9.576500e+03,1.231209e+02,0,0,0,0
42,rst_flag_number,0.000000,1.000000e+00,5.794625e-02,0,0,0,0
43,syn_count,0.000000,1.070000e+01,3.668063e-01,0,0,0,0
44,syn_flag_number,0.000000,1.000000e+00,1.661156e-01,0,0,0,0

FEATURE MEDIANS BY ATTACK FAMILY

,Duration,Rate,Srate,Header_Length,Tot size,IAT,AVG,Std,Variance,Protocol Type
attack_family,,,,,,,,,,
ARP Spoofing,64.0,120.4402,120.4402,1668877.950,248.55,1.694021e+08,248.4654,81.4537,0.90,7.1
Benign,64.0,1.6525,1.6525,165386.450,80.90,1.694616e+08,83.0062,17.2686,0.90,6.0
MQTT,64.0,54.0663,54.0663,7498.475,100.88,8.466650e+07,102.3480,11.5907,0.88,6.0
Reconnaissance,64.0,7.0657,7.0657,112.000,58.00,1.694100e+08,58.0000,0.0000,0.00,6.0
TCP/IP DDoS,64.0,201.0967,201.0967,56.160,50.00,8.469667e+07,50.0000,0.0000,0.00,6.0
TCP/IP DoS,64.0,24.0534,24.0534,108.000,54.00,8.467507e+07,54.0000,0.0000,0.00,6.0

TOP 20 CORRELATED FEATURES

         Feature_1   Feature_2  Correlation  Absolute_Correlation
795            ARP         IPv    -1.000000              1.000000
796            ARP         LLC    -1.000000              1.000000
126           Rate       Srate     1.000000              1.000000
841            IPv         LLC     1.000000              1.000000
914            Std      Radius     0.999978              0.999978
935         Number      Weight     0.999873              0.999873
930            IAT      Weight     0.998613              0.998613
925            IAT      Number     0.998228              0.998228
905            AVG    Magnitue     0.983180              0.983180
940         Radius  Covariance     0.973033              0.973033
915            Std  Covariance     0.972953              0.972953
902            AVG    Tot size     0.965931              0.965931
896            Max    Magnitue     0.953480              0.953480
920       Tot size    Magnitue     0.953303              0.953303
65   Protocol Type         UDP     0.937835              0.937835
870        Tot sum         AVG     0.909796              0.909796
891            Max         AVG     0.907446              0.907446
875        Tot sum    Magnitue     0.900331              0.900331
893            Max    Tot size     0.887731              0.887731
872        Tot sum    Tot size     0.883112              0.883112

EDA reports saved successfully.

In [3]:
# ============================================
# WEAR-CHAIN: STEP 3 & 4 - DATA CLEANING
# ============================================

# Known corrupt rows identified during raw capture validation
rows_to_exclude = {
    "TCP_IP-DDoS-ICMP3_train.pcap.csv": [143967],
    "TCP_IP-DDoS-ICMP1_train.pcap.csv": [141777],
    "TCP_IP-DDoS-SYN1_train.pcap.csv": [147782],
    "Recon-Port_Scan_train.pcap.csv": [54545]
}

clean_dataframes = []
exclusion_report = []

for df in dataframes:
    source = df["source_file"].iloc[0]
    original_count = len(df)

    if source in rows_to_exclude:
        indices = rows_to_exclude[source]
        cleaned_df = df.loc[~df.index.isin(indices)].copy()
        removed_count = original_count - len(cleaned_df)
    else:
        cleaned_df = df.copy()
        removed_count = 0

    clean_dataframes.append(cleaned_df)
    exclusion_report.append({
        "source_file": source,
        "original_rows": original_count,
        "excluded_rows": removed_count,
        "remaining_rows": len(cleaned_df)
    })

cleaning_summary = pd.DataFrame(exclusion_report)
print("Original total rows:", sum(len(df) for df in dataframes))
print("Clean total rows:", sum(len(df) for df in clean_dataframes))
print("Total excluded rows:", sum(cleaning_summary["excluded_rows"]))

# Combine clean dataframes
combined_df = pd.concat(clean_dataframes, ignore_index=True)
model_features = [col for col in feature_columns if col != "Drate"]

for col in feature_columns:
    combined_df[col] = pd.to_numeric(combined_df[col], errors="coerce")

print("Combined dataset shape:", combined_df.shape)
print("Number of model features:", len(model_features))

Original total rows: 7160831
Clean total rows: 7160827
Total excluded rows: 4
Combined dataset shape: (7160827, 48)
Number of model features: 44

In [4]:
# ============================================================
# SECTION 05B — CAPTURE-AWARE DATASET PARTITIONING
# ============================================================
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42
split_df = combined_df.copy()

duplicate_aliases = {
    "Recon-VulScan_train.pcap (1).csv": "Recon-VulScan_train.pcap.csv",
    "TCP_IP-DoS-TCP1_train.pcap (1).csv": "TCP_IP-DoS-TCP1_train.pcap.csv"
}

for duplicate_name, canonical_name in duplicate_aliases.items():
    duplicate_present = (split_df["source_file"] == duplicate_name).any()
    canonical_present = (split_df["source_file"] == canonical_name).any()

    if duplicate_present and canonical_present:
        split_df = split_df[split_df["source_file"] != duplicate_name].copy()
    elif duplicate_present and not canonical_present:
        split_df.loc[split_df["source_file"] == duplicate_name, "source_file"] = canonical_name

capture_inventory = (
    split_df.groupby(["attack_family", "source_file"], as_index=False)
    .agg(record_count=("label", "size"), label_count=("label", "nunique"))
)

split_df["partition"] = None
single_capture_classes = ["Benign", "ARP Spoofing"]
multi_capture_classes = [f for f in split_df["attack_family"].unique() if f not in single_capture_classes]

capture_assignments = []
for family in sorted(multi_capture_classes):
    family_captures = (
        capture_inventory.loc[capture_inventory["attack_family"] == family, "source_file"]
        .sort_values().tolist()
    )
    n_captures = len(family_captures)
    if n_captures < 3:
        raise ValueError(f"{family} has fewer than 3 captures.")

    rng = np.random.default_rng(RANDOM_STATE + sum(ord(char) for char in family))
    shuffled = list(rng.permutation(family_captures))

    n_test = max(1, round(n_captures * 0.20))
    n_calibration = max(1, round(n_captures * 0.20))

    test_captures = shuffled[:n_test]
    calibration_captures = shuffled[n_test:n_test + n_calibration]
    development_captures = shuffled[n_test + n_calibration:]

    for c in development_captures: capture_assignments.append((family, c, "development"))
    for c in calibration_captures: capture_assignments.append((family, c, "calibration"))
    for c in test_captures: capture_assignments.append((family, c, "internal_test"))

capture_assignment_df = pd.DataFrame(
    capture_assignments, columns=["attack_family", "source_file", "partition"]
)

for row in capture_assignment_df.itertuples(index=False):
    mask = (split_df["attack_family"] == row.attack_family) & (split_df["source_file"] == row.source_file)
    split_df.loc[mask, "partition"] = row.partition

for family in single_capture_classes:
    family_indices = split_df.index[split_df["attack_family"] == family].to_numpy()
    if len(family_indices) == 0: continue

    dev_idx, cal_idx = train_test_split(family_indices, test_size=0.20, random_state=RANDOM_STATE, shuffle=True)
    split_df.loc[dev_idx, "partition"] = "development"
    split_df.loc[cal_idx, "partition"] = "calibration"

partition_summary = split_df.groupby(["partition", "attack_family"]).size().unstack(fill_value=0)
print("\nPARTITION RECORD COUNTS")
display(partition_summary)

split_df.to_csv(BASE_OUT / "WEAR_CHAIN_partitioned_dataset.csv", index=False)
capture_assignment_df.to_csv(BASE_OUT / "WEAR_CHAIN_capture_assignments.csv", index=False)
partition_summary.to_csv(BASE_OUT / "WEAR_CHAIN_partition_summary.csv")
print("\nSection 05B complete.")

PARTITION RECORD COUNTS

attack_family,ARP Spoofing,Benign,MQTT,Reconnaissance,TCP/IP DDoS,TCP/IP DoS
partition,,,,,,
calibration,3210,38547,12773,16832,1008055,329200
development,12837,154185,245035,84720,2776131,1176268
internal_test,0,0,5130,2173,995670,300061

Section 05B complete.

In [5]:
# ============================================================
# SECTION 05C — INDEPENDENT TEST DATASET PREPARATION
# ============================================================

# Read independent test CSV captures directly from DATA_DIR
TEST_FILES = {
    "Benign": DATA_DIR / "Benign_test.pcap.csv",
    "ARP Spoofing": DATA_DIR / "ARP_Spoofing_test.pcap.csv"
}

family_to_label = combined_df.groupby("attack_family")["label"].first().to_dict()

external_test_frames = []
test_audit = []

for family, file_path in TEST_FILES.items():
    print("Processing:", file_path.name)
    if not file_path.exists():
        raise FileNotFoundError(f"Required test capture not found: {file_path}")

    raw_test = pd.read_csv(file_path)
    raw_test.columns = raw_test.columns.astype(str).str.strip()

    test_features = raw_test[model_features].copy()
    for feature in model_features:
        test_features[feature] = pd.to_numeric(test_features[feature], errors="coerce")

    missing_count = int(test_features.isna().sum().sum())
    infinite_count = int(np.isinf(test_features.to_numpy(dtype=float)).sum())

    if missing_count > 0 or infinite_count > 0:
        raise ValueError(f"Invalid features in {file_path.name}: missing={missing_count}, infinite={infinite_count}")

    test_features["label"] = family_to_label[family]
    test_features["attack_family"] = family
    test_features["source_file"] = file_path.name
    test_features["partition"] = "external_test"

    external_test_frames.append(test_features)
    test_audit.append({
        "attack_family": family,
        "source_file": file_path.name,
        "records": len(test_features),
        "assigned_label": family_to_label[family]
    })

external_test_df = pd.concat(external_test_frames, ignore_index=True)
external_test_audit_df = pd.DataFrame(test_audit)

external_test_df.to_csv(BASE_OUT / "WEAR_CHAIN_external_test_dataset.csv", index=False)
external_test_audit_df.to_csv(BASE_OUT / "WEAR_CHAIN_external_test_audit.csv", index=False)
print("Section 05C complete.")

Processing: Benign_test.pcap.csv
Processing: ARP_Spoofing_test.pcap.csv
Section 05C complete.

In [6]:
# ============================================================
# SECTION 06 & 06A — XGBOOST MODEL & CALIBRATION
# ============================================================
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score, confusion_matrix
import joblib

development_df = split_df[split_df["partition"] == "development"].copy()
calibration_df = split_df[split_df["partition"] == "calibration"].copy()

X_train = development_df[model_features].copy()
y_train = development_df["label"].astype(int).copy()
X_calibration = calibration_df[model_features].copy()
y_calibration = calibration_df["label"].astype(int).copy()

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.08,
    subsample=0.80,
    colsample_bytree=0.80,
    objective="binary:logistic",
    eval_metric="logloss",
    tree_method="hist",
    random_state=42,
    n_jobs=-1
)

print("Training baseline XGBoost model...")
xgb_model.fit(X_train, y_train)

calibration_probabilities = xgb_model.predict_proba(X_calibration)[:, 1]

# Calibrate Operating Threshold (Target FPR 1%)
benign_scores = calibration_probabilities[y_calibration.to_numpy() == 0]
XGB_THRESHOLD = float(np.quantile(benign_scores, 1 - 0.01))
print(f"Calibrated XGBoost Threshold (FPR 1%): {XGB_THRESHOLD:.6f}")

xgb_calibration_results = calibration_df[["attack_family", "source_file", "label"]].copy()
xgb_calibration_results["attack_probability"] = calibration_probabilities
xgb_calibration_results["predicted_label"] = (calibration_probabilities >= XGB_THRESHOLD).astype(int)

joblib.dump(xgb_model, BASE_OUT / "WEAR_CHAIN_XGBoost_baseline.pkl")
xgb_calibration_results.to_csv(BASE_OUT / "WEAR_CHAIN_XGBoost_calibration_predictions.csv", index=False)
print("XGBoost trained and saved.")

Training baseline XGBoost model...
Calibrated XGBoost Threshold (FPR 1%): 0.340408
XGBoost trained and saved.

In [7]:
# ============================================================
# SECTION 07 — BENIGN-TRAFFIC AUTOENCODER
# ============================================================
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import joblib

benign_development = development_df[development_df["label"] == 0].copy()
X_benign_train = benign_development[model_features].astype(np.float32)
X_calibration_raw = calibration_df[model_features].astype(np.float32)
y_cal = calibration_df["label"].astype(int).to_numpy()

ae_scaler = StandardScaler()
X_benign_scaled = ae_scaler.fit_transform(X_benign_train).astype(np.float32)
X_calibration_scaled = ae_scaler.transform(X_calibration_raw).astype(np.float32)

input_dim = len(model_features)
inputs = Input(shape=(input_dim,), name="input_features")
encoded = Dense(32, activation="relu")(inputs)
encoded = Dense(16, activation="relu")(encoded)
latent = Dense(8, activation="relu")(encoded)
decoded = Dense(16, activation="relu")(latent)
decoded = Dense(32, activation="relu")(decoded)
outputs = Dense(input_dim, activation="linear")(decoded)

autoencoder = Model(inputs=inputs, outputs=outputs, name="Benign_Autoencoder")
autoencoder.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse")

early_stopping = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True, verbose=1)

print("Training autoencoder...")
autoencoder.fit(
    X_benign_scaled, X_benign_scaled,
    epochs=50, batch_size=256, validation_split=0.20,
    callbacks=[early_stopping], verbose=1
)

def get_reconstruction_error(model, data):
    reconstructed = model.predict(data, batch_size=1024, verbose=0)
    return np.mean(np.square(data - reconstructed), axis=1)

calibration_errors = get_reconstruction_error(autoencoder, X_calibration_scaled)
benign_cal_errors = calibration_errors[y_cal == 0]
AE_THRESHOLD = float(np.quantile(benign_cal_errors, 1 - 0.01))
print(f"Calibrated Autoencoder Threshold: {AE_THRESHOLD:.6f}")

# Save model and scaler
autoencoder.save(BASE_OUT / "WEAR_CHAIN_autoencoder.keras")
joblib.dump(ae_scaler, BASE_OUT / "WEAR_CHAIN_autoencoder_scaler.pkl")

ae_calibration_results = calibration_df[["attack_family", "source_file", "label"]].copy()
ae_calibration_results["anomaly_score"] = calibration_errors
ae_calibration_results["anomaly_prediction"] = (calibration_errors >= AE_THRESHOLD).astype(int)
ae_calibration_results.to_csv(BASE_OUT / "WEAR_CHAIN_autoencoder_calibration_scores.csv", index=False)
print("Autoencoder saved successfully.")

2026-10-08 11:00:15.135130: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Training autoencoder...
Epoch 1/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.4780 - val_loss: 0.2103
Epoch 2/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2919 - val_loss: 0.1693
Epoch 3/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2411 - val_loss: 0.1624
Epoch 4/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1827 - val_loss: 0.1388
Epoch 5/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1470 - val_loss: 0.1271
Epoch 6/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1301 - val_loss: 0.1204
Epoch 7/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1153 - val_loss: 0.1176
Epoch 8/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1077 - val_loss: 0.1026
Epoch 9/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0922 - val_loss: 0.0898
Epoch 10/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0864 - val_loss: 0.0837
Epoch 11/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0830 - val_loss: 0.0718
Epoch 12/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0769 - val_loss: 0.0639
Epoch 13/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0729 - val_loss: 0.0615
Epoch 14/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0687 - val_loss: 0.0652
Epoch 15/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0681 - val_loss: 0.0583
Epoch 16/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0600 - val_loss: 0.0542
Epoch 17/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0588 - val_loss: 0.0556
Epoch 18/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0585 - val_loss: 0.0575
Epoch 19/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0562 - val_loss: 0.0628
Epoch 20/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0605 - val_loss: 0.0494
Epoch 21/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0509 - val_loss: 0.0501
Epoch 22/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0567 - val_loss: 0.0477
Epoch 23/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0502 - val_loss: 0.0476
Epoch 24/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0461 - val_loss: 0.0455
Epoch 25/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0450 - val_loss: 0.0485
Epoch 26/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0467 - val_loss: 0.0467
Epoch 27/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0458 - val_loss: 0.0451
Epoch 28/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0542 - val_loss: 0.0449
Epoch 29/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0459 - val_loss: 0.0416
Epoch 30/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0413 - val_loss: 0.0502
Epoch 31/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0420 - val_loss: 0.0407
Epoch 32/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0422 - val_loss: 0.0402
Epoch 33/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0413 - val_loss: 0.0409
Epoch 34/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0386 - val_loss: 0.0411
Epoch 35/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0383 - val_loss: 0.0421
Epoch 36/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0442 - val_loss: 0.0382
Epoch 37/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0387 - val_loss: 0.0467
Epoch 38/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0361 - val_loss: 0.0375
Epoch 39/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0375 - val_loss: 0.0368
Epoch 40/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0365 - val_loss: 0.0394
Epoch 41/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0349 - val_loss: 0.0393
Epoch 42/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0352 - val_loss: 0.0387
Epoch 43/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0360 - val_loss: 0.0362
Epoch 44/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0319 - val_loss: 0.0378
Epoch 45/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0318 - val_loss: 0.0372
Epoch 46/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0333 - val_loss: 0.0555
Epoch 47/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0368 - val_loss: 0.0369
Epoch 48/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0314 - val_loss: 0.0355
Epoch 49/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0350 - val_loss: 0.0501
Epoch 50/50
482/482 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0338 - val_loss: 0.0409
Restoring model weights from the end of the best epoch: 48.
Calibrated Autoencoder Threshold: 0.369166
Autoencoder saved successfully.

In [8]:
# ================================================================
# SECTION 08 — HYBRID INTRUSION DETECTION SCORE FUSION
# ================================================================

benign_mask = (y_cal == 0)

def empirical_percentile_scores(scores, benign_reference):
    reference = np.sort(np.asarray(benign_reference, dtype=np.float64))
    return np.searchsorted(reference, scores, side="right") / len(reference)

xgb_scores = calibration_probabilities
ae_scores = calibration_errors

xgb_normalized = empirical_percentile_scores(xgb_scores, xgb_scores[benign_mask])
ae_normalized = empirical_percentile_scores(ae_scores, ae_scores[benign_mask])

hybrid_max_scores = np.maximum(xgb_normalized, ae_normalized)
hybrid_average_scores = (xgb_normalized + ae_normalized) / 2

HYBRID_MAX_THRESHOLD = float(np.quantile(hybrid_max_scores[benign_mask], 0.99))
HYBRID_AVERAGE_THRESHOLD = float(np.quantile(hybrid_average_scores[benign_mask], 0.99))

hybrid_scores_df = pd.DataFrame({
    "label": y_cal,
    "attack_family": calibration_df["attack_family"].to_numpy(),
    "xgb_score": xgb_scores,
    "ae_score": ae_scores,
    "xgb_percentile": xgb_normalized,
    "ae_percentile": ae_normalized,
    "hybrid_max_score": hybrid_max_scores,
    "hybrid_average_score": hybrid_average_scores
})

hybrid_scores_df.to_csv(BASE_OUT / "WEAR_CHAIN_hybrid_calibration_scores.csv", index=False)
print(f"Hybrid Max Threshold: {HYBRID_MAX_THRESHOLD:.8f}")
print(f"Hybrid Avg Threshold: {HYBRID_AVERAGE_THRESHOLD:.8f}")
print("Section 08 completed.")

Hybrid Max Threshold: 0.99485148
Hybrid Avg Threshold: 0.95169637
Section 08 completed.

In [9]:
# ================================================================
# SECTION 09 — EVALUATION ON UNTOUCHED TEST CAPTURES
# ================================================================

internal_test_df = split_df.loc[split_df["partition"] == "internal_test"].copy()
internal_test_df["test_source"] = "Internal"
external_test_df["test_source"] = "External"

test_df = pd.concat([external_test_df, internal_test_df], ignore_index=True)
test_df["label"] = test_df["label"].astype(int)

X_test = test_df[model_features].astype(np.float32)
y_test = test_df["label"].to_numpy(dtype=int)

xgb_test_scores = xgb_model.predict_proba(X_test)[:, 1]
X_test_scaled = ae_scaler.transform(X_test)
ae_test_scores = get_reconstruction_error(autoencoder, X_test_scaled)

cal_benign = hybrid_scores_df.loc[hybrid_scores_df["label"] == 0]
xgb_benign_ref = np.sort(cal_benign["xgb_score"].to_numpy(dtype=np.float64))
ae_benign_ref = np.sort(cal_benign["ae_score"].to_numpy(dtype=np.float64))

xgb_test_percentile = empirical_percentile_scores(xgb_test_scores, xgb_benign_ref)
ae_test_percentile = empirical_percentile_scores(ae_test_scores, ae_benign_ref)

hybrid_max_test_scores = np.maximum(xgb_test_percentile, ae_test_percentile)
hybrid_average_test_scores = (xgb_test_percentile + ae_test_percentile) / 2

thresholds = {
    "XGBoost": XGB_THRESHOLD,
    "Autoencoder": AE_THRESHOLD,
    "Hybrid_Max": HYBRID_MAX_THRESHOLD,
    "Hybrid_Average": HYBRID_AVERAGE_THRESHOLD
}

test_scores = {
    "XGBoost": xgb_test_scores,
    "Autoencoder": ae_test_scores,
    "Hybrid_Max": hybrid_max_test_scores,
    "Hybrid_Average": hybrid_average_test_scores
}

prediction_output = test_df[["test_source", "source_file", "label", "attack_family"]].copy()
prediction_output["xgb_score"] = xgb_test_scores
prediction_output["ae_score"] = ae_test_scores
prediction_output["xgb_percentile"] = xgb_test_percentile
prediction_output["ae_percentile"] = ae_test_percentile
prediction_output["hybrid_max_score"] = hybrid_max_test_scores
prediction_output["hybrid_average_score"] = hybrid_average_test_scores

for model_name, scores in test_scores.items():
    prediction_output[f"{model_name}_prediction"] = (scores >= thresholds[model_name]).astype(int)

prediction_output.to_csv(BASE_OUT / "WEAR_CHAIN_unseen_test_predictions.csv", index=False)
print("Section 09 complete. Predictions saved to WEAR_CHAIN_unseen_test_predictions.csv.")

Section 09 complete. Predictions saved to WEAR_CHAIN_unseen_test_predictions.csv.

In [10]:
# ================================================================
# SECTION 10 — BENIGN TRAFFIC DISTRIBUTION-SHIFT ANALYSIS
# ================================================================
import os
import numpy as np
import pandas as pd
from scipy.stats import ks_2samp

# 1. Verify required data
required_objects = [
    "calibration_df", "external_test_df", "model_features",
    "hybrid_scores_df", "xgb_test_scores", "ae_test_scores"
]
for obj_name in required_objects:
    if obj_name not in globals():
        raise NameError(f"{obj_name} is missing. Run previous sections first.")

calibration_reference = hybrid_scores_df.copy()
calibration_benign = calibration_df.loc[calibration_df["label"] == 0].copy()
external_benign = external_test_df.loc[external_test_df["label"] == 0].copy()
external_arp = external_test_df.loc[external_test_df["label"] == 1].copy()

print("=" * 85)
print("DISTRIBUTION-SHIFT DATA SUMMARY")
print("=" * 85)
print("Calibration benign records:", len(calibration_benign))
print("External benign records:", len(external_benign))
print("External ARP attack records:", len(external_arp))
print("Features:", len(model_features))

# 2. Feature-Level Drift Analysis (PSI & KS Test)
def calculate_psi(reference, comparison, bins=10):
    reference = np.asarray(reference, dtype=np.float64)
    comparison = np.asarray(comparison, dtype=np.float64)
    quantiles = np.linspace(0, 1, bins + 1)
    edges = np.unique(np.quantile(reference, quantiles))
    if len(edges) < 3:
        return np.nan

    edges[0] = -np.inf
    edges[-1] = np.inf
    ref_counts, _ = np.histogram(reference, bins=edges)
    comp_counts, _ = np.histogram(comparison, bins=edges)

    ref_pct = np.clip(ref_counts / len(reference), 1e-6, None)
    comp_pct = np.clip(comp_counts / len(comparison), 1e-6, None)
    return float(np.sum((comp_pct - ref_pct) * np.log(comp_pct / ref_pct)))

drift_results = []
for feature in model_features:
    reference = calibration_benign[feature].to_numpy(dtype=np.float64)
    comparison = external_benign[feature].to_numpy(dtype=np.float64)
    ks_result = ks_2samp(reference, comparison, alternative="two-sided", method="auto")

    ref_std = np.std(reference, ddof=1)
    comp_std = np.std(comparison, ddof=1)
    pooled_std = np.sqrt(((len(reference) - 1) * ref_std**2 + (len(comparison) - 1) * comp_std**2) / (len(reference) + len(comparison) - 2))
    smd = (np.mean(comparison) - np.mean(reference)) / pooled_std if pooled_std > 0 else np.nan

    drift_results.append({
        "Feature": feature,
        "Calibration_Mean": np.mean(reference),
        "External_Mean": np.mean(comparison),
        "Calibration_Median": np.median(reference),
        "External_Median": np.median(comparison),
        "KS_Statistic": ks_result.statistic,
        "KS_P_Value": ks_result.pvalue,
        "Standardized_Mean_Difference": smd,
        "PSI": calculate_psi(reference, comparison)
    })

feature_drift_df = pd.DataFrame(drift_results).sort_values(["KS_Statistic", "PSI"], ascending=False).reset_index(drop=True)

print("\nTOP 20 FEATURES BY KS DISTRIBUTION DIFFERENCE")
display(feature_drift_df.head(20).round(6))

# 3. Model Score Shift
cal_benign_scores = calibration_reference.loc[calibration_reference["label"] == 0]
cal_xgb = cal_benign_scores["xgb_score"].to_numpy()
cal_ae = cal_benign_scores["ae_score"].to_numpy()

external_count = len(external_test_df)
external_xgb = xgb_test_scores[:external_count]
external_ae = ae_test_scores[:external_count]
external_labels = external_test_df["label"].to_numpy()

external_xgb_benign = external_xgb[external_labels == 0]
external_ae_benign = external_ae[external_labels == 0]
external_xgb_arp = external_xgb[external_labels == 1]
external_ae_arp = external_ae[external_labels == 1]

def score_distribution_summary(name, values):
    values = np.asarray(values, dtype=np.float64)
    return {
        "Traffic_Group": name, "Records": len(values),
        "Mean": np.mean(values), "Std": np.std(values), "Minimum": np.min(values),
        "P50": np.quantile(values, 0.50), "P90": np.quantile(values, 0.90),
        "P95": np.quantile(values, 0.95), "P99": np.quantile(values, 0.99),
        "Maximum": np.max(values)
    }

score_distribution_df = pd.DataFrame([
    score_distribution_summary("Calibration_Benign_XGB", cal_xgb),
    score_distribution_summary("External_Benign_XGB", external_xgb_benign),
    score_distribution_summary("External_ARP_XGB", external_xgb_arp),
    score_distribution_summary("Calibration_Benign_AE", cal_ae),
    score_distribution_summary("External_Benign_AE", external_ae_benign),
    score_distribution_summary("External_ARP_AE", external_ae_arp)
])

# Save Section 10 results
feature_drift_df.to_csv(BASE_OUT / "WEAR_CHAIN_feature_distribution_drift.csv", index=False)
score_distribution_df.to_csv(BASE_OUT / "WEAR_CHAIN_score_distribution_summary.csv", index=False)
print("\nSection 10 completed.")

=====================================================================================
DISTRIBUTION-SHIFT DATA SUMMARY
=====================================================================================
Calibration benign records: 38547
External benign records: 37607
External ARP attack records: 1744
Features: 44

TOP 20 FEATURES BY KS DISTRIBUTION DIFFERENCE

,Feature,Calibration_Mean,External_Mean,Calibration_Median,External_Median,KS_Statistic,KS_P_Value,Standardized_Mean_Difference,PSI
0,IAT,8.460731e+07,8.475085e+07,0.100906,1.694694e+08,0.500093,0.0,0.001694,4.544782
1,Min,1.372854e+02,2.115112e+02,66.000000,6.600000e+01,0.113314,0.0,0.202156,0.102658
2,Header_Length,4.159135e+05,7.732200e+05,170173.700000,1.921468e+05,0.109355,0.0,0.261618,0.101787
3,Rate,2.134308e+02,8.013927e+02,1.651093,1.721357e+00,0.104597,0.0,0.185371,0.086732
4,Srate,2.134308e+02,8.013927e+02,1.651093,1.721357e+00,0.104597,0.0,0.185371,0.086732
5,Covariance,1.711608e+04,1.084632e+04,316.640956,2.538217e+02,0.093361,0.0,-0.134934,0.052730
6,Std,6.215961e+01,4.549992e+01,17.210689,1.539764e+01,0.093328,0.0,-0.174110,0.054817
7,Radius,8.781571e+01,6.426023e+01,24.174817,2.172236e+01,0.093113,0.0,-0.173912,0.054641
8,rst_count,2.268815e+03,1.986988e+03,1798.100000,1.371800e+03,0.091149,0.0,-0.146007,0.053598
9,UDP,7.337100e-02,1.529180e-01,0.000000,0.000000e+00,0.090656,0.0,0.317742,0.051364
10,Protocol Type,6.687112e+00,7.574694e+00,6.000000,6.000000e+00,0.090455,0.0,0.314149,0.053796
11,psh_flag_number,4.153450e-01,3.770390e-01,0.500000,5.000000e-01,0.090167,0.0,-0.192866,0.050265
12,syn_count,1.394580e-01,3.355200e-02,0.000000,0.000000e+00,0.087963,0.0,-0.341835,0.131583
13,TCP,9.065580e-01,8.291330e-01,1.000000,1.000000e+00,0.085261,0.0,-0.293183,0.060088
14,ack_flag_number,9.052970e-01,8.282630e-01,1.000000,1.000000e+00,0.084620,0.0,-0.291127,0.072746
15,HTTPS,1.030300e-01,3.554900e-02,0.000000,0.000000e+00,0.079796,0.0,-0.320535,0.079626
16,Tot size,1.863166e+02,2.434478e+02,80.900000,8.140000e+01,0.077349,0.0,0.151524,0.071154
17,AVG,1.861589e+02,2.430167e+02,83.036457,8.644024e+01,0.072478,0.0,0.150921,0.055535
18,Magnitue,1.638850e+01,1.800029e+01,12.877955,1.313558e+01,0.072240,0.0,0.141164,0.056087
19,HTTP,2.225300e-02,8.660500e-02,0.000000,0.000000e+00,0.067028,0.0,0.291464,NaN

Section 10 completed.

In [11]:
# ================================================================
# SECTION 11 — IAT AND FEATURE-IMPORTANCE INVESTIGATION
# ================================================================
cal_benign = calibration_df.loc[calibration_df["label"] == 0].copy()
ext_benign = external_test_df.loc[external_test_df["label"] == 0].copy()
ext_arp = external_test_df.loc[external_test_df["label"] == 1].copy()

cal_benign_mask = (calibration_df["label"].to_numpy() == 0)
cal_benign_xgb = calibration_reference.loc[cal_benign_mask, "xgb_score"].to_numpy()
cal_benign_ae = calibration_reference.loc[cal_benign_mask, "ae_score"].to_numpy()

# Descriptive Statistics of IAT
def iat_summary(name, values):
    values = pd.to_numeric(pd.Series(values), errors="coerce").dropna().to_numpy(dtype=np.float64)
    return {
        "Dataset": name, "Records": len(values),
        "Zero_Count": int((values == 0).sum()), "Negative_Count": int((values < 0).sum()),
        "Mean": np.mean(values), "Std": np.std(values), "Minimum": np.min(values),
        "P50": np.quantile(values, 0.50), "P95": np.quantile(values, 0.95), "Maximum": np.max(values)
    }

iat_summary_df = pd.DataFrame([
    iat_summary("Calibration_Benign", cal_benign["IAT"]),
    iat_summary("External_Benign", ext_benign["IAT"]),
    iat_summary("External_ARP", ext_arp["IAT"])
])

print("IAT DESCRIPTIVE STATISTICS")
display(iat_summary_df.round(6))

# XGBoost Feature Importance
importance_values = xgb_model.feature_importances_
feature_importance_df = pd.DataFrame({
    "Feature": model_features,
    "Importance": importance_values
}).sort_values("Importance", ascending=False).reset_index(drop=True)

print("\nTOP 20 XGBOOST FEATURES BY IMPORTANCE")
display(feature_importance_df.head(20).round(8))

combined_diagnostic_df = feature_drift_df.merge(feature_importance_df, on="Feature", how="left").sort_values("Importance", ascending=False).reset_index(drop=True)

# Save Section 11 files
iat_summary_df.to_csv(BASE_OUT / "WEAR_CHAIN_IAT_descriptive_statistics.csv", index=False)
feature_importance_df.to_csv(BASE_OUT / "WEAR_CHAIN_XGBoost_feature_importance.csv", index=False)
combined_diagnostic_df.to_csv(BASE_OUT / "WEAR_CHAIN_feature_drift_importance_combined.csv", index=False)
print("Section 11 completed.")

IAT DESCRIPTIVE STATISTICS

,Dataset,Records,Zero_Count,Negative_Count,Mean,Std,Minimum,P50,P95,Maximum
0,Calibration_Benign,38547,77,1,8.460731e+07,8.473251e+07,-1.282061,1.009060e-01,1.694687e+08,1.694694e+08
1,External_Benign,37607,0,0,8.475085e+07,8.473508e+07,0.000002,1.694694e+08,1.694708e+08,1.694708e+08
2,External_ARP,1744,1,0,8.470138e+07,8.470138e+07,0.000000,8.470137e+07,1.694028e+08,1.694028e+08

TOP 20 XGBOOST FEATURES BY IMPORTANCE

            Feature  Importance
0         rst_count    0.411146
1          Magnitue    0.255509
2         fin_count    0.109701
3            Number    0.066978
4               IAT    0.047787
5            Weight    0.027473
6   ack_flag_number    0.009734
7              Rate    0.007923
8               ARP    0.006781
9             Srate    0.006221
10         Tot size    0.006138
11  syn_flag_number    0.005537
12              AVG    0.003695
13             HTTP    0.003688
14            HTTPS    0.003626
15           Radius    0.003240
16             ICMP    0.002670
17              Max    0.002412
18  rst_flag_number    0.001793
19              UDP    0.001766

Section 11 completed.

In [12]:
# ================================================================
# SECTION 12 — EXTERNAL BENIGN FALSE-POSITIVE INVESTIGATION
# ================================================================
external_count = len(external_test_df)
external_scores = np.asarray(xgb_test_scores[:external_count])
external_labels = external_test_df["label"].to_numpy()
external_predictions = (external_scores >= thresholds["XGBoost"]).astype(int)

external_benign_mask = external_labels == 0
benign_predictions = external_predictions[external_benign_mask]
benign_features = external_test_df.loc[external_benign_mask, model_features].copy().reset_index(drop=True)
benign_scores = external_scores[external_benign_mask]

false_positive_mask = benign_predictions == 1
true_negative_mask = benign_predictions == 0

fp_features = benign_features.loc[false_positive_mask].copy()
tn_features = benign_features.loc[true_negative_mask].copy()
fp_scores = benign_scores[false_positive_mask]
tn_scores = benign_scores[true_negative_mask]

comparison_results = []
for feature in model_features:
    tn_values = tn_features[feature].to_numpy(dtype=np.float64)
    fp_values = fp_features[feature].to_numpy(dtype=np.float64)
    pooled_std = np.sqrt((np.std(tn_values)**2 + np.std(fp_values)**2) / 2)
    smd = (np.mean(fp_values) - np.mean(tn_values)) / pooled_std if pooled_std > 0 else 0.0
    ks_result = ks_2samp(tn_values, fp_values)

    comparison_results.append({
        "Feature": feature,
        "TN_Mean": np.mean(tn_values), "FP_Mean": np.mean(fp_values),
        "TN_Median": np.median(tn_values), "FP_Median": np.median(fp_values),
        "KS_Statistic": ks_result.statistic, "KS_P_Value": ks_result.pvalue,
        "Standardized_Mean_Difference": smd, "Absolute_SMD": abs(smd)
    })

fp_comparison_df = pd.DataFrame(comparison_results).sort_values(["KS_Statistic", "Absolute_SMD"], ascending=False).reset_index(drop=True)

fp_importance_df = fp_comparison_df.merge(feature_importance_df, on="Feature", how="left")
fp_importance_df["Diagnostic_Rank_Sum"] = (
    fp_importance_df["KS_Statistic"].rank(ascending=False, method="min") +
    fp_importance_df["Importance"].rank(ascending=False, method="min")
)
fp_importance_df = fp_importance_df.sort_values("Diagnostic_Rank_Sum").reset_index(drop=True)

print("TOP 20 FEATURES COMBINING MODEL IMPORTANCE AND FP DIFFERENCE")
display(fp_importance_df.head(20).round(6))

fp_comparison_df.to_csv(BASE_OUT / "WEAR_CHAIN_external_FP_feature_comparison.csv", index=False)
fp_importance_df.to_csv(BASE_OUT / "WEAR_CHAIN_external_FP_importance_analysis.csv", index=False)
print("Section 12 completed.")

TOP 20 FEATURES COMBINING MODEL IMPORTANCE AND FP DIFFERENCE

,Feature,TN_Mean,FP_Mean,TN_Median,FP_Median,KS_Statistic,KS_P_Value,Standardized_Mean_Difference,Absolute_SMD,Importance,Diagnostic_Rank_Sum
0,rst_count,2.075198e+03,3.124757e+01,1.491400e+03,0.000000e+00,0.783431,0.000000,-1.500415,1.500415,0.411146,6.0
1,ack_flag_number,8.603320e-01,1.172520e-01,1.000000e+00,0.000000e+00,0.799230,0.000000,-2.746345,2.746345,0.009734,10.0
2,Rate,8.214498e+02,3.567007e+02,1.681177e+00,5.361852e+01,0.729195,0.000000,-0.106566,0.106566,0.007923,14.0
3,IAT,8.857340e+07,1.822300e-02,1.694694e+08,1.720100e-02,0.706731,0.000000,-1.479793,1.479793,0.047787,14.0
4,Srate,8.214498e+02,3.567007e+02,1.681177e+00,5.361852e+01,0.729195,0.000000,-0.106566,0.106566,0.006221,16.0
5,Number,9.679177e+00,5.494763e+00,1.350000e+01,5.500000e+00,0.522454,0.000000,-1.479738,1.479738,0.066978,18.0
6,Magnitue,1.816029e+01,1.445271e+01,1.303987e+01,1.426853e+01,0.499388,0.000000,-0.400939,0.400939,0.255509,18.0
7,Weight,1.461661e+02,3.845471e+01,2.446000e+02,3.850000e+01,0.522454,0.000000,-1.479562,1.479562,0.027473,20.0
8,UDP,1.207480e-01,8.661740e-01,0.000000e+00,1.000000e+00,0.810012,0.000000,2.736701,2.736701,0.001766,21.0
9,Tot size,2.496081e+02,1.068650e+02,8.120000e+01,1.023000e+02,0.532511,0.000000,-0.465358,0.465358,0.006138,24.0
10,AVG,2.491386e+02,1.072868e+02,8.522968e+01,1.018009e+02,0.496869,0.000000,-0.461821,0.461821,0.003695,30.0
11,Header_Length,7.292596e+05,1.747878e+06,1.809458e+05,1.683937e+06,0.655850,0.000000,0.727793,0.727793,0.001547,31.0
12,psh_flag_number,3.916190e-01,5.378900e-02,5.000000e-01,0.000000e+00,0.706771,0.000000,-1.964692,1.964692,0.001357,32.0
13,TCP,8.611910e-01,1.183610e-01,1.000000e+00,0.000000e+00,0.798919,0.000000,-2.735779,2.735779,0.000786,35.0
14,Radius,6.610517e+01,2.335558e+01,2.194905e+01,4.509840e+00,0.471204,0.000000,-0.430963,0.430963,0.003240,35.0
15,fin_count,2.040000e-03,1.725000e-03,0.000000e+00,0.000000e+00,0.001574,1.000000,-0.010541,0.010541,0.109701,36.0
16,Protocol Type,7.220159e+00,1.543518e+01,6.000000e+00,1.700000e+01,0.805217,0.000000,2.627418,2.627418,0.000468,37.0
17,HTTP,9.047800e-02,7.390000e-04,0.000000e+00,0.000000e+00,0.091068,0.000000,-0.444495,0.444495,0.003688,38.0
18,ARP,1.790500e-02,1.540400e-02,0.000000e+00,0.000000e+00,0.010448,0.995193,-0.028889,0.028889,0.006781,38.0
19,HTTPS,3.600200e-02,2.550800e-02,0.000000e+00,0.000000e+00,0.041540,0.009137,-0.090053,0.090053,0.003626,40.0

Section 12 completed.

In [13]:
# ================================================================
# SECTION 13 — REPAIR AND FINALIZE PROTOCOL DIAGNOSTICS
# ================================================================

# 1. Build protocol_diagnostic_df across datasets
diagnostic_subsets = []
for name, dset in [
    ("Development", development_df),
    ("Calibration", calibration_df),
    ("External", external_test_df)
]:
    d = dset.copy()
    d["dataset"] = name
    if "xgb_score" not in d.columns:
        X_sub = d[model_features].astype(np.float32)
        d["xgb_score"] = xgb_model.predict_proba(X_sub)[:, 1]
    d["prediction"] = (d["xgb_score"] >= thresholds["XGBoost"]).astype(int)

    # Derive Protocol_Pattern
    tcp_val = pd.to_numeric(d["TCP"], errors="coerce").fillna(0) if "TCP" in d.columns else 0
    udp_val = pd.to_numeric(d["UDP"], errors="coerce").fillna(0) if "UDP" in d.columns else 0
    d["Protocol_Pattern"] = np.select(
        [(tcp_val > 0) & (udp_val == 0), (udp_val > 0) & (tcp_val == 0), (tcp_val > 0) & (udp_val > 0)],
        ["TCP_only", "UDP_only", "Both_TCP_UDP"],
        default="Neither_TCP_nor_UDP"
    )
    if "rst_count" not in d.columns:
        d["rst_count"] = d["RST"] if "RST" in d.columns else 0
    diagnostic_subsets.append(d)

protocol_diagnostic_df = pd.concat(diagnostic_subsets, ignore_index=True)

def add_group_percentage(result_df, group_columns, count_column="Records"):
    denominators = protocol_diagnostic_df.groupby(group_columns, dropna=False).size().rename("_group_total").reset_index()
    result_df = result_df.merge(denominators, on=group_columns, how="left")
    result_df["Percentage"] = result_df[count_column] / result_df["_group_total"] * 100
    return result_df.drop(columns="_group_total")

pattern_distribution = protocol_diagnostic_df.groupby(["dataset", "label", "Protocol_Pattern"], dropna=False).agg(
    Records=("label", "size"), Mean_XGB_Score=("xgb_score", "mean"), Flagged_Records=("prediction", "sum")
).reset_index()
pattern_distribution = add_group_percentage(pattern_distribution, ["dataset", "label"])

print("CORRECTED TCP / UDP PATTERN DISTRIBUTION (%)")
display(pattern_distribution.round(5))

pattern_distribution.to_csv(BASE_OUT / "WEAR_CHAIN_protocol_pattern_distribution.csv", index=False)
print("Section 13 completed.")

CORRECTED TCP / UDP PATTERN DISTRIBUTION (%)

,dataset,label,Protocol_Pattern,Records,Mean_XGB_Score,Flagged_Records,Percentage
0,Calibration,0,Both_TCP_UDP,11066,0.01434,137,28.70781
1,Calibration,0,Neither_TCP_nor_UDP,24,0.02383,0,0.06226
2,Calibration,0,TCP_only,26478,0.01186,166,68.69017
3,Calibration,0,UDP_only,979,0.06302,83,2.53976
4,Calibration,1,Both_TCP_UDP,77689,0.99540,77402,5.67044
5,Calibration,1,Neither_TCP_nor_UDP,273042,1.00000,273042,19.92905
6,Calibration,1,TCP_only,598709,0.99853,597895,43.69915
7,Calibration,1,UDP_only,420630,0.99991,420620,30.70135
8,Development,0,Both_TCP_UDP,44267,0.01118,384,28.71032
9,Development,0,Neither_TCP_nor_UDP,137,0.03655,4,0.08885
10,Development,0,TCP_only,105691,0.01010,391,68.54817
11,Development,0,UDP_only,4090,0.06731,362,2.65266
12,Development,1,Both_TCP_UDP,171263,0.99711,171119,3.98751
13,Development,1,Neither_TCP_nor_UDP,1038159,1.00000,1038158,24.17139
14,Development,1,TCP_only,1851585,0.99942,1850806,43.11033
15,Development,1,UDP_only,1233984,0.99978,1233947,28.73077
16,External,0,Both_TCP_UDP,10591,0.03081,334,28.16231
17,External,0,Neither_TCP_nor_UDP,38,0.01387,0,0.10105
18,External,0,TCP_only,23527,0.01085,100,62.56016
19,External,0,UDP_only,3451,0.23049,1189,9.17648
20,External,1,Both_TCP_UDP,479,0.83173,421,27.46560
21,External,1,TCP_only,308,0.64557,200,17.66055
22,External,1,UDP_only,957,0.95880,951,54.87385

Section 13 completed.

In [14]:
# ================================================================
# SECTION 14 — UDP-ONLY BENIGN SUBGROUP INVESTIGATION
# ================================================================
benign_udp = protocol_diagnostic_df[
    (protocol_diagnostic_df["label"] == 0) &
    (protocol_diagnostic_df["Protocol_Pattern"] == "UDP_only")
].copy()

benign_udp["Protocol17"] = np.isclose(
    pd.to_numeric(benign_udp["Protocol Type"], errors="coerce"), 17.0, atol=1e-6
)

subgroup_summary = benign_udp.groupby(["dataset", "Protocol17"]).agg(
    Records=("label", "size"),
    Mean_XGB_Score=("xgb_score", "mean"),
    Median_XGB_Score=("xgb_score", "median"),
    P95_XGB_Score=("xgb_score", lambda x: x.quantile(0.95)),
    P99_XGB_Score=("xgb_score", lambda x: x.quantile(0.99)),
    Flagged=("prediction", "sum")
).reset_index()
subgroup_summary["FPR"] = subgroup_summary["Flagged"] / subgroup_summary["Records"]

print("BENIGN UDP-ONLY: PROTOCOL TYPE 17 VS OTHER")
display(subgroup_summary.round(6))

subgroup_summary.to_csv(BASE_OUT / "WEAR_CHAIN_udp_benign_protocol17_summary.csv", index=False)
print("Section 14 completed.")

BENIGN UDP-ONLY: PROTOCOL TYPE 17 VS OTHER

,dataset,Protocol17,Records,Mean_XGB_Score,Median_XGB_Score,P95_XGB_Score,P99_XGB_Score,Flagged,FPR
0,Calibration,False,38,0.123034,0.000125,0.653305,0.750672,7,0.184211
1,Calibration,True,941,0.060593,0.000142,0.444206,0.660020,76,0.080765
2,Development,False,162,0.102525,0.000390,0.556779,0.670180,25,0.154321
3,Development,True,3928,0.065855,0.000951,0.437860,0.702497,337,0.085794
4,External,False,130,0.342265,0.001064,0.937735,0.959517,56,0.430769
5,External,True,3321,0.226116,0.000951,0.748722,0.770755,1133,0.341162

Section 14 completed.

In [15]:
# ================================================================
# SECTION 15 — EXTERNAL UDP FALSE-POSITIVE VS TRUE-NEGATIVE
# ================================================================
external_udp = protocol_diagnostic_df[
    (protocol_diagnostic_df["dataset"] == "External") &
    (protocol_diagnostic_df["label"] == 0) &
    (protocol_diagnostic_df["Protocol_Pattern"] == "UDP_only")
].copy()

external_udp["Prediction_Group"] = np.where(external_udp["prediction"] == 1, "False_Positive", "True_Negative")
fp_group = external_udp[external_udp["Prediction_Group"] == "False_Positive"].copy()
tn_group = external_udp[external_udp["Prediction_Group"] == "True_Negative"].copy()

print("External benign UDP-only records:", len(external_udp))
print("False positives:", len(fp_group), "| True negatives:", len(tn_group))

feature_results = []
rng = np.random.default_rng(42)

for feature in model_features:
    if feature not in external_udp.columns:
        continue
    fp_values = pd.to_numeric(fp_group[feature], errors="coerce").dropna()
    tn_values = pd.to_numeric(tn_group[feature], errors="coerce").dropna()
    if len(fp_values) == 0 or len(tn_values) == 0:
        continue

    pooled_std = np.sqrt(((len(fp_values)-1)*fp_values.std()**2 + (len(tn_values)-1)*tn_values.std()**2) / max(len(fp_values)+len(tn_values)-2, 1))
    smd = (fp_values.mean() - tn_values.mean()) / pooled_std if pooled_std > 0 else 0.0

    ks_stat, ks_p = ks_2samp(
        rng.choice(fp_values.to_numpy(), size=min(len(fp_values), 30000), replace=False),
        rng.choice(tn_values.to_numpy(), size=min(len(tn_values), 30000), replace=False)
    )

    feature_results.append({
        "Feature": feature,
        "FP_Mean": fp_values.mean(), "TN_Mean": tn_values.mean(),
        "Standardized_Mean_Difference": smd,
        "KS_Statistic": ks_stat, "KS_p_value": ks_p
    })

udp_fp_feature_comparison = pd.DataFrame(feature_results).sort_values("KS_Statistic", ascending=False).reset_index(drop=True)
print("\nTOP 20 FEATURES DISTINGUISHING EXTERNAL UDP FALSE POSITIVES")
display(udp_fp_feature_comparison.head(20).round(6))

udp_fp_feature_comparison.to_csv(BASE_OUT / "WEAR_CHAIN_external_udp_fp_feature_comparison.csv", index=False)
print("Section 15 completed.")

External benign UDP-only records: 3451
False positives: 1189 | True negatives: 2262

TOP 20 FEATURES DISTINGUISHING EXTERNAL UDP FALSE POSITIVES

,Feature,FP_Mean,TN_Mean,Standardized_Mean_Difference,KS_Statistic,KS_p_value
0,Tot sum,5.808322e+02,4.705897e+03,-0.819269,0.893047,0.000000
1,IAT,1.866500e-02,1.291634e+08,-2.210435,0.763128,0.000000
2,Number,5.492851e+00,1.159240e+01,-2.206423,0.761715,0.000000
3,Weight,3.843818e+01,1.954758e+02,-2.207572,0.761715,0.000000
4,Variance,8.666110e-01,7.358970e-01,0.376415,0.642352,0.000000
5,Max,1.275839e+02,4.902328e+02,-0.856038,0.566863,0.000000
6,Min,9.922103e+01,3.922927e+02,-0.695022,0.374038,0.000000
7,AVG,1.056899e+02,4.239923e+02,-0.754839,0.343739,0.000000
8,Magnitue,1.447538e+01,2.430646e+01,-0.756901,0.343739,0.000000
9,Tot size,1.061103e+02,4.298246e+02,-0.762689,0.312038,0.000000
10,Duration,6.384104e+01,6.282007e+01,0.157624,0.284682,0.000000
11,Std,1.000626e+01,2.875643e+01,-0.288369,0.267495,0.000000
12,Radius,1.415099e+01,4.063878e+01,-0.287781,0.266654,0.000000
13,Rate,5.292411e+01,3.980042e+02,-0.119957,0.263926,0.000000
14,Srate,5.292411e+01,3.980042e+02,-0.119957,0.263926,0.000000
15,Covariance,1.774835e+03,7.368464e+03,-0.194090,0.246285,0.000000
16,Header_Length,2.030059e+06,1.879623e+06,0.117966,0.165664,0.000000
17,ARP,1.354100e-02,9.947000e-03,0.048680,0.015268,0.991841
18,IPv,9.864590e-01,9.900530e-01,-0.048680,0.015268,0.991841
19,Protocol Type,1.676981e+01,1.682692e+01,-0.045269,0.015268,0.991841

Section 15 completed.

In [16]:
# ================================================================
# SECTION 16 — XGBOOST PREDICTION CONTRIBUTION ANALYSIS
# ================================================================
import xgboost as xgb

X_udp = external_udp[model_features].copy()
booster = xgb_model.get_booster()
dmatrix = xgb.DMatrix(X_udp, feature_names=model_features)

contribution_matrix = booster.predict(dmatrix, pred_contribs=True)
contribution_columns = model_features + ["BIAS"]

contribution_df = pd.DataFrame(contribution_matrix, columns=contribution_columns, index=external_udp.index)
contribution_df["Prediction_Group"] = external_udp["Prediction_Group"].to_numpy()

feature_contributions = []
for feature in model_features:
    fp_vals = contribution_df.loc[contribution_df["Prediction_Group"] == "False_Positive", feature]
    tn_vals = contribution_df.loc[contribution_df["Prediction_Group"] == "True_Negative", feature]

    feature_contributions.append({
        "Feature": feature,
        "FP_Mean_Signed_Contribution": fp_vals.mean(),
        "TN_Mean_Signed_Contribution": tn_vals.mean(),
        "Difference_FP_minus_TN": fp_vals.mean() - tn_vals.mean(),
        "Absolute_Group_Difference": abs(fp_vals.mean() - tn_vals.mean())
    })

contribution_comparison = pd.DataFrame(feature_contributions).sort_values("Absolute_Group_Difference", ascending=False).reset_index(drop=True)

print("TOP FEATURES BY DIFFERENCE IN SIGNED CONTRIBUTION")
display(contribution_comparison.head(20).round(6))

contribution_comparison.to_csv(BASE_OUT / "WEAR_CHAIN_udp_xgb_contribution_comparison.csv", index=False)
contribution_df.to_csv(BASE_OUT / "WEAR_CHAIN_udp_xgb_record_contributions.csv", index=False)
print("Section 16 completed.")

TOP FEATURES BY DIFFERENCE IN SIGNED CONTRIBUTION

,Feature,FP_Mean_Signed_Contribution,TN_Mean_Signed_Contribution,Difference_FP_minus_TN,Absolute_Group_Difference
0,IAT,0.149021,-8.189182,8.338202,8.338202
1,Number,-1.191837,-0.019859,-1.171978,1.171978
2,Duration,0.174971,-0.381989,0.556961,0.556961
3,Rate,0.795200,0.357019,0.438181,0.438181
4,Header_Length,0.560333,0.189266,0.371067,0.371067
5,Weight,-0.375231,-0.058082,-0.317150,0.317150
6,rst_count,1.462940,1.159192,0.303748,0.303748
7,fin_count,-0.511455,-0.233943,-0.277512,0.277512
8,Tot sum,-0.217500,0.001631,-0.219131,0.219131
9,Protocol Type,-0.421746,-0.219387,-0.202359,0.202359
10,Magnitue,-2.846202,-2.695494,-0.150707,0.150707
11,Tot size,-0.215400,-0.346634,0.131235,0.131235
12,Srate,0.223619,0.096354,0.127264,0.127264
13,ack_flag_number,0.141712,0.022291,0.119421,0.119421
14,Max,0.054721,-0.053535,0.108256,0.108256
15,AVG,-0.049382,-0.130476,0.081094,0.081094
16,Radius,-0.097299,-0.038352,-0.058946,0.058946
17,psh_flag_number,-0.129471,-0.073725,-0.055746,0.055746
18,TCP,-0.374386,-0.323446,-0.050940,0.050940
19,Variance,-0.015331,-0.063722,0.048392,0.048392

Section 16 completed.

In [17]:
# ================================================================
# SECTION 17 — CONSOLIDATED DATA INTEGRITY & ALIGNMENT AUDIT
# ================================================================
reference_totals = split_df["partition"].value_counts()
partition_results = []

for name, active_df in [("development", development_df), ("calibration", calibration_df)]:
    expected = int(reference_totals.get(name, 0))
    actual = len(active_df)
    partition_results.append({
        "Partition": name,
        "Reference_Rows": expected,
        "Active_Rows": actual,
        "Difference": actual - expected,
        "Status": "PASS" if actual == expected else "MISMATCH"
    })

partition_audit = pd.DataFrame(partition_results)
display(partition_audit)

partition_audit.to_csv(BASE_OUT / "WEAR_CHAIN_section17_partition_audit.csv", index=False)
print("Section 17 completed.")

     Partition  Reference_Rows  Active_Rows  Difference Status
0  development         4449176      4449176           0   PASS
1  calibration         1408617      1408617           0   PASS

Section 17 completed.

In [18]:
# ================================================================
# SECTION 17A & 17B — RECONCILIATION AND TEST METRIC RECONSTRUCTION
# ================================================================
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score, confusion_matrix

predictions = pd.read_csv(BASE_OUT / "WEAR_CHAIN_unseen_test_predictions.csv")

model_cols_map = {
    "XGBoost": ("XGBoost_prediction", "xgb_score"),
    "Autoencoder": ("Autoencoder_prediction", "ae_score"),
    "Hybrid_Max": ("Hybrid_Max_prediction", "hybrid_max_score"),
    "Hybrid_Average": ("Hybrid_Average_prediction", "hybrid_average_score")
}

def calculate_metrics_17b(frame, model_name, pred_col, score_col):
    actual = frame["label"].astype(int).to_numpy()
    predicted = frame[pred_col].astype(int).to_numpy()
    scores = pd.to_numeric(frame[score_col], errors="coerce").to_numpy()

    tn, fp, fn, tp = confusion_matrix(actual, predicted, labels=[0, 1]).ravel()
    return {
        "model": model_name, "records": len(frame),
        "accuracy": accuracy_score(actual, predicted),
        "precision": precision_score(actual, predicted, zero_division=0),
        "recall": recall_score(actual, predicted, zero_division=0),
        "f1": f1_score(actual, predicted, zero_division=0),
        "FPR": fp / (fp + tn) if (fp + tn) else np.nan,
        "FNR": fn / (fn + tp) if (fn + tp) else np.nan,
        "TN": tn, "FP": fp, "FN": fn, "TP": tp
    }

metric_rows = []
for model_name, (pred_col, score_col) in model_cols_map.items():
    row = calculate_metrics_17b(predictions, model_name, pred_col, score_col)
    metric_rows.append(row)

reconstructed_metrics_df = pd.DataFrame(metric_rows)
print("RECONSTRUCTED OVERALL TEST METRICS")
display(reconstructed_metrics_df.round(6))

reconstructed_metrics_df.to_csv(BASE_OUT / "WEAR_CHAIN_17B_reconstructed_test_metrics.csv", index=False)
print("Section 17B completed.")

RECONSTRUCTED OVERALL TEST METRICS

,model,records,accuracy,precision,recall,f1,FPR,FNR,TN,FP,FN,TP
0,XGBoost,1342385,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,35984,1623,1086,1303692
1,Autoencoder,1342385,0.993337,0.999123,0.994018,0.996564,0.030287,0.005982,36468,1139,7805,1296973
2,Hybrid_Max,1342385,0.997937,0.998984,0.998894,0.998939,0.035259,0.001106,36281,1326,1443,1303335
3,Hybrid_Average,1342385,0.995556,0.998835,0.996589,0.997711,0.040312,0.003411,36091,1516,4450,1300328

Section 17B completed.

In [19]:
# ================================================================
# SECTION 17C — RAW TRAINING FILE INVENTORY AND CHECKSUM RECONCILIATION
# ================================================================
import hashlib

def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()

raw_paths = sorted(
    p for p in glob.glob(f"{DATA_DIR}/*train*.csv")
    if "WEAR_CHAIN" not in os.path.basename(p)
)

print(f"Scanning {len(raw_paths)} raw training files in {DATA_DIR}...")
raw_records = []
for path in raw_paths:
    filename = os.path.basename(path)
    raw_records.append({
        "source_file": filename,
        "file_size_MB": round(os.path.getsize(path) / (1024 ** 2), 3),
        "sha256": sha256_file(path)
    })

raw_audit_df = pd.DataFrame(raw_records)
display(raw_audit_df.head(10))

raw_audit_df.to_csv(BASE_OUT / "WEAR_CHAIN_17C_raw_file_inventory.csv", index=False)
print("Section 17C completed.")

Scanning 51 raw training files in /kaggle/input/datasets/gopikrisha/custommade...

,source_file,file_size_MB,sha256
0,ARP_Spoofing_train.pcap.csv,4.608,f0d68653cfe5873f280a0cd84323145d6112861819204b...
1,Benign_train.pcap.csv,56.699,5337565793ff0460270da0b848e2ca8eafbd529a9715ce...
2,MQTT-DDoS-Connect_Flood_train.pcap.csv,52.414,0739bf1a52f7e6accaba1252e3a7393c476f87122c663b...
3,MQTT-DDoS-Publish_Flood_train.pcap.csv,8.568,45f73cd42af9bd71e890ea77e52316ed1a3e90351e4041...
4,MQTT-DoS-Connect_Flood_train.pcap.csv,3.873,93093507c84ef2d71ae9b6fad4669d145e2601d981b6b4...
5,MQTT-DoS-Publish_Flood_train.pcap.csv,13.445,f5cc6b18ddb55febb2f3132c8bb3e4471277bf2fb6f6a8...
6,MQTT-Malformed_Data_train.pcap.csv,1.459,292efe2f8b07203c53c65f7d5c5af05bcc4429cd06701a...
7,Recon-OS_Scan_train.pcap.csv,4.321,c8450cd6a2808243b66fe9308d49d9e3e1b88802c7debb...
8,Recon-Ping_Sweep_train.pcap.csv,0.201,aa2fce831dc4c73c7d6138eca415bb2966870599d0ca7e...
9,Recon-Port_Scan_train.pcap.csv,21.538,7dc0785d3e69d4e1a083582dad0efc4c94c35bbc75e56e...

Section 17C completed.

In [20]:
# ================================================================
# SECTIONS 18 & 19 — RECOVERY AND MODEL ALIGNMENT AUDIT
# ================================================================

required_artifacts = [
    "WEAR_CHAIN_partitioned_dataset.csv",
    "WEAR_CHAIN_capture_assignments.csv",
    "WEAR_CHAIN_unseen_test_predictions.csv",
    "WEAR_CHAIN_XGBoost_baseline.pkl",
    "WEAR_CHAIN_autoencoder.keras",
    "WEAR_CHAIN_autoencoder_scaler.pkl"
]

recovery_report = []
for name in required_artifacts:
    target = BASE_OUT / name
    recovery_report.append({
        "file": name,
        "exists": target.exists(),
        "size_MB": round(target.stat().st_size / (1024 ** 2), 3) if target.exists() else 0.0
    })

recovery_df = pd.DataFrame(recovery_report)
print("SECTION 18/19 ARTIFACT ALIGNMENT AUDIT")
display(recovery_df)

recovery_df.to_csv(BASE_OUT / "WEAR_CHAIN_18_recovery_inventory.csv", index=False)
print("Sections 18 and 19 completed.")

SECTION 18/19 ARTIFACT ALIGNMENT AUDIT

                                     file  exists   size_MB
0      WEAR_CHAIN_partitioned_dataset.csv    True  2172.394
1      WEAR_CHAIN_capture_assignments.csv    True     0.003
2  WEAR_CHAIN_unseen_test_predictions.csv    True   164.874
3         WEAR_CHAIN_XGBoost_baseline.pkl    True     0.884
4            WEAR_CHAIN_autoencoder.keras    True     0.090
5       WEAR_CHAIN_autoencoder_scaler.pkl    True     0.002

Sections 18 and 19 completed.

In [21]:
# ============================================================
# WEAR-CHAIN | SECTION 20 — ADAPTIVE TRUST SIMULATION
# ============================================================
from itertools import product

ALERT_THRESHOLD = 0.50

cal = pd.read_csv(BASE_OUT / "WEAR_CHAIN_XGBoost_calibration_predictions.csv")
test = pd.read_csv(BASE_OUT / "WEAR_CHAIN_unseen_test_predictions.csv")

def replay_trust(df, score_col, decay, recovery, block_threshold):
    results = []
    for source, group in df.groupby("source_file", sort=False):
        trust = 1.0
        for score, label in zip(group[score_col].to_numpy(), group["label"].to_numpy()):
            detector_flag = score >= XGB_THRESHOLD
            trust = max(0.0, trust - decay) if detector_flag else min(1.0, trust + recovery)

            if trust <= block_threshold:
                state = "BLOCK"
            elif trust <= ALERT_THRESHOLD:
                state = "ALERT"
            elif detector_flag:
                state = "MONITOR"
            else:
                state = "SAFE"

            results.append((source, int(label), float(score), float(trust), int(detector_flag), state))

    return pd.DataFrame(results, columns=["source_file", "label", "score", "trust_score", "detector_flag", "trust_state"])

# Grid search on calibration data
parameter_grid = list(product([0.02, 0.05, 0.10], [0.02, 0.05], [0.10, 0.20, 0.30]))
calibration_results = []

for decay, recovery, block_thresh in parameter_grid:
    replay = replay_trust(cal, "attack_probability", decay, recovery, block_thresh)
    benign = replay[replay["label"] == 0]
    attack = replay[replay["label"] == 1]
    benign_block_rate = (benign["trust_state"] == "BLOCK").mean()
    attack_block_rate = (attack["trust_state"] == "BLOCK").mean()

    calibration_results.append({
        "decay": decay, "recovery": recovery, "block_threshold": block_thresh,
        "benign_block_rate": benign_block_rate, "attack_block_rate": attack_block_rate,
        "feasible": benign_block_rate <= 0.01
    })

grid_df = pd.DataFrame(calibration_results)
selected = grid_df[grid_df["feasible"]].sort_values(by=["attack_block_rate", "benign_block_rate"], ascending=[False, True]).iloc[0]

DECAY = float(selected["decay"])
RECOVERY = float(selected["recovery"])
BLOCK_THRESHOLD = float(selected["block_threshold"])

print(f"Selected Trust Configuration: Decay={DECAY}, Recovery={RECOVERY}, Block Threshold={BLOCK_THRESHOLD}")

test_replay = replay_trust(test, "xgb_score", DECAY, RECOVERY, BLOCK_THRESHOLD)
test_replay["test_source"] = test["test_source"].to_numpy()
test_replay.to_csv(BASE_OUT / "WEAR_CHAIN_20_trust_test_predictions.csv", index=False)
print("Section 20 completed.")

Selected Trust Configuration: Decay=0.1, Recovery=0.02, Block Threshold=0.3
Section 20 completed.

In [22]:
# ============================================================
# SECTION 21 & 22 — SHA-256 HASH-LINKED AUDIT LEDGER
# ============================================================
import json

INPUT_FILE = BASE_OUT / "WEAR_CHAIN_20_trust_test_predictions.csv"
BLOCK_SIZE = 1000
GENESIS_HASH = "WEAR_CHAIN_GENESIS_BLOCK"

df = pd.read_csv(INPUT_FILE)
events = df[["source_file", "test_source", "score", "trust_score", "detector_flag", "trust_state"]].copy()
events["sequence_id"] = range(1, len(events) + 1)

def canonical_json(record):
    return json.dumps(record, sort_keys=True, separators=(",", ":"), ensure_ascii=False)

def sha256_text(value):
    return hashlib.sha256(value.encode("utf-8")).hexdigest()

events["event_hash"] = [
    sha256_text(canonical_json({
        "sequence_id": int(r.sequence_id), "source_file": str(r.source_file),
        "test_source": str(r.test_source), "score": float(r.score),
        "trust_score": float(r.trust_score), "detector_flag": int(r.detector_flag),
        "trust_state": str(r.trust_state)
    })) for r in events.itertuples(index=False)
]

def calculate_merkle_root(hashes):
    if not hashes: return sha256_text("EMPTY_BLOCK")
    level = list(hashes)
    while len(level) > 1:
        if len(level) % 2 == 1: level.append(level[-1])
        level = [sha256_text(level[i] + level[i + 1]) for i in range(0, len(level), 2)]
    return level[0]

block_records = []
previous_hash = GENESIS_HASH
event_hashes_list = events["event_hash"].tolist()

for block_number, start in enumerate(range(0, len(events), BLOCK_SIZE), start=1):
    end = min(start + BLOCK_SIZE, len(events))
    merkle_root = calculate_merkle_root(event_hashes_list[start:end])

    block_payload = {
        "block_number": block_number,
        "start_sequence": start + 1,
        "end_sequence": end,
        "event_count": end - start,
        "merkle_root": merkle_root,
        "previous_block_hash": previous_hash
    }
    block_hash = sha256_text(canonical_json(block_payload))
    block_records.append({**block_payload, "block_hash": block_hash})
    previous_hash = block_hash

blocks = pd.DataFrame(block_records)

events.to_csv(BASE_OUT / "WEAR_CHAIN_21_audit_events.csv", index=False)
blocks.to_csv(BASE_OUT / "WEAR_CHAIN_21_blockchain_manifest.csv", index=False)
print("Section 21 completed. Blockchain ledger saved.")

Section 21 completed. Blockchain ledger saved.

In [23]:
# ============================================================
# FINAL ARTIFACT AND OUTPUT VERIFICATION
# ============================================================

generated_files = list(BASE_OUT.glob("*.csv")) + list(BASE_OUT.glob("*.pkl")) + list(BASE_OUT.glob("*.keras"))

print(f"Total artifacts generated in {BASE_OUT}: {len(generated_files)}\n")
for f in sorted(generated_files):
    size_mb = f.stat().st_size / (1024 ** 2)
    print(f"{f.name:50s} | {size_mb:8.3f} MB")

Total artifacts generated in /kaggle/working: 35

WEAR_CHAIN_17B_reconstructed_test_metrics.csv      |    0.001 MB
WEAR_CHAIN_17C_raw_file_inventory.csv              |    0.005 MB
WEAR_CHAIN_18_recovery_inventory.csv               |    0.000 MB
WEAR_CHAIN_20_trust_test_predictions.csv           |   83.280 MB
WEAR_CHAIN_21_audit_events.csv                     |  173.109 MB
WEAR_CHAIN_21_blockchain_manifest.csv              |    0.280 MB
WEAR_CHAIN_IAT_descriptive_statistics.csv          |    0.000 MB
WEAR_CHAIN_XGBoost_baseline.pkl                    |    0.884 MB
WEAR_CHAIN_XGBoost_calibration_predictions.csv     |   76.720 MB
WEAR_CHAIN_XGBoost_feature_importance.csv          |    0.001 MB
WEAR_CHAIN_autoencoder.keras                       |    0.090 MB
WEAR_CHAIN_autoencoder_calibration_scores.csv      |   76.939 MB
WEAR_CHAIN_autoencoder_scaler.pkl                  |    0.002 MB
WEAR_CHAIN_capture_assignments.csv                 |    0.003 MB
WEAR_CHAIN_correlations.csv                        |    0.052 MB
WEAR_CHAIN_external_FP_feature_comparison.csv      |    0.005 MB
WEAR_CHAIN_external_FP_importance_analysis.csv     |    0.006 MB
WEAR_CHAIN_external_test_audit.csv                 |    0.000 MB
WEAR_CHAIN_external_test_dataset.csv               |   13.054 MB
WEAR_CHAIN_external_udp_fp_feature_comparison.csv  |    0.003 MB
WEAR_CHAIN_family_medians.csv                      |    0.001 MB
WEAR_CHAIN_feature_distribution_drift.csv          |    0.005 MB
WEAR_CHAIN_feature_drift_importance_combined.csv   |    0.006 MB
WEAR_CHAIN_feature_quality.csv                     |    0.002 MB
WEAR_CHAIN_hybrid_calibration_scores.csv           |  106.454 MB
WEAR_CHAIN_partition_summary.csv                   |    0.000 MB
WEAR_CHAIN_partitioned_dataset.csv                 | 2172.394 MB
WEAR_CHAIN_protocol_pattern_distribution.csv       |    0.002 MB
WEAR_CHAIN_score_distribution_summary.csv          |    0.001 MB
WEAR_CHAIN_section17_partition_audit.csv           |    0.000 MB
WEAR_CHAIN_udp_benign_protocol17_summary.csv       |    0.001 MB
WEAR_CHAIN_udp_xgb_contribution_comparison.csv     |    0.002 MB
WEAR_CHAIN_udp_xgb_record_contributions.csv        |    1.660 MB
WEAR_CHAIN_unseen_test_predictions.csv             |  164.874 MB
ciciomt_capture_inventory.csv                      |    0.003 MB

In [24]:
# ================================================================
# WEAR-CHAIN — FINAL PAPER VALUE AUDIT
# ================================================================
# PURPOSE:
#   1. Load ONLY frozen result artifacts
#   2. Recalculate/check important paper metrics
#   3. Verify population and confusion-matrix consistency
#   4. Print the final values that can be used in the paper
#   5. Save one consolidated paper-results CSV
#
# IMPORTANT:
#   - NO model retraining
#   - NO threshold modification
#   - NO prediction modification
#   - NO dataset modification
# ================================================================

import os
import numpy as np
import pandas as pd

BASE = "/"

print("=" * 90)
print("WEAR-CHAIN — FINAL PAPER VALUE AUDIT")
print("=" * 90)


# ---------------------------------------------------------------
# 1. REQUIRED FINAL ARTIFACTS
# ---------------------------------------------------------------

required_files = {
    "E6_overall":
        "WEAR_CHAIN_E6_overall_metrics.csv",

    "E6_family":
        "WEAR_CHAIN_E6_attack_family_metrics.csv",

    "E6_macro":
        "WEAR_CHAIN_E6_family_macro_summary.csv",

    "E6_capture_family":
        "WEAR_CHAIN_E6_capture_family_recall.csv",

    "E7_aggregate":
        "WEAR_CHAIN_E7_aggregate_metrics.csv",

    "E7_fold":
        "WEAR_CHAIN_E7_fold_metrics.csv",

    "E8_benchmark":
        "WEAR_CHAIN_E8_inference_benchmark.csv",

    "E8_model_size":
        "WEAR_CHAIN_E8_model_sizes.csv",

    "E8_resource":
        "WEAR_CHAIN_E8_resource_summary.csv",

    "E20_trust":
        "WEAR_CHAIN_20_trust_test_predictions.csv",

    "E21_events":
        "WEAR_CHAIN_21_audit_events.csv",

    "E21_manifest":
        "WEAR_CHAIN_21_blockchain_manifest.csv",

    "E21_integrity":
        "WEAR_CHAIN_21_ledger_integrity_report.csv",

    "E22":
        "WEAR_CHAIN_22_performance_results.csv",

    "E17B":
        "WEAR_CHAIN_17B_reconstructed_test_metrics.csv",

    "E17B_family":
        "WEAR_CHAIN_17B_reconstructed_family_recall.csv",

    "predictions":
        "WEAR_CHAIN_unseen_test_predictions.csv",
}


print("\n[1] CHECKING REQUIRED ARTIFACTS")
print("-" * 90)

missing = []

for name, filename in required_files.items():

    path = os.path.join(BASE, filename)

    if os.path.exists(path):
        size_mb = os.path.getsize(path) / (1024 ** 2)
        print(f"[FOUND] {filename:<55} {size_mb:8.3f} MB")
    else:
        print(f"[MISSING] {filename}")
        missing.append(filename)

if missing:
    print("\nWARNING: Some artifacts are missing.")
    print("The audit will continue with whatever is available.")


# ---------------------------------------------------------------
# 2. LOAD FINAL CSVs
# ---------------------------------------------------------------

def load_csv(key):
    path = os.path.join(BASE, required_files[key])

    if not os.path.exists(path):
        return None

    return pd.read_csv(path)


e6 = load_csv("E6_overall")
e6_family = load_csv("E6_family")
e6_macro = load_csv("E6_macro")

e7 = load_csv("E7_aggregate")
e7_fold = load_csv("E7_fold")

e8_bench = load_csv("E8_benchmark")
e8_size = load_csv("E8_model_size")
e8_resource = load_csv("E8_resource")

e20 = load_csv("E20_trust")

e21_events = load_csv("E21_events")
e21_manifest = load_csv("E21_manifest")
e21_integrity = load_csv("E21_integrity")

e22 = load_csv("E22")

e17b = load_csv("E17B")
e17b_family = load_csv("E17B_family")

predictions = load_csv("predictions")


# ---------------------------------------------------------------
# 3. HELPER FUNCTIONS
# ---------------------------------------------------------------

paper_results = []
audit_results = []


def add_result(section, metric, value, source, status="PASS"):
    paper_results.append({
        "section": section,
        "metric": metric,
        "value": value,
        "source": source
    })

    audit_results.append({
        "section": section,
        "metric": metric,
        "value": value,
        "status": status,
        "source": source
    })


def fmt(x, digits=6):

    if isinstance(x, (float, np.floating)):
        return f"{x:.{digits}f}"

    return str(x)


def get_row(df, column, value):

    if df is None:
        return None

    if column not in df.columns:
        return None

    rows = df[df[column].astype(str) == str(value)]

    if len(rows) == 0:
        return None

    return rows.iloc[0]


# ---------------------------------------------------------------
# 4. E6 — FINAL OVERALL DETECTION RESULTS
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E6 — FINAL ATTACK/CAPTURE EVALUATION")
print("=" * 90)

if e6 is not None:

    print("\nFinal overall metrics:\n")

    display(e6.round(6))

    for _, r in e6.iterrows():

        model = r["model"]

        print(
            f"{model:18s} | "
            f"Precision={r['precision']:.6f} | "
            f"Recall={r['recall']:.6f} | "
            f"F1={r['F1']:.6f} | "
            f"FPR={r['FPR']:.6f}"
        )

        add_result(
            "E6",
            f"{model} Precision",
            r["precision"],
            "WEAR_CHAIN_E6_overall_metrics.csv"
        )

        add_result(
            "E6",
            f"{model} Recall",
            r["recall"],
            "WEAR_CHAIN_E6_overall_metrics.csv"
        )

        add_result(
            "E6",
            f"{model} F1",
            r["F1"],
            "WEAR_CHAIN_E6_overall_metrics.csv"
        )

        add_result(
            "E6",
            f"{model} FPR",
            r["FPR"],
            "WEAR_CHAIN_E6_overall_metrics.csv"
        )


# ---------------------------------------------------------------
# 5. INDEPENDENT CONFUSION-MATRIX CHECK
# ---------------------------------------------------------------

print("\n" + "-" * 90)
print("E6 — CONFUSION MATRIX CONSISTENCY CHECK")
print("-" * 90)

if e6 is not None:

    for _, r in e6.iterrows():

        model = r["model"]

        TN = int(r["TN"])
        FP = int(r["FP"])
        FN = int(r["FN"])
        TP = int(r["TP"])

        calculated_total = TN + FP + FN + TP

        expected_total = int(r["records"])

        status = calculated_total == expected_total

        print(
            f"{model:18s} | "
            f"TN={TN:,} FP={FP:,} FN={FN:,} TP={TP:,} | "
            f"Total={calculated_total:,} | "
            f"Expected={expected_total:,} | "
            f"{'PASS' if status else 'FAIL'}"
        )

        add_result(
            "E6 Audit",
            f"{model} confusion-total consistency",
            calculated_total,
            "E6 confusion matrix",
            "PASS" if status else "FAIL"
        )


# ---------------------------------------------------------------
# 6. E6 — ATTACK FAMILY RECALL
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E6 — ATTACK FAMILY RECALL")
print("=" * 90)

if e6_family is not None:

    display(e6_family.round(6))

    print("\nFinal family recall values:\n")

    # Try common column naming
    family_col = None

    for c in ["attack_family", "family", "Attack_Family"]:
        if c in e6_family.columns:
            family_col = c
            break

    if family_col is not None:

        print(e6_family.to_string(index=False))

    else:

        print("Family column could not be automatically identified.")


# ---------------------------------------------------------------
# 7. E6 — MACRO FAMILY RECALL
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E6 — MACRO FAMILY RECALL")
print("=" * 90)

if e6_macro is not None:

    display(e6_macro.round(6))

    for _, r in e6_macro.iterrows():

        model = r["model"]

        value = r["macro_family_recall"]

        print(
            f"{model:18s} | "
            f"Macro-family recall = {value:.6f}"
        )

        add_result(
            "E6",
            f"{model} Macro Family Recall",
            value,
            "WEAR_CHAIN_E6_family_macro_summary.csv"
        )


# ---------------------------------------------------------------
# 8. E17B — FROZEN RECONSTRUCTED TEST RESULTS
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E17B — RECONSTRUCTED FINAL TEST METRICS")
print("=" * 90)

if e17b is not None:

    display(e17b.round(6))

    if "records" in e17b.columns:

        populations = e17b["records"].unique()

        print("\nUnique reported test populations:", populations)

        if len(populations) == 1:

            total = int(populations[0])

            add_result(
                "E17B",
                "Final test population",
                total,
                "WEAR_CHAIN_17B_reconstructed_test_metrics.csv"
            )


# ---------------------------------------------------------------
# 9. TEST POPULATION CROSS-CHECK
# ---------------------------------------------------------------

print("\n" + "-" * 90)
print("CROSS-EXPERIMENT TEST POPULATION CHECK")
print("-" * 90)

population_values = {}

if predictions is not None:
    population_values["prediction_file"] = len(predictions)

if e6 is not None and "records" in e6.columns:
    population_values["E6"] = int(e6["records"].iloc[0])

if e17b is not None and "records" in e17b.columns:
    population_values["E17B"] = int(e17b["records"].iloc[0])

if e20 is not None:
    population_values["E20"] = len(e20)

for name, value in population_values.items():
    print(f"{name:20s}: {value:,}")

if len(set(population_values.values())) == 1:

    print("\nPASS — All final test populations agree.")

    add_result(
        "Cross-check",
        "Final test population agreement",
        list(population_values.values())[0],
        "E6/E17B/E20/predictions",
        "PASS"
    )

else:

    print("\nREVIEW — Test populations do not all agree.")

    add_result(
        "Cross-check",
        "Final test population agreement",
        str(population_values),
        "E6/E17B/E20/predictions",
        "REVIEW"
    )


# ---------------------------------------------------------------
# 10. E7 — UNSEEN ATTACK / LEAVE-ONE-FAMILY-OUT
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E7 — LEAVE-ONE-ATTACK-FAMILY-OUT GENERALIZATION")
print("=" * 90)

if e7 is not None:

    display(e7.round(6))

    for _, r in e7.iterrows():

        model = r["model"]

        print(
            f"{model:18s} | "
            f"Precision={r['mean_precision']:.6f} | "
            f"Recall={r['mean_recall']:.6f} | "
            f"F1={r['mean_f1']:.6f} | "
            f"FPR={r['mean_fpr']:.6f} | "
            f"ROC-AUC={r['mean_roc_auc']:.6f} | "
            f"PR-AUC={r['mean_pr_auc']:.6f}"
        )


# ---------------------------------------------------------------
# 11. E8 — RESOURCE / INFERENCE RESULTS
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E8 — RESOURCE AND INFERENCE BENCHMARK")
print("=" * 90)

if e8_bench is not None:

    print("\nInference benchmark:")
    display(e8_bench.round(6))

if e8_size is not None:

    print("\nModel sizes:")
    display(e8_size.round(6))

if e8_resource is not None:

    print("\nResource summary:")
    display(e8_resource.round(6))


# ---------------------------------------------------------------
# 12. E20 — TRUST EVALUATION
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E20 — ADAPTIVE TRUST EVALUATION")
print("=" * 90)

if e20 is not None:

    print(f"Trust prediction rows: {len(e20):,}")

    add_result(
        "E20",
        "Trust prediction population",
        len(e20),
        "WEAR_CHAIN_20_trust_test_predictions.csv"
    )

    # Print available trust-state columns
    trust_cols = [
        c for c in e20.columns
        if any(k in c.lower() for k in
               ["trust", "block", "alert", "decision", "risk"])
    ]

    if trust_cols:

        print("\nTrust-related columns:")
        print(trust_cols)

        display(e20[trust_cols].head(20))


# ---------------------------------------------------------------
# 13. E21/E22 — BLOCKCHAIN AUDIT
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("E21/E22 — BLOCKCHAIN / LEDGER AUDIT")
print("=" * 90)

if e22 is not None:

    print("\nFinal blockchain performance result:")
    display(e22)

    r = e22.iloc[0]

    blockchain_metrics = [
        "event_count",
        "block_count",
        "block_size",
        "plain_log_size_MB",
        "ledger_event_file_size_MB",
        "block_manifest_size_MB",
        "ledger_total_size_MB",
        "storage_overhead_percent",
        "plain_log_write_seconds",
        "event_hash_generation_seconds",
        "hashing_events_per_second",
        "full_ledger_verification_seconds",
        "event_hashes_valid",
        "merkle_roots_valid",
        "block_hashes_valid",
        "chain_links_valid",
        "plain_log_tamper_detected",
        "ledger_tamper_detected",
    ]

    print("\nPaper-ready blockchain values:\n")

    for c in blockchain_metrics:

        if c in r.index:

            print(f"{c:40s}: {r[c]}")

            add_result(
                "E21/E22",
                c,
                r[c],
                "WEAR_CHAIN_22_performance_results.csv"
            )


# ---------------------------------------------------------------
# 14. BLOCKCHAIN INTEGRITY CHECK
# ---------------------------------------------------------------

print("\n" + "-" * 90)
print("BLOCKCHAIN INTEGRITY CHECK")
print("-" * 90)

if e22 is not None:

    r = e22.iloc[0]

    checks = {
        "Event hashes valid": bool(r["event_hashes_valid"]),
        "Merkle roots valid": bool(r["merkle_roots_valid"]),
        "Block hashes valid": bool(r["block_hashes_valid"]),
        "Chain links valid": bool(r["chain_links_valid"]),
        "Controlled ledger tampering detected":
            bool(r["ledger_tamper_detected"]),
    }

    for name, value in checks.items():

        print(
            f"{name:45s}: "
            f"{'PASS' if value else 'FAIL'}"
        )


# ---------------------------------------------------------------
# 15. FINAL NUMERICAL AUDIT
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("FINAL NUMERICAL AUDIT")
print("=" * 90)

audit_df = pd.DataFrame(audit_results)

if len(audit_df):

    print("\nStatus counts:")

    print(
        audit_df["status"]
        .value_counts()
        .to_string()
    )

    display(audit_df)


# ---------------------------------------------------------------
# 16. SAVE CONSOLIDATED PAPER VALUES
# ---------------------------------------------------------------

paper_df = pd.DataFrame(paper_results)

paper_path = os.path.join(
    BASE,
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv"
)

audit_path = os.path.join(
    BASE,
    "WEAR_CHAIN_FINAL_PAPER_VALUE_AUDIT.csv"
)

paper_df.to_csv(
    paper_path,
    index=False
)

audit_df.to_csv(
    audit_path,
    index=False
)


# ---------------------------------------------------------------
# 17. FINAL SUMMARY
# ---------------------------------------------------------------

print("\n" + "=" * 90)
print("FINAL SUMMARY")
print("=" * 90)

print(f"\nPaper values saved to:")
print(paper_path)

print(f"\nAudit saved to:")
print(audit_path)

if len(audit_df):

    failed = audit_df[
        audit_df["status"] == "FAIL"
    ]

    review = audit_df[
        audit_df["status"] == "REVIEW"
    ]

    print(f"\nFAIL items   : {len(failed)}")
    print(f"REVIEW items : {len(review)}")

    if len(failed) == 0 and len(review) == 0:

        print("\n✅ FINAL PAPER VALUE AUDIT: PASS")

    else:

        print("\n⚠️ FINAL PAPER VALUE AUDIT: REVIEW REQUIRED")

print("\nNO MODELS WERE RETRAINED.")
print("NO THRESHOLDS WERE MODIFIED.")
print("NO EXISTING PREDICTIONS WERE MODIFIED.")
print("=" * 90)

==========================================================================================
WEAR-CHAIN — FINAL PAPER VALUE AUDIT
==========================================================================================

[1] CHECKING REQUIRED ARTIFACTS
------------------------------------------------------------------------------------------
[MISSING] WEAR_CHAIN_E6_overall_metrics.csv
[MISSING] WEAR_CHAIN_E6_attack_family_metrics.csv
[MISSING] WEAR_CHAIN_E6_family_macro_summary.csv
[MISSING] WEAR_CHAIN_E6_capture_family_recall.csv
[MISSING] WEAR_CHAIN_E7_aggregate_metrics.csv
[MISSING] WEAR_CHAIN_E7_fold_metrics.csv
[MISSING] WEAR_CHAIN_E8_inference_benchmark.csv
[MISSING] WEAR_CHAIN_E8_model_sizes.csv
[MISSING] WEAR_CHAIN_E8_resource_summary.csv
[MISSING] WEAR_CHAIN_20_trust_test_predictions.csv
[MISSING] WEAR_CHAIN_21_audit_events.csv
[MISSING] WEAR_CHAIN_21_blockchain_manifest.csv
[MISSING] WEAR_CHAIN_21_ledger_integrity_report.csv
[MISSING] WEAR_CHAIN_22_performance_results.csv
[MISSING] WEAR_CHAIN_17B_reconstructed_test_metrics.csv
[MISSING] WEAR_CHAIN_17B_reconstructed_family_recall.csv
[MISSING] WEAR_CHAIN_unseen_test_predictions.csv

WARNING: Some artifacts are missing.
The audit will continue with whatever is available.

==========================================================================================
E6 — FINAL ATTACK/CAPTURE EVALUATION
==========================================================================================

------------------------------------------------------------------------------------------
E6 — CONFUSION MATRIX CONSISTENCY CHECK
------------------------------------------------------------------------------------------

==========================================================================================
E6 — ATTACK FAMILY RECALL
==========================================================================================

==========================================================================================
E6 — MACRO FAMILY RECALL
==========================================================================================

==========================================================================================
E17B — RECONSTRUCTED FINAL TEST METRICS
==========================================================================================

------------------------------------------------------------------------------------------
CROSS-EXPERIMENT TEST POPULATION CHECK
------------------------------------------------------------------------------------------

REVIEW — Test populations do not all agree.

==========================================================================================
E7 — LEAVE-ONE-ATTACK-FAMILY-OUT GENERALIZATION
==========================================================================================

==========================================================================================
E8 — RESOURCE AND INFERENCE BENCHMARK
==========================================================================================

==========================================================================================
E20 — ADAPTIVE TRUST EVALUATION
==========================================================================================

==========================================================================================
E21/E22 — BLOCKCHAIN / LEDGER AUDIT
==========================================================================================

------------------------------------------------------------------------------------------
BLOCKCHAIN INTEGRITY CHECK
------------------------------------------------------------------------------------------

==========================================================================================
FINAL NUMERICAL AUDIT
==========================================================================================

Status counts:
status
REVIEW    1

,section,metric,value,status,source
0,Cross-check,Final test population agreement,{},REVIEW,E6/E17B/E20/predictions

==========================================================================================
FINAL SUMMARY
==========================================================================================

Paper values saved to:
/WEAR_CHAIN_FINAL_PAPER_VALUES.csv

Audit saved to:
/WEAR_CHAIN_FINAL_PAPER_VALUE_AUDIT.csv

FAIL items   : 0
REVIEW items : 1

⚠️ FINAL PAPER VALUE AUDIT: REVIEW REQUIRED

NO MODELS WERE RETRAINED.
NO THRESHOLDS WERE MODIFIED.
NO EXISTING PREDICTIONS WERE MODIFIED.
==========================================================================================

In [25]:
# ================================================================
# WEAR-CHAIN — FINAL KAGGLE PAPER VALUE EXTRACTION & AUDIT
# ================================================================
# IMPORTANT:
#   - NO MODEL RETRAINING
#   - NO THRESHOLD CHANGES
#   - NO DATA MODIFICATION
#   - Uses existing Kaggle artifacts only
# ================================================================

import os
import glob
import json
import hashlib
import math
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

# ---------------------------------------------------------------
# 0. LOCATE KAGGLE OUTPUT DIRECTORY
# ---------------------------------------------------------------

BASE_OUT = Path("/kaggle/working")

print("=" * 80)
print("WEAR-CHAIN FINAL KAGGLE PAPER VALUE EXTRACTION")
print("=" * 80)
print("Output directory:", BASE_OUT)
print()


# ---------------------------------------------------------------
# 1. HELPER FUNCTIONS
# ---------------------------------------------------------------

audit_rows = []
paper_values = {}

def add_audit(category, item, value, status="INFO", note=""):
    audit_rows.append({
        "category": category,
        "item": item,
        "value": value,
        "status": status,
        "note": note
    })

def add_paper(section, metric, value, source):
    paper_values.setdefault(section, {})
    paper_values[section][metric] = {
        "value": value,
        "source": source
    }

def safe_read_csv(filename, **kwargs):
    path = BASE_OUT / filename
    if not path.exists():
        print(f"WARNING: Missing {filename}")
        return None
    return pd.read_csv(path, **kwargs)


# ---------------------------------------------------------------
# 2. ARTIFACT INVENTORY
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("1. ARTIFACT INVENTORY")
print("=" * 80)

artifact_rows = []

for path in sorted(BASE_OUT.iterdir()):
    if path.is_file():
        artifact_rows.append({
            "file": path.name,
            "extension": path.suffix,
            "exists": True,
            "size_MB": round(path.stat().st_size / (1024**2), 3)
        })

artifact_df = pd.DataFrame(artifact_rows)

print(f"Total files in /kaggle/working: {len(artifact_df)}")
display(artifact_df)

artifact_df.to_csv(
    BASE_OUT / "WEAR_CHAIN_FINAL_artifact_inventory.csv",
    index=False
)

required_artifacts = [
    "WEAR_CHAIN_partitioned_dataset.csv",
    "WEAR_CHAIN_capture_assignments.csv",
    "WEAR_CHAIN_unseen_test_predictions.csv",
    "WEAR_CHAIN_XGBoost_baseline.pkl",
    "WEAR_CHAIN_autoencoder.keras",
    "WEAR_CHAIN_autoencoder_scaler.pkl",
    "WEAR_CHAIN_XGBoost_calibration_predictions.csv",
    "WEAR_CHAIN_20_trust_test_predictions.csv",
    "WEAR_CHAIN_21_audit_events.csv",
    "WEAR_CHAIN_21_blockchain_manifest.csv"
]

print("\nREQUIRED ARTIFACT CHECK")

for name in required_artifacts:
    path = BASE_OUT / name
    status = "PASS" if path.exists() else "FAIL"

    add_audit(
        "Artifacts",
        name,
        str(path.exists()),
        status,
        f"{round(path.stat().st_size/(1024**2),3)} MB"
        if path.exists() else "Missing"
    )

    print(
        f"{status:5s} | {name:50s} | "
        f"{round(path.stat().st_size/(1024**2),3) if path.exists() else 0} MB"
    )


# ---------------------------------------------------------------
# 3. RAW TRAINING FILE INVENTORY
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("2. RAW TRAINING CAPTURE INVENTORY")
print("=" * 80)

# Find the original Kaggle input directory automatically.
possible_input_dirs = [
    Path("/kaggle/input/datasets/gopikrisha/custommade"),
]

DATA_DIR = None

for candidate in possible_input_dirs:
    if candidate.exists():
        DATA_DIR = candidate
        break

if DATA_DIR is None:
    # fallback search
    candidates = list(Path("/kaggle/input").glob("**/*"))
    csv_dirs = [
        p for p in candidates
        if p.is_dir() and any(p.glob("*train*.csv"))
    ]

    if csv_dirs:
        DATA_DIR = csv_dirs[0]

print("Detected DATA_DIR:", DATA_DIR)

raw_df = None

if DATA_DIR is not None:

    raw_paths = sorted(
        p for p in DATA_DIR.glob("*train*.csv")
        if "WEAR_CHAIN" not in p.name
    )

    raw_records = []

    def sha256_file(path):
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b""):
                h.update(chunk)
        return h.hexdigest()

    print(f"Raw training CSV captures found: {len(raw_paths)}")

    for path in raw_paths:

        raw_records.append({
            "source_file": path.name,
            "file_size_MB": round(
                path.stat().st_size / (1024**2), 3
            ),
            "sha256": sha256_file(path)
        })

    raw_df = pd.DataFrame(raw_records)

    display(raw_df)

    raw_df.to_csv(
        BASE_OUT / "WEAR_CHAIN_FINAL_raw_capture_inventory.csv",
        index=False
    )

    add_audit(
        "Dataset",
        "Unique raw training captures",
        len(raw_df),
        "PASS" if len(raw_df) == 51 else "REVIEW",
        "Expected original Kaggle experiment = 51"
    )

    add_paper(
        "Dataset",
        "Raw training captures",
        int(len(raw_df)),
        "WEAR_CHAIN_FINAL_raw_capture_inventory.csv"
    )


# ---------------------------------------------------------------
# 4. PARTITION AUDIT
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("3. PARTITION AUDIT")
print("=" * 80)

partition_df = safe_read_csv(
    "WEAR_CHAIN_partitioned_dataset.csv"
)

if partition_df is not None:

    print("Partitioned dataset shape:", partition_df.shape)

    partition_counts = (
        partition_df["partition"]
        .value_counts()
        .sort_index()
    )

    print("\nPartition counts:")
    display(partition_counts.to_frame("records"))

    for partition, count in partition_counts.items():
        add_paper(
            "Partition",
            f"{partition}_records",
            int(count),
            "WEAR_CHAIN_partitioned_dataset.csv"
        )

    # Expected original Kaggle totals
    expected_partition_totals = {
        "development": 4449176,
        "calibration": 1408617,
    }

    for partition, expected in expected_partition_totals.items():

        actual = int(
            partition_counts.get(partition, 0)
        )

        status = "PASS" if actual == expected else "FAIL"

        add_audit(
            "Partition",
            partition,
            actual,
            status,
            f"Expected {expected}; difference={actual-expected}"
        )

        print(
            f"{partition:15s} | "
            f"Expected={expected:,} | "
            f"Actual={actual:,} | "
            f"{status}"
        )

    if "internal_test" in partition_counts:
        add_paper(
            "Partition",
            "internal_test_records",
            int(partition_counts["internal_test"]),
            "WEAR_CHAIN_partitioned_dataset.csv"
        )


# ---------------------------------------------------------------
# 5. CAPTURE ASSIGNMENT AUDIT
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("4. CAPTURE ASSIGNMENT AUDIT")
print("=" * 80)

capture_df = safe_read_csv(
    "WEAR_CHAIN_capture_assignments.csv"
)

if capture_df is not None:

    print("Capture assignment rows:", len(capture_df))

    display(
        capture_df.groupby(
            ["partition", "attack_family"]
        ).size()
        .reset_index(name="captures")
    )

    duplicate_captures = (
        capture_df["source_file"].duplicated().sum()
    )

    print("Duplicate capture assignments:", duplicate_captures)

    add_audit(
        "Capture Assignment",
        "Rows",
        len(capture_df),
        "INFO"
    )

    add_audit(
        "Capture Assignment",
        "Duplicate source_file assignments",
        int(duplicate_captures),
        "PASS" if duplicate_captures == 0 else "FAIL"
    )


# ---------------------------------------------------------------
# 6. TEST PREDICTION DATASET
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("5. FINAL TEST POPULATION")
print("=" * 80)

pred = safe_read_csv(
    "WEAR_CHAIN_unseen_test_predictions.csv"
)

if pred is None:
    raise FileNotFoundError(
        "WEAR_CHAIN_unseen_test_predictions.csv is required."
    )

print("Test prediction shape:", pred.shape)

TEST_N = len(pred)

print(f"\nTOTAL TEST RECORDS = {TEST_N:,}")

add_paper(
    "Test Population",
    "Total unseen test records",
    int(TEST_N),
    "WEAR_CHAIN_unseen_test_predictions.csv"
)

# Source split
if "test_source" in pred.columns:

    source_counts = (
        pred["test_source"]
        .value_counts(dropna=False)
        .rename_axis("test_source")
        .reset_index(name="records")
    )

    print("\nTest source distribution:")
    display(source_counts)

    for _, row in source_counts.iterrows():
        add_paper(
            "Test Population",
            f'{row["test_source"]}_records',
            int(row["records"]),
            "WEAR_CHAIN_unseen_test_predictions.csv"
        )


# Label distribution
label_counts = (
    pred["label"]
    .value_counts()
    .sort_index()
)

print("\nLabel distribution:")
display(label_counts.to_frame("records"))

for label, count in label_counts.items():

    label_name = "Benign" if int(label) == 0 else "Attack"

    add_paper(
        "Test Population",
        f"{label_name}_records",
        int(count),
        "WEAR_CHAIN_unseen_test_predictions.csv"
    )


# Attack family distribution
if "attack_family" in pred.columns:

    family_counts = (
        pred.groupby(
            ["label", "attack_family"]
        ).size()
        .reset_index(name="records")
        .sort_values(["label", "records"], ascending=[True, False])
    )

    print("\nAttack-family distribution:")
    display(family_counts)

    family_counts.to_csv(
        BASE_OUT / "WEAR_CHAIN_FINAL_test_family_counts.csv",
        index=False
    )


# ---------------------------------------------------------------
# 7. VERIFY PREDICTION COLUMNS
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("6. PREDICTION COLUMN AUDIT")
print("=" * 80)

required_prediction_columns = [
    "test_source",
    "source_file",
    "label",
    "attack_family",
    "xgb_score",
    "ae_score",
    "xgb_percentile",
    "ae_percentile",
    "hybrid_max_score",
    "hybrid_average_score",
    "XGBoost_prediction",
    "Autoencoder_prediction",
    "Hybrid_Max_prediction",
    "Hybrid_Average_prediction"
]

for col in required_prediction_columns:

    exists = col in pred.columns

    add_audit(
        "Prediction Columns",
        col,
        str(exists),
        "PASS" if exists else "FAIL"
    )

    print(
        f"{'PASS' if exists else 'FAIL':5s} | {col}"
    )


# ---------------------------------------------------------------
# 8. THRESHOLDS
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("7. FINAL DETECTION THRESHOLDS")
print("=" * 80)

# Known values from executed Kaggle run.
# We do NOT change or recompute them here.

threshold_values = {
    "XGBoost": 0.340408,
    "Hybrid_Max": 0.99488936,
    "Hybrid_Average": 0.94991439,
    "Autoencoder": None
}

# Try to recover AE threshold from existing notebook variables
# if the notebook variable still exists.
if "AE_THRESHOLD" in globals():
    threshold_values["Autoencoder"] = float(AE_THRESHOLD)

for model, value in threshold_values.items():

    print(
        f"{model:18s} = "
        f"{value if value is not None else 'NOT STORED IN FINAL CELL'}"
    )

    add_paper(
        "Detection Thresholds",
        model,
        value,
        "Executed Kaggle notebook / existing notebook variable"
    )


# ---------------------------------------------------------------
# 9. INDEPENDENTLY RECONSTRUCT FINAL METRICS
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("8. INDEPENDENT RECONSTRUCTION OF FINAL TEST METRICS")
print("=" * 80)

model_map = {
    "XGBoost": (
        "XGBoost_prediction",
        "xgb_score"
    ),
    "Autoencoder": (
        "Autoencoder_prediction",
        "ae_score"
    ),
    "Hybrid_Max": (
        "Hybrid_Max_prediction",
        "hybrid_max_score"
    ),
    "Hybrid_Average": (
        "Hybrid_Average_prediction",
        "hybrid_average_score"
    )
}

metric_rows = []

for model_name, (pred_col, score_col) in model_map.items():

    actual = pred["label"].astype(int).to_numpy()
    predicted = pred[pred_col].astype(int).to_numpy()

    tn, fp, fn, tp = confusion_matrix(
        actual,
        predicted,
        labels=[0, 1]
    ).ravel()

    row = {
        "model": model_name,
        "records": len(pred),
        "accuracy": accuracy_score(actual, predicted),
        "precision": precision_score(
            actual, predicted, zero_division=0
        ),
        "recall": recall_score(
            actual, predicted, zero_division=0
        ),
        "f1": f1_score(
            actual, predicted, zero_division=0
        ),
        "FPR": fp / (fp + tn),
        "FNR": fn / (fn + tp),
        "TN": int(tn),
        "FP": int(fp),
        "FN": int(fn),
        "TP": int(tp)
    }

    # ROC/PR AUC if labels and scores support them
    try:
        scores = pd.to_numeric(
            pred[score_col],
            errors="coerce"
        ).to_numpy()

        row["ROC_AUC"] = roc_auc_score(
            actual,
            scores
        )

        row["PR_AUC"] = average_precision_score(
            actual,
            scores
        )

    except Exception:
        row["ROC_AUC"] = np.nan
        row["PR_AUC"] = np.nan

    metric_rows.append(row)

metrics_df = pd.DataFrame(metric_rows)

display(
    metrics_df.style.format({
        "accuracy": "{:.6f}",
        "precision": "{:.6f}",
        "recall": "{:.6f}",
        "f1": "{:.6f}",
        "FPR": "{:.6f}",
        "FNR": "{:.6f}",
        "ROC_AUC": "{:.6f}",
        "PR_AUC": "{:.6f}"
    })
)

metrics_df.to_csv(
    BASE_OUT / "WEAR_CHAIN_FINAL_test_metrics.csv",
    index=False
)


# Add paper values
for _, row in metrics_df.iterrows():

    model = row["model"]

    for metric in [
        "accuracy",
        "precision",
        "recall",
        "f1",
        "FPR",
        "FNR",
        "ROC_AUC",
        "PR_AUC",
        "TN",
        "FP",
        "FN",
        "TP"
    ]:

        add_paper(
            "Final Test Metrics",
            f"{model}_{metric}",
            (
                float(row[metric])
                if pd.notna(row[metric])
                else None
            ),
            "Independent reconstruction from WEAR_CHAIN_unseen_test_predictions.csv"
        )


# ---------------------------------------------------------------
# 10. CONFUSION-MATRIX TOTAL CHECK
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("9. CONFUSION MATRIX RECONCILIATION")
print("=" * 80)

for _, row in metrics_df.iterrows():

    total = (
        row["TN"] +
        row["FP"] +
        row["FN"] +
        row["TP"]
    )

    status = (
        "PASS"
        if total == TEST_N
        else "FAIL"
    )

    print(
        f"{row['model']:18s} | "
        f"TN+FP+FN+TP={int(total):,} | "
        f"Test={TEST_N:,} | {status}"
    )

    add_audit(
        "Metrics",
        f"{row['model']} confusion matrix total",
        int(total),
        status,
        f"Expected {TEST_N}"
    )


# ---------------------------------------------------------------
# 11. PREDICTION VALIDITY
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("10. PREDICTION VALIDITY CHECKS")
print("=" * 80)

for model, (pred_col, score_col) in model_map.items():

    unique_predictions = sorted(
        pred[pred_col].dropna().unique().tolist()
    )

    valid_binary = set(unique_predictions).issubset({0, 1})

    missing_scores = int(
        pred[score_col].isna().sum()
    )

    print(
        f"{model:18s} | "
        f"binary={valid_binary} | "
        f"missing scores={missing_scores}"
    )

    add_audit(
        "Prediction Validity",
        f"{model} binary predictions",
        str(unique_predictions),
        "PASS" if valid_binary else "FAIL"
    )

    add_audit(
        "Prediction Validity",
        f"{model} missing scores",
        missing_scores,
        "PASS" if missing_scores == 0 else "FAIL"
    )


# ---------------------------------------------------------------
# 12. TRUST MANAGEMENT
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("11. ADAPTIVE TRUST MANAGEMENT")
print("=" * 80)

trust_file = (
    BASE_OUT /
    "WEAR_CHAIN_20_trust_test_predictions.csv"
)

if trust_file.exists():

    trust_df = pd.read_csv(trust_file)

    print("Trust prediction rows:", len(trust_df))
    print("\nTrust columns:")
    print(list(trust_df.columns))

    # Known selected configuration from executed notebook
    DECAY_VALUE = 0.10
    RECOVERY_VALUE = 0.02
    BLOCK_THRESHOLD_VALUE = 0.30
    ALERT_THRESHOLD_VALUE = 0.50

    print("\nSelected configuration:")
    print("Decay           :", DECAY_VALUE)
    print("Recovery        :", RECOVERY_VALUE)
    print("Alert threshold :", ALERT_THRESHOLD_VALUE)
    print("Block threshold :", BLOCK_THRESHOLD_VALUE)

    add_paper(
        "Adaptive Trust",
        "Decay",
        DECAY_VALUE,
        "Executed Kaggle Section 20"
    )

    add_paper(
        "Adaptive Trust",
        "Recovery",
        RECOVERY_VALUE,
        "Executed Kaggle Section 20"
    )

    add_paper(
        "Adaptive Trust",
        "Alert threshold",
        ALERT_THRESHOLD_VALUE,
        "Executed Kaggle Section 20"
    )

    add_paper(
        "Adaptive Trust",
        "Block threshold",
        BLOCK_THRESHOLD_VALUE,
        "Executed Kaggle Section 20"
    )

    # Trust states
    if "trust_state" in trust_df.columns:

        state_counts = (
            trust_df["trust_state"]
            .value_counts(dropna=False)
            .rename_axis("trust_state")
            .reset_index(name="records")
        )

        state_counts["percentage"] = (
            state_counts["records"] /
            len(trust_df) * 100
        )

        print("\nOverall trust-state distribution:")
        display(state_counts)

        state_counts.to_csv(
            BASE_OUT / "WEAR_CHAIN_FINAL_trust_state_counts.csv",
            index=False
        )

        for _, row in state_counts.iterrows():

            add_paper(
                "Adaptive Trust",
                f"Overall_{row['trust_state']}_records",
                int(row["records"]),
                "WEAR_CHAIN_20_trust_test_predictions.csv"
            )

            add_paper(
                "Adaptive Trust",
                f"Overall_{row['trust_state']}_percentage",
                float(row["percentage"]),
                "WEAR_CHAIN_20_trust_test_predictions.csv"
            )

        # Trust states by actual label
        if "label" in trust_df.columns:

            trust_by_label = (
                trust_df
                .groupby(
                    ["label", "trust_state"]
                )
                .size()
                .reset_index(name="records")
            )

            trust_by_label["percentage_within_label"] = (
                trust_by_label
                .groupby("label")["records"]
                .transform(lambda x: x / x.sum() * 100)
            )

            print("\nTrust states by actual class:")
            display(trust_by_label)

            trust_by_label.to_csv(
                BASE_OUT /
                "WEAR_CHAIN_FINAL_trust_by_label.csv",
                index=False
            )

            for _, row in trust_by_label.iterrows():

                label_name = (
                    "Benign"
                    if int(row["label"]) == 0
                    else "Attack"
                )

                add_paper(
                    "Adaptive Trust",
                    f"{label_name}_{row['trust_state']}_records",
                    int(row["records"]),
                    "WEAR_CHAIN_20_trust_test_predictions.csv"
                )

                add_paper(
                    "Adaptive Trust",
                    f"{label_name}_{row['trust_state']}_percentage",
                    float(row["percentage_within_label"]),
                    "WEAR_CHAIN_20_trust_test_predictions.csv"
                )

else:

    print("WARNING: Trust artifact not found.")

    add_audit(
        "Adaptive Trust",
        "WEAR_CHAIN_20_trust_test_predictions.csv",
        "Missing",
        "REVIEW"
    )


# ---------------------------------------------------------------
# 13. BLOCKCHAIN / HASH-LINKED LEDGER
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("12. BLOCKCHAIN / HASH-LINKED LEDGER")
print("=" * 80)

events_file = (
    BASE_OUT /
    "WEAR_CHAIN_21_audit_events.csv"
)

blocks_file = (
    BASE_OUT /
    "WEAR_CHAIN_21_blockchain_manifest.csv"
)

events_df = None
blocks_df = None

if events_file.exists():

    events_df = pd.read_csv(events_file)

    print("Ledger events:", len(events_df))

    add_paper(
        "Blockchain Ledger",
        "Ledger events",
        int(len(events_df)),
        "WEAR_CHAIN_21_audit_events.csv"
    )

else:
    print("WARNING: audit events file missing.")

if blocks_file.exists():

    blocks_df = pd.read_csv(blocks_file)

    print("Ledger blocks:", len(blocks_df))

    add_paper(
        "Blockchain Ledger",
        "Ledger blocks",
        int(len(blocks_df)),
        "WEAR_CHAIN_21_blockchain_manifest.csv"
    )

else:
    print("WARNING: blockchain manifest missing.")


# ---------------------------------------------------------------
# 14. BLOCKCHAIN STRUCTURAL CHECKS
# ---------------------------------------------------------------

if events_df is not None:

    print("\nLedger event structure:")
    print(list(events_df.columns))

    required_event_cols = [
        "source_file",
        "test_source",
        "score",
        "trust_score",
        "detector_flag",
        "trust_state",
        "sequence_id",
        "event_hash"
    ]

    for col in required_event_cols:

        exists = col in events_df.columns

        add_audit(
            "Blockchain",
            f"Event column: {col}",
            str(exists),
            "PASS" if exists else "FAIL"
        )

    # Sequence check
    if "sequence_id" in events_df.columns:

        expected_sequence = np.arange(
            1,
            len(events_df) + 1
        )

        actual_sequence = (
            events_df["sequence_id"]
            .to_numpy()
        )

        sequence_ok = np.array_equal(
            actual_sequence,
            expected_sequence
        )

        print(
            "Sequence integrity:",
            "PASS" if sequence_ok else "FAIL"
        )

        add_audit(
            "Blockchain",
            "Sequential event IDs",
            str(sequence_ok),
            "PASS" if sequence_ok else "FAIL"
        )

    # Duplicate hashes
    if "event_hash" in events_df.columns:

        duplicate_event_hashes = (
            events_df["event_hash"]
            .duplicated()
            .sum()
        )

        print(
            "Duplicate event hashes:",
            duplicate_event_hashes
        )

        add_audit(
            "Blockchain",
            "Duplicate event hashes",
            int(duplicate_event_hashes),
            "PASS"
            if duplicate_event_hashes == 0
            else "REVIEW"
        )


# ---------------------------------------------------------------
# 15. RECOMPUTE EVENT HASHES
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("13. SHA-256 EVENT HASH VERIFICATION")
print("=" * 80)

def canonical_json(record):
    return json.dumps(
        record,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False
    )

def sha256_text(value):
    return hashlib.sha256(
        value.encode("utf-8")
    ).hexdigest()

event_hash_check = None

if events_df is not None:

    required_cols = [
        "sequence_id",
        "source_file",
        "test_source",
        "score",
        "trust_score",
        "detector_flag",
        "trust_state",
        "event_hash"
    ]

    if all(c in events_df.columns for c in required_cols):

        recomputed_hashes = []

        for r in events_df.itertuples(index=False):

            payload = {
                "sequence_id": int(r.sequence_id),
                "source_file": str(r.source_file),
                "test_source": str(r.test_source),
                "score": float(r.score),
                "trust_score": float(r.trust_score),
                "detector_flag": int(r.detector_flag),
                "trust_state": str(r.trust_state)
            }

            recomputed_hashes.append(
                sha256_text(
                    canonical_json(payload)
                )
            )

        stored_hashes = (
            events_df["event_hash"]
            .astype(str)
            .tolist()
        )

        event_hash_check = (
            recomputed_hashes == stored_hashes
        )

        matching = sum(
            a == b
            for a, b in zip(
                recomputed_hashes,
                stored_hashes
            )
        )

        print(
            f"Matching event hashes: "
            f"{matching:,}/{len(events_df):,}"
        )

        print(
            "Event hash integrity:",
            "PASS" if event_hash_check else "FAIL"
        )

        add_paper(
            "Blockchain Ledger",
            "Event hash integrity",
            bool(event_hash_check),
            "Independent SHA-256 recomputation"
        )

        add_audit(
            "Blockchain",
            "SHA-256 event integrity",
            str(event_hash_check),
            "PASS" if event_hash_check else "FAIL"
        )


# ---------------------------------------------------------------
# 16. RECOMPUTE MERKLE ROOTS + BLOCK HASH CHAIN
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("14. MERKLE ROOT AND BLOCK HASH VERIFICATION")
print("=" * 80)

def calculate_merkle_root(hashes):

    if not hashes:
        return sha256_text("EMPTY_BLOCK")

    level = list(hashes)

    while len(level) > 1:

        if len(level) % 2 == 1:
            level.append(level[-1])

        level = [
            sha256_text(
                level[i] + level[i + 1]
            )
            for i in range(
                0,
                len(level),
                2
            )
        ]

    return level[0]


merkle_ok = None
block_chain_ok = None

if events_df is not None and blocks_df is not None:

    event_hashes = (
        events_df["event_hash"]
        .astype(str)
        .tolist()
    )

    recomputed_block_rows = []

    previous_hash = "WEAR_CHAIN_GENESIS_BLOCK"

    for block_number, start in enumerate(
        range(
            0,
            len(events_df),
            1000
        ),
        start=1
    ):

        end = min(
            start + 1000,
            len(events_df)
        )

        block_event_hashes = (
            event_hashes[start:end]
        )

        merkle_root = calculate_merkle_root(
            block_event_hashes
        )

        payload = {
            "block_number": block_number,
            "start_sequence": start + 1,
            "end_sequence": end,
            "event_count": end - start,
            "merkle_root": merkle_root,
            "previous_block_hash": previous_hash
        }

        block_hash = sha256_text(
            canonical_json(payload)
        )

        recomputed_block_rows.append({
            **payload,
            "block_hash": block_hash
        })

        previous_hash = block_hash

    recomputed_blocks = pd.DataFrame(
        recomputed_block_rows
    )

    # Compare the generated manifest with saved manifest
    comparison_columns = [
        "block_number",
        "start_sequence",
        "end_sequence",
        "event_count",
        "merkle_root",
        "previous_block_hash",
        "block_hash"
    ]

    saved_compare = blocks_df[
        comparison_columns
    ].copy()

    saved_compare = saved_compare.reset_index(
        drop=True
    )

    recomputed_compare = recomputed_blocks[
        comparison_columns
    ].copy()

    recomputed_compare = recomputed_compare.reset_index(
        drop=True
    )

    block_chain_ok = saved_compare.equals(
        recomputed_compare
    )

    print(
        "Block/Merkle integrity:",
        "PASS" if block_chain_ok else "FAIL"
    )

    if not block_chain_ok:

        print("\nSaved vs recomputed block differences:")

        comparison = saved_compare.compare(
            recomputed_compare,
            result_names=("saved", "recomputed")
        )

        display(comparison.head(50))

    else:

        print(
            f"Verified blocks: "
            f"{len(blocks_df):,}"
        )

    add_paper(
        "Blockchain Ledger",
        "Merkle/block-chain integrity",
        bool(block_chain_ok),
        "Independent reconstruction"
    )

    add_paper(
        "Blockchain Ledger",
        "Block size",
        1000,
        "Executed Kaggle Section 21"
    )

    add_paper(
        "Blockchain Ledger",
        "Genesis hash",
        "WEAR_CHAIN_GENESIS_BLOCK",
        "Executed Kaggle Section 21"
    )

    add_audit(
        "Blockchain",
        "Merkle/block hash chain",
        str(block_chain_ok),
        "PASS" if block_chain_ok else "FAIL"
    )


# ---------------------------------------------------------------
# 17. LEDGER OVERHEAD / SIZE
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("15. LEDGER STORAGE INFORMATION")
print("=" * 80)

if events_file.exists():

    events_size_mb = (
        events_file.stat().st_size /
        (1024**2)
    )

    print(
        f"Audit event ledger size: "
        f"{events_size_mb:.3f} MB"
    )

    add_paper(
        "Blockchain Ledger",
        "Audit event file size MB",
        round(events_size_mb, 3),
        "WEAR_CHAIN_21_audit_events.csv"
    )

if blocks_file.exists():

    blocks_size_mb = (
        blocks_file.stat().st_size /
        (1024**2)
    )

    print(
        f"Blockchain manifest size: "
        f"{blocks_size_mb:.3f} MB"
    )

    add_paper(
        "Blockchain Ledger",
        "Blockchain manifest size MB",
        round(blocks_size_mb, 3),
        "WEAR_CHAIN_21_blockchain_manifest.csv"
    )


# ---------------------------------------------------------------
# 18. FINAL MODEL ARTIFACT CHECK
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("16. MODEL ARTIFACT VERIFICATION")
print("=" * 80)

model_artifacts = [
    "WEAR_CHAIN_XGBoost_baseline.pkl",
    "WEAR_CHAIN_autoencoder.keras",
    "WEAR_CHAIN_autoencoder_scaler.pkl"
]

for filename in model_artifacts:

    path = BASE_OUT / filename

    if path.exists():

        size_mb = path.stat().st_size / (
            1024**2
        )

        print(
            f"PASS | {filename:45s} | "
            f"{size_mb:.3f} MB"
        )

        add_paper(
            "Model Artifacts",
            filename,
            True,
            f"{size_mb:.3f} MB"
        )

    else:

        print(
            f"FAIL | {filename}"
        )

        add_paper(
            "Model Artifacts",
            filename,
            False,
            "Missing"
        )


# ---------------------------------------------------------------
# 19. FINAL DATASET NUMBERS
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("17. FINAL DATASET VALUES")
print("=" * 80)

# Known authoritative values from the executed Kaggle experiment.
# These are recorded here for paper extraction, NOT used to alter
# any experiment.

known_dataset_values = {
    "raw_training_rows": 7160831,
    "clean_training_rows": 7160827,
    "excluded_malformed_rows": 4,
    "raw_capture_count": 51,
    "model_feature_count": 44,
    "development_rows": 4449176,
    "calibration_rows": 1408617,
    "unseen_test_rows": 1342385
}

for metric, value in known_dataset_values.items():

    print(
        f"{metric:30s}: {value:,}"
    )

    add_paper(
        "Dataset",
        metric,
        value,
        "Executed Kaggle experiment / audit records"
    )


# ---------------------------------------------------------------
# 20. FINAL MODEL SUMMARY
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("18. FINAL MODEL SUMMARY")
print("=" * 80)

summary_columns = [
    "model",
    "records",
    "accuracy",
    "precision",
    "recall",
    "f1",
    "FPR",
    "FNR",
    "TN",
    "FP",
    "FN",
    "TP"
]

display(
    metrics_df[
        summary_columns
    ].round(6)
)


# ---------------------------------------------------------------
# 21. FINAL PAPER VALUES TABLE
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("19. PAPER-READY VALUES")
print("=" * 80)

paper_rows = []

for section, values in paper_values.items():

    for metric, obj in values.items():

        paper_rows.append({
            "section": section,
            "metric": metric,
            "value": obj["value"],
            "source": obj["source"]
        })

paper_df = pd.DataFrame(paper_rows)

display(paper_df)

paper_df.to_csv(
    BASE_OUT /
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv",
    index=False
)


# ---------------------------------------------------------------
# 22. FINAL AUDIT TABLE
# ---------------------------------------------------------------

audit_df = pd.DataFrame(audit_rows)

audit_df.to_csv(
    BASE_OUT /
    "WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv",
    index=False
)

print("\n" + "=" * 80)
print("20. FINAL AUDIT STATUS")
print("=" * 80)

fail_count = (
    audit_df["status"]
    .astype(str)
    .str.upper()
    .eq("FAIL")
    .sum()
)

review_count = (
    audit_df["status"]
    .astype(str)
    .str.upper()
    .eq("REVIEW")
    .sum()
)

pass_count = (
    audit_df["status"]
    .astype(str)
    .str.upper()
    .eq("PASS")
    .sum()
)

print("PASS   :", pass_count)
print("REVIEW :", review_count)
print("FAIL   :", fail_count)

if fail_count == 0:
    if review_count == 0:
        final_status = "PASS"
    else:
        final_status = "PASS_WITH_REVIEW"
else:
    final_status = "FAIL"

print("\nFINAL STATUS:", final_status)


# ---------------------------------------------------------------
# 23. JSON EXPORT
# ---------------------------------------------------------------

final_json = {
    "project": "WEAR-CHAIN",
    "experiment": "Original Kaggle experiment",
    "final_status": final_status,
    "audit_counts": {
        "PASS": int(pass_count),
        "REVIEW": int(review_count),
        "FAIL": int(fail_count)
    },
    "paper_values": paper_values
}

with open(
    BASE_OUT /
    "WEAR_CHAIN_FINAL_PAPER_VALUES.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        final_json,
        f,
        indent=2,
        default=str
    )


# ---------------------------------------------------------------
# 24. FINAL FILE LIST
# ---------------------------------------------------------------

print("\n" + "=" * 80)
print("FINAL OUTPUT FILES")
print("=" * 80)

final_files = [
    "WEAR_CHAIN_FINAL_test_metrics.csv",
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv",
    "WEAR_CHAIN_FINAL_PAPER_VALUES.json",
    "WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv",
    "WEAR_CHAIN_FINAL_artifact_inventory.csv",
    "WEAR_CHAIN_FINAL_raw_capture_inventory.csv",
    "WEAR_CHAIN_FINAL_test_family_counts.csv",
    "WEAR_CHAIN_FINAL_trust_state_counts.csv",
    "WEAR_CHAIN_FINAL_trust_by_label.csv"
]

for filename in final_files:

    path = BASE_OUT / filename

    if path.exists():

        print(
            f"PASS | {filename:55s} | "
            f"{path.stat().st_size/(1024**2):.3f} MB"
        )

    else:

        print(
            f"---- | {filename:55s} | not generated"
        )


print("\n" + "=" * 80)
print("WEAR-CHAIN FINAL EXTRACTION COMPLETE")
print("=" * 80)

print("""
IMPORTANT:
These outputs are extracted/reconstructed from the existing Kaggle
experiment. No model was retrained and no threshold was changed.

The most important files for the paper are:

1. WEAR_CHAIN_FINAL_test_metrics.csv
2. WEAR_CHAIN_FINAL_PAPER_VALUES.csv
3. WEAR_CHAIN_FINAL_PAPER_VALUES.json
4. WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv

Do not mix these values with the later Colab experiment.
""")

================================================================================
WEAR-CHAIN FINAL KAGGLE PAPER VALUE EXTRACTION
================================================================================
Output directory: /kaggle/working


================================================================================
1. ARTIFACT INVENTORY
================================================================================
Total files in /kaggle/working: 36

,file,extension,exists,size_MB
0,WEAR_CHAIN_17B_reconstructed_test_metrics.csv,.csv,True,0.001
1,WEAR_CHAIN_17C_raw_file_inventory.csv,.csv,True,0.005
2,WEAR_CHAIN_18_recovery_inventory.csv,.csv,True,0.000
3,WEAR_CHAIN_20_trust_test_predictions.csv,.csv,True,83.280
4,WEAR_CHAIN_21_audit_events.csv,.csv,True,173.109
5,WEAR_CHAIN_21_blockchain_manifest.csv,.csv,True,0.280
6,WEAR_CHAIN_IAT_descriptive_statistics.csv,.csv,True,0.000
7,WEAR_CHAIN_XGBoost_baseline.pkl,.pkl,True,0.884
8,WEAR_CHAIN_XGBoost_calibration_predictions.csv,.csv,True,76.720
9,WEAR_CHAIN_XGBoost_feature_importance.csv,.csv,True,0.001
10,WEAR_CHAIN_autoencoder.keras,.keras,True,0.090
11,WEAR_CHAIN_autoencoder_calibration_scores.csv,.csv,True,76.939
12,WEAR_CHAIN_autoencoder_scaler.pkl,.pkl,True,0.002
13,WEAR_CHAIN_capture_assignments.csv,.csv,True,0.003
14,WEAR_CHAIN_correlations.csv,.csv,True,0.052
15,WEAR_CHAIN_external_FP_feature_comparison.csv,.csv,True,0.005
16,WEAR_CHAIN_external_FP_importance_analysis.csv,.csv,True,0.006
17,WEAR_CHAIN_external_test_audit.csv,.csv,True,0.000
18,WEAR_CHAIN_external_test_dataset.csv,.csv,True,13.054
19,WEAR_CHAIN_external_udp_fp_feature_comparison.csv,.csv,True,0.003
20,WEAR_CHAIN_family_medians.csv,.csv,True,0.001
21,WEAR_CHAIN_feature_distribution_drift.csv,.csv,True,0.005
22,WEAR_CHAIN_feature_drift_importance_combined.csv,.csv,True,0.006
23,WEAR_CHAIN_feature_quality.csv,.csv,True,0.002
24,WEAR_CHAIN_hybrid_calibration_scores.csv,.csv,True,106.454
25,WEAR_CHAIN_partition_summary.csv,.csv,True,0.000
26,WEAR_CHAIN_partitioned_dataset.csv,.csv,True,2172.394
27,WEAR_CHAIN_protocol_pattern_distribution.csv,.csv,True,0.002
28,WEAR_CHAIN_score_distribution_summary.csv,.csv,True,0.001
29,WEAR_CHAIN_section17_partition_audit.csv,.csv,True,0.000
30,WEAR_CHAIN_udp_benign_protocol17_summary.csv,.csv,True,0.001
31,WEAR_CHAIN_udp_xgb_contribution_comparison.csv,.csv,True,0.002
32,WEAR_CHAIN_udp_xgb_record_contributions.csv,.csv,True,1.660
33,WEAR_CHAIN_unseen_test_predictions.csv,.csv,True,164.874
34,__notebook__.ipynb,.ipynb,True,0.853
35,ciciomt_capture_inventory.csv,.csv,True,0.003

REQUIRED ARTIFACT CHECK
PASS  | WEAR_CHAIN_partitioned_dataset.csv                 | 2172.394 MB
PASS  | WEAR_CHAIN_capture_assignments.csv                 | 0.003 MB
PASS  | WEAR_CHAIN_unseen_test_predictions.csv             | 164.874 MB
PASS  | WEAR_CHAIN_XGBoost_baseline.pkl                    | 0.884 MB
PASS  | WEAR_CHAIN_autoencoder.keras                       | 0.09 MB
PASS  | WEAR_CHAIN_autoencoder_scaler.pkl                  | 0.002 MB
PASS  | WEAR_CHAIN_XGBoost_calibration_predictions.csv     | 76.72 MB
PASS  | WEAR_CHAIN_20_trust_test_predictions.csv           | 83.28 MB
PASS  | WEAR_CHAIN_21_audit_events.csv                     | 173.109 MB
PASS  | WEAR_CHAIN_21_blockchain_manifest.csv              | 0.28 MB

================================================================================
2. RAW TRAINING CAPTURE INVENTORY
================================================================================
Detected DATA_DIR: /kaggle/input/datasets/gopikrisha/custommade
Raw training CSV captures found: 51

,source_file,file_size_MB,sha256
0,ARP_Spoofing_train.pcap.csv,4.608,f0d68653cfe5873f280a0cd84323145d6112861819204b...
1,Benign_train.pcap.csv,56.699,5337565793ff0460270da0b848e2ca8eafbd529a9715ce...
2,MQTT-DDoS-Connect_Flood_train.pcap.csv,52.414,0739bf1a52f7e6accaba1252e3a7393c476f87122c663b...
3,MQTT-DDoS-Publish_Flood_train.pcap.csv,8.568,45f73cd42af9bd71e890ea77e52316ed1a3e90351e4041...
4,MQTT-DoS-Connect_Flood_train.pcap.csv,3.873,93093507c84ef2d71ae9b6fad4669d145e2601d981b6b4...
5,MQTT-DoS-Publish_Flood_train.pcap.csv,13.445,f5cc6b18ddb55febb2f3132c8bb3e4471277bf2fb6f6a8...
6,MQTT-Malformed_Data_train.pcap.csv,1.459,292efe2f8b07203c53c65f7d5c5af05bcc4429cd06701a...
7,Recon-OS_Scan_train.pcap.csv,4.321,c8450cd6a2808243b66fe9308d49d9e3e1b88802c7debb...
8,Recon-Ping_Sweep_train.pcap.csv,0.201,aa2fce831dc4c73c7d6138eca415bb2966870599d0ca7e...
9,Recon-Port_Scan_train.pcap.csv,21.538,7dc0785d3e69d4e1a083582dad0efc4c94c35bbc75e56e...
10,Recon-VulScan_train.pcap.csv,0.604,c4abeec187c4ac8167b69251fa9d3d4e8ca182ddb5fcfd...
11,TCP_IP-DDoS-ICMP1_train.pcap.csv,45.378,421e6cf37dde9a8a17ab473cc7977647f298ef47326110...
12,TCP_IP-DDoS-ICMP2_train.pcap.csv,44.878,ae8b5ded976d6f49ff01babb66431ffb250f63695c349d...
13,TCP_IP-DDoS-ICMP3_train.pcap.csv,47.482,71bde2ecf6f5ab28a3c2eb5205cb6bfaca7338b1d17cf0...
14,TCP_IP-DDoS-ICMP4_train.pcap.csv,46.893,e4a3074f251ee5c6df6650136b5199c5e738cc582c5559...
15,TCP_IP-DDoS-ICMP5_train.pcap.csv,45.168,92f2ba3e950de4a656343370737e3e5033918e0832f2f0...
16,TCP_IP-DDoS-ICMP6_train.pcap.csv,44.679,acf11dd59b947fd0c0cfb538832346a6c2c503241157f9...
17,TCP_IP-DDoS-ICMP7_train.pcap.csv,43.908,c0d9f56186383d15d71c88eb38b25243795bb234fda99c...
18,TCP_IP-DDoS-ICMP8_train.pcap.csv,44.957,d542b4b84fcc0d4c9b88cc8e2101752d1d94d4e4cedbf3...
19,TCP_IP-DDoS-SYN1_train.pcap.csv,52.680,6563e1d9b9dbddbe9172b6916bd22b624b32b489ba899a...
20,TCP_IP-DDoS-SYN2_train.pcap.csv,55.466,58e602b0b9efff6d256a822dbf1698babaadc90f1a9002...
21,TCP_IP-DDoS-SYN3_train.pcap.csv,57.821,7ba40eadca16c42d66dc180e48cc7c343e15ca518f01ee...
22,TCP_IP-DDoS-SYN4_train.pcap.csv,46.998,c1c362bb07e3773797f95626fc62d88d590e7ef960be9a...
23,TCP_IP-DDoS-TCP1_train.pcap.csv,50.530,ce2eece139e36bcf3eac8da2ed8447652dc5b0fd383439...
24,TCP_IP-DDoS-TCP2_train.pcap.csv,48.457,b16359ecb30825d32c6eec4d966f8a0eccc735d609cf36...
25,TCP_IP-DDoS-TCP3_train.pcap.csv,48.061,1cf4238b3ddd9350f6e5f473f275ee599a97451ddcccd2...
26,TCP_IP-DDoS-TCP4_train.pcap.csv,48.136,5695efe61f4e94a3c93184bd970495205f02425b15695f...
27,TCP_IP-DDoS-UDP1_train.pcap.csv,47.676,ecfdafd04396912abbb0c679431c12b225d2e60651a1f1...
28,TCP_IP-DDoS-UDP2_train.pcap.csv,47.531,862223972addbd30ddfac516cd94b937d9ed465497dd7f...
29,TCP_IP-DDoS-UDP3_train.pcap.csv,49.935,83b720d6b77379b1b91461e061c5f464c765c628d301ed...
30,TCP_IP-DDoS-UDP4_train.pcap.csv,49.795,76f5a0e57181bf9b1d200f87b1ab69aec6eebf80a4f394...
31,TCP_IP-DDoS-UDP5_train.pcap.csv,48.481,1b316d70ae8cfd19c8f8292e1914adfebd39d732d32b71...
32,TCP_IP-DDoS-UDP6_train.pcap.csv,49.237,230f99ef999649538ed013a1a6cfd99aefd1c30481f130...
33,TCP_IP-DDoS-UDP7_train.pcap.csv,45.992,6d9f7c56a5edc30c9628eb87904ceb1e3ca576d319b1f1...
34,TCP_IP-DDoS-UDP8_train.pcap.csv,47.090,80c51b47fcc14eef34b9a484e3e84d84b2a077492dcb39...
35,TCP_IP-DoS-ICMP1_train.pcap.csv,27.282,dfb859a6c2dfb84f05acd935b5aa36af5e38a122b6abf4...
36,TCP_IP-DoS-ICMP2_train.pcap.csv,23.984,f6d20bc819226d5855b2de01cf98a1cf67fae6f1c98244...
37,TCP_IP-DoS-ICMP3_train.pcap.csv,25.621,ec5d9e7189f522b31e0f6affd51dd6bb857b3a7ff63688...
38,TCP_IP-DoS-ICMP4_train.pcap.csv,25.841,b04253e20396d7ffc348c19acad4d57fc3359ad74091f8...
39,TCP_IP-DoS-SYN1_train.pcap.csv,33.252,a3db508fa739a83c4966ed2e6e43431a7c0f009a7ae490...
40,TCP_IP-DoS-SYN2_train.pcap.csv,29.066,105c18058ee979cd34ba2bf8a278b7547866e215d2b684...
41,TCP_IP-DoS-SYN3_train.pcap.csv,28.794,34010f5dd9fb730055cdbf3d3bb2967f7cde89495f0464...
42,TCP_IP-DoS-SYN4_train.pcap.csv,27.715,35b2ce8e2a0359779e5bf46e944bd007feb51edea5f677...
43,TCP_IP-DoS-TCP1_train.pcap.csv,23.064,ddaccc225dc04630df932269e330db1c8ca5de107bd32d...
44,TCP_IP-DoS-TCP2_train.pcap.csv,24.381,fdda01333df6e6a76f772ffb3702b7905f1591ed5391a8...
45,TCP_IP-DoS-TCP3_train.pcap.csv,23.128,09575ce27ec0464bee31e3f40c6b0877601381fd7fc986...
46,TCP_IP-DoS-TCP4_train.pcap.csv,22.474,1f90983d49207153eba59259808c659a307dcad0394749...
47,TCP_IP-DoS-UDP1_train.pcap.csv,33.830,083d7310340e66f7256567ccb048c99c49ecdf4a7cfb10...
48,TCP_IP-DoS-UDP2_train.pcap.csv,32.734,68af8270f9a47a47086b534ff7f45abdc59c5ed1303b82...
49,TCP_IP-DoS-UDP3_train.pcap.csv,33.923,394ffda61e15f69fbfbfc0f6fcd3f6a54c0661cde9068d...
50,TCP_IP-DoS-UDP4_train.pcap.csv,38.090,69f2d5223a1ad1bdbd50cedd4133697bd097b3a2ce66d8...

================================================================================
3. PARTITION AUDIT
================================================================================
Partitioned dataset shape: (7160827, 49)

Partition counts:

               records
partition
calibration    1408617
development    4449176
internal_test  1303034

development     | Expected=4,449,176 | Actual=4,449,176 | PASS
calibration     | Expected=1,408,617 | Actual=1,408,617 | PASS

================================================================================
4. CAPTURE ASSIGNMENT AUDIT
================================================================================
Capture assignment rows: 49

        partition   attack_family  captures
0     calibration            MQTT         1
1     calibration  Reconnaissance         1
2     calibration     TCP/IP DDoS         5
3     calibration      TCP/IP DoS         3
4     development            MQTT         3
5     development  Reconnaissance         2
6     development     TCP/IP DDoS        14
7     development      TCP/IP DoS        10
8   internal_test            MQTT         1
9   internal_test  Reconnaissance         1
10  internal_test     TCP/IP DDoS         5
11  internal_test      TCP/IP DoS         3

Duplicate capture assignments: 0

================================================================================
5. FINAL TEST POPULATION
================================================================================
Test prediction shape: (1342385, 14)

TOTAL TEST RECORDS = 1,342,385

Test source distribution:

  test_source  records
0    Internal  1303034
1    External    39351

Label distribution:

       records
label
0        37607
1      1304778

Attack-family distribution:

   label   attack_family  records
0      0          Benign    37607
4      1     TCP/IP DDoS   995670
5      1      TCP/IP DoS   300061
2      1            MQTT     5130
3      1  Reconnaissance     2173
1      1    ARP Spoofing     1744

================================================================================
6. PREDICTION COLUMN AUDIT
================================================================================
PASS  | test_source
PASS  | source_file
PASS  | label
PASS  | attack_family
PASS  | xgb_score
PASS  | ae_score
PASS  | xgb_percentile
PASS  | ae_percentile
PASS  | hybrid_max_score
PASS  | hybrid_average_score
PASS  | XGBoost_prediction
PASS  | Autoencoder_prediction
PASS  | Hybrid_Max_prediction
PASS  | Hybrid_Average_prediction

================================================================================
7. FINAL DETECTION THRESHOLDS
================================================================================
XGBoost            = 0.340408
Hybrid_Max         = 0.99488936
Hybrid_Average     = 0.94991439
Autoencoder        = 0.3691655993461609

================================================================================
8. INDEPENDENT RECONSTRUCTION OF FINAL TEST METRICS
================================================================================

================================================================================
9. CONFUSION MATRIX RECONCILIATION
================================================================================
XGBoost            | TN+FP+FN+TP=1,342,385 | Test=1,342,385 | PASS
Autoencoder        | TN+FP+FN+TP=1,342,385 | Test=1,342,385 | PASS
Hybrid_Max         | TN+FP+FN+TP=1,342,385 | Test=1,342,385 | PASS
Hybrid_Average     | TN+FP+FN+TP=1,342,385 | Test=1,342,385 | PASS

================================================================================
10. PREDICTION VALIDITY CHECKS
================================================================================
XGBoost            | binary=True | missing scores=0
Autoencoder        | binary=True | missing scores=0
Hybrid_Max         | binary=True | missing scores=0
Hybrid_Average     | binary=True | missing scores=0

================================================================================
11. ADAPTIVE TRUST MANAGEMENT
================================================================================
Trust prediction rows: 1342385

Trust columns:
['source_file', 'label', 'score', 'trust_score', 'detector_flag', 'trust_state', 'test_source']

Selected configuration:
Decay           : 0.1
Recovery        : 0.02
Alert threshold : 0.5
Block threshold : 0.3

Overall trust-state distribution:

  trust_state  records  percentage
0       BLOCK  1309223   97.529621
1        SAFE    32851    2.447211
2     MONITOR      254    0.018922
3       ALERT       57    0.004246

Trust states by actual class:

   label trust_state  records  percentage_within_label
0      0       ALERT       35                 0.093068
1      0       BLOCK     4526                12.034993
2      0     MONITOR      199                 0.529157
3      0        SAFE    32847                87.342782
4      1       ALERT       22                 0.001686
5      1       BLOCK  1304697                99.993792
6      1     MONITOR       55                 0.004215
7      1        SAFE        4                 0.000307

================================================================================
12. BLOCKCHAIN / HASH-LINKED LEDGER
================================================================================
Ledger events: 1342385
Ledger blocks: 1343

Ledger event structure:
['source_file', 'test_source', 'score', 'trust_score', 'detector_flag', 'trust_state', 'sequence_id', 'event_hash']
Sequence integrity: PASS
Duplicate event hashes: 0

================================================================================
13. SHA-256 EVENT HASH VERIFICATION
================================================================================
Matching event hashes: 1,342,385/1,342,385
Event hash integrity: PASS

================================================================================
14. MERKLE ROOT AND BLOCK HASH VERIFICATION
================================================================================
Block/Merkle integrity: PASS
Verified blocks: 1,343

================================================================================
15. LEDGER STORAGE INFORMATION
================================================================================
Audit event ledger size: 173.109 MB
Blockchain manifest size: 0.280 MB

================================================================================
16. MODEL ARTIFACT VERIFICATION
================================================================================
PASS | WEAR_CHAIN_XGBoost_baseline.pkl               | 0.884 MB
PASS | WEAR_CHAIN_autoencoder.keras                  | 0.090 MB
PASS | WEAR_CHAIN_autoencoder_scaler.pkl             | 0.002 MB

================================================================================
17. FINAL DATASET VALUES
================================================================================
raw_training_rows             : 7,160,831
clean_training_rows           : 7,160,827
excluded_malformed_rows       : 4
raw_capture_count             : 51
model_feature_count           : 44
development_rows              : 4,449,176
calibration_rows              : 1,408,617
unseen_test_rows              : 1,342,385

================================================================================
18. FINAL MODEL SUMMARY
================================================================================

,model,records,accuracy,precision,recall,f1,FPR,FNR,TN,FP,FN,TP
0,XGBoost,1342385,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,35984,1623,1086,1303692
1,Autoencoder,1342385,0.993337,0.999123,0.994018,0.996564,0.030287,0.005982,36468,1139,7805,1296973
2,Hybrid_Max,1342385,0.997937,0.998984,0.998894,0.998939,0.035259,0.001106,36281,1326,1443,1303335
3,Hybrid_Average,1342385,0.995556,0.998835,0.996589,0.997711,0.040312,0.003411,36091,1516,4450,1300328

================================================================================
19. PAPER-READY VALUES
================================================================================

,section,metric,value,source
0,Dataset,Raw training captures,51,WEAR_CHAIN_FINAL_raw_capture_inventory.csv
1,Dataset,raw_training_rows,7160831,Executed Kaggle experiment / audit records
2,Dataset,clean_training_rows,7160827,Executed Kaggle experiment / audit records
3,Dataset,excluded_malformed_rows,4,Executed Kaggle experiment / audit records
4,Dataset,raw_capture_count,51,Executed Kaggle experiment / audit records
...,...,...,...,...
103,Blockchain Ledger,Audit event file size MB,173.109,WEAR_CHAIN_21_audit_events.csv
104,Blockchain Ledger,Blockchain manifest size MB,0.28,WEAR_CHAIN_21_blockchain_manifest.csv
105,Model Artifacts,WEAR_CHAIN_XGBoost_baseline.pkl,True,0.884 MB
106,Model Artifacts,WEAR_CHAIN_autoencoder.keras,True,0.090 MB
107,Model Artifacts,WEAR_CHAIN_autoencoder_scaler.pkl,True,0.002 MB

================================================================================
20. FINAL AUDIT STATUS
================================================================================
PASS   : 52
REVIEW : 0
FAIL   : 0

FINAL STATUS: PASS

================================================================================
FINAL OUTPUT FILES
================================================================================
PASS | WEAR_CHAIN_FINAL_test_metrics.csv                       | 0.001 MB
PASS | WEAR_CHAIN_FINAL_PAPER_VALUES.csv                       | 0.010 MB
PASS | WEAR_CHAIN_FINAL_PAPER_VALUES.json                      | 0.015 MB
PASS | WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv                       | 0.003 MB
PASS | WEAR_CHAIN_FINAL_artifact_inventory.csv                 | 0.002 MB
PASS | WEAR_CHAIN_FINAL_raw_capture_inventory.csv              | 0.005 MB
PASS | WEAR_CHAIN_FINAL_test_family_counts.csv                 | 0.000 MB
PASS | WEAR_CHAIN_FINAL_trust_state_counts.csv                 | 0.000 MB
PASS | WEAR_CHAIN_FINAL_trust_by_label.csv                     | 0.000 MB

================================================================================
WEAR-CHAIN FINAL EXTRACTION COMPLETE
================================================================================

IMPORTANT:
These outputs are extracted/reconstructed from the existing Kaggle
experiment. No model was retrained and no threshold was changed.

The most important files for the paper are:

1. WEAR_CHAIN_FINAL_test_metrics.csv
2. WEAR_CHAIN_FINAL_PAPER_VALUES.csv
3. WEAR_CHAIN_FINAL_PAPER_VALUES.json
4. WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv

Do not mix these values with the later Colab experiment.

In [26]:
# ============================================================
# WEAR-CHAIN — PUBLICATION-GRADE KAGGLE ANALYSIS
# ============================================================
# IMPORTANT:
# - KAGGLE ONLY
# - NO MODEL RETRAINING
# - NO THRESHOLD CHANGES TO THE FROZEN MAIN RESULTS
# - USES EXISTING FROZEN TEST PREDICTIONS / TRUST / LEDGER FILES
# - OPTIMIZED FOR 1.34M+ TEST RECORDS
#
# Outputs:
#   1. Threshold sensitivity
#   2. ROC curve data
#   3. Precision-Recall curve data
#   4. Bootstrap 95% CIs
#   5. Paired error analysis
#   6. Test-set class distribution
#   7. Per-source/capture analysis
#   8. Genuine 18-configuration trust sensitivity
#   9. Trust-state summary
#  10. Blockchain structural audit
#  11. Controlled ledger tamper checks
#  12. Master publication evidence index
# ============================================================


# ============================================================
# 0. IMPORTS
# ============================================================

import os
import json
import math
import hashlib
import shutil
import time

import numpy as np
import pandas as pd

from pathlib import Path

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    roc_curve,
    precision_recall_curve,
    confusion_matrix
)


# ============================================================
# CONFIGURATION
# ============================================================

WORK = Path("/kaggle/working")

OUT = WORK / "WEAR_CHAIN_PUBLICATION_ANALYSIS"
OUT.mkdir(exist_ok=True)

PRED_FILE = WORK / "WEAR_CHAIN_unseen_test_predictions.csv"
TRUST_FILE = WORK / "WEAR_CHAIN_20_trust_test_predictions.csv"
MANIFEST_FILE = WORK / "WEAR_CHAIN_21_blockchain_manifest.csv"
AUDIT_EVENT_FILE = WORK / "WEAR_CHAIN_21_audit_events.csv"

assert PRED_FILE.exists(), (
    f"Missing required prediction file:\n{PRED_FILE}"
)

print("=" * 90)
print("WEAR-CHAIN — PUBLICATION-GRADE KAGGLE ANALYSIS")
print("=" * 90)
print("NO MODEL RETRAINING")
print("FROZEN KAGGLE TEST PREDICTIONS")
print("Optimized for large test population")
print("=" * 90)


# ============================================================
# LOAD FROZEN TEST PREDICTIONS
# ============================================================

print("\nLoading frozen test predictions...")

df = pd.read_csv(PRED_FILE)

print(f"Prediction rows: {len(df):,}")
print(f"Prediction file: {PRED_FILE}")

print("\nPrediction columns:")
for c in df.columns:
    print("   ", c)


# ============================================================
# HELPER — COLUMN DISCOVERY
# ============================================================

def find_column(candidates, dataframe=df):

    for c in candidates:
        if c in dataframe.columns:
            return c

    return None


# ============================================================
# GROUND-TRUTH LABEL
# ============================================================

LABEL_COL = find_column([
    "label",
    "Label",
    "target",
    "Target",
    "y_true",
    "true_label"
])

assert LABEL_COL is not None, (
    "Could not identify ground-truth label column."
)

y = pd.to_numeric(
    df[LABEL_COL],
    errors="coerce"
).fillna(0).astype(np.int8).to_numpy()

print("\nGround-truth column:", LABEL_COL)

class_counts_raw = pd.Series(y).value_counts().sort_index()

print("\nGround-truth distribution:")
print(class_counts_raw)


# ============================================================
# DETECTOR COLUMN DISCOVERY
# ============================================================

MODEL_INFO = {

    "XGBoost": {

        "score_candidates": [
            "XGBoost_score",
            "XGBoost_probability",
            "XGBoost_prob",
            "xgb_score",
            "xgb_probability"
        ],

        "pred_candidates": [
            "XGBoost_prediction",
            "XGBoost_pred",
            "xgb_prediction"
        ]
    },

    "Autoencoder": {

        "score_candidates": [
            "Autoencoder_score",
            "Autoencoder_anomaly_score",
            "ae_score",
            "autoencoder_score"
        ],

        "pred_candidates": [
            "Autoencoder_prediction",
            "Autoencoder_pred",
            "ae_prediction"
        ]
    },

    "Hybrid_Max": {

        "score_candidates": [
            "Hybrid_Max_score",
            "Hybrid_Max",
            "hybrid_max_score"
        ],

        "pred_candidates": [
            "Hybrid_Max_prediction",
            "Hybrid_Max_pred"
        ]
    },

    "Hybrid_Average": {

        "score_candidates": [
            "Hybrid_Average_score",
            "Hybrid_Average",
            "hybrid_average_score"
        ],

        "pred_candidates": [
            "Hybrid_Average_prediction",
            "Hybrid_Average_pred"
        ]
    }
}


models = {}


for name, info in MODEL_INFO.items():

    score_col = next(
        (
            c for c in info["score_candidates"]
            if c in df.columns
        ),
        None
    )

    pred_col = next(
        (
            c for c in info["pred_candidates"]
            if c in df.columns
        ),
        None
    )

    if score_col is not None:

        models[name] = {
            "score_col": score_col,
            "score": pd.to_numeric(
                df[score_col],
                errors="coerce"
            ).to_numpy(dtype=np.float64)
        }

    if pred_col is not None:

        if name not in models:
            models[name] = {}

        models[name]["pred_col"] = pred_col

        models[name]["pred"] = (
            pd.to_numeric(
                df[pred_col],
                errors="coerce"
            )
            .fillna(0)
            .astype(np.int8)
            .to_numpy()
        )


print("\nDetected models:")

for name, info in models.items():

    print(
        f"{name:20s} "
        f"score={info.get('score_col')} "
        f"prediction={info.get('pred_col')}"
    )


assert len(models) > 0, "No detector columns were identified."


# ============================================================
# COMMON METRIC FUNCTION
# ============================================================

def calculate_metrics(y_true, y_pred):

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    accuracy = (
        (tp + tn) /
        (tp + tn + fp + fn)
    )

    precision = (
        tp / (tp + fp)
        if (tp + fp) else 0
    )

    recall = (
        tp / (tp + fn)
        if (tp + fn) else 0
    )

    f1 = (
        2 * precision * recall /
        (precision + recall)
        if (precision + recall) else 0
    )

    fpr = (
        fp / (fp + tn)
        if (fp + tn) else 0
    )

    fnr = (
        fn / (fn + tp)
        if (fn + tp) else 0
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "FPR": fpr,
        "FNR": fnr,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    }


# ============================================================
# 1. THRESHOLD SENSITIVITY
# ============================================================

print("\n" + "=" * 90)
print("1. FAST THRESHOLD SENSITIVITY")
print("=" * 90)

thresholds = np.unique(
    np.concatenate([
        np.arange(0.00, 0.91, 0.01),
        np.arange(0.91, 0.991, 0.005),
        np.arange(0.991, 1.001, 0.001)
    ])
)

threshold_rows = []


for model_name, info in models.items():

    if "score" not in info:
        print(
            f"Skipping {model_name}: "
            "score unavailable."
        )
        continue

    score = np.asarray(
        info["score"],
        dtype=np.float64
    )

    valid = np.isfinite(score)

    if not valid.all():

        print(
            f"Skipping {model_name}: "
            f"{(~valid).sum():,} invalid scores."
        )

        continue

    score_min = score.min()
    score_max = score.max()

    print(
        f"\n{model_name}: "
        f"score range = "
        f"{score_min:.6f} → {score_max:.6f}"
    )

    # Probability-like score only.
    if score_min < 0 or score_max > 1:

        print(
            f"Skipping threshold sweep for "
            f"{model_name}: not in [0,1]."
        )

        continue

    # Sort ONCE.
    order = np.argsort(score)

    sorted_scores = score[order]
    sorted_y = y[order]

    total_pos = int((y == 1).sum())
    total_neg = int((y == 0).sum())

    for t in thresholds:

        idx = np.searchsorted(
            sorted_scores,
            t,
            side="left"
        )

        # Scores >= threshold are attacks.
        attack_y = sorted_y[idx:]

        tp = int((attack_y == 1).sum())
        fp = int((attack_y == 0).sum())

        fn = total_pos - tp
        tn = total_neg - fp

        precision = (
            tp / (tp + fp)
            if (tp + fp) else 0
        )

        recall = (
            tp / (tp + fn)
            if (tp + fn) else 0
        )

        f1 = (
            2 * precision * recall /
            (precision + recall)
            if (precision + recall)
            else 0
        )

        fpr = (
            fp / (fp + tn)
            if (fp + tn)
            else 0
        )

        fnr = (
            fn / (fn + tp)
            if (fn + tp)
            else 0
        )

        threshold_rows.append({

            "model": model_name,

            "threshold": float(t),

            "precision": precision,

            "recall": recall,

            "f1": f1,

            "FPR": fpr,

            "FNR": fnr,

            "TN": tn,

            "FP": fp,

            "FN": fn,

            "TP": tp
        })


threshold_df = pd.DataFrame(
    threshold_rows
)

threshold_df.to_csv(
    OUT / "WEAR_CHAIN_threshold_sensitivity.csv",
    index=False
)

print(
    f"\nThreshold analysis complete:"
    f" {len(threshold_df):,} rows"
)


# ============================================================
# 2. ROC / PR CURVE DATA
# ============================================================

print("\n" + "=" * 90)
print("2. ROC / PRECISION-RECALL CURVE DATA")
print("=" * 90)

roc_rows = []
pr_rows = []

auc_rows = []


for model_name, info in models.items():

    if "score" not in info:
        continue

    score = np.asarray(
        info["score"],
        dtype=np.float64
    )

    if not np.isfinite(score).all():

        print(
            f"Skipping {model_name}: "
            "invalid score values."
        )

        continue

    print(f"Processing {model_name}...")


    # -----------------------------
    # ROC
    # -----------------------------

    try:

        fpr, tpr, roc_thresholds = roc_curve(
            y,
            score
        )

        for a, b, c in zip(
            fpr,
            tpr,
            roc_thresholds
        ):

            roc_rows.append({
                "model": model_name,
                "FPR": a,
                "TPR": b,
                "threshold": c
            })

        roc_auc = roc_auc_score(
            y,
            score
        )

    except Exception as e:

        print(
            f"ROC error for {model_name}: {e}"
        )

        roc_auc = np.nan


    # -----------------------------
    # PRECISION-RECALL
    # -----------------------------

    try:

        precision, recall, pr_thresholds = (
            precision_recall_curve(
                y,
                score
            )
        )

        for i in range(len(precision)):

            threshold = (
                pr_thresholds[i]
                if i < len(pr_thresholds)
                else np.nan
            )

            pr_rows.append({

                "model": model_name,

                "precision": precision[i],

                "recall": recall[i],

                "threshold": threshold
            })

        pr_auc = average_precision_score(
            y,
            score
        )

    except Exception as e:

        print(
            f"PR error for {model_name}: {e}"
        )

        pr_auc = np.nan


    auc_rows.append({

        "model": model_name,

        "ROC_AUC": roc_auc,

        "PR_AUC": pr_auc
    })


pd.DataFrame(roc_rows).to_csv(
    OUT / "WEAR_CHAIN_ROC_curve_data.csv",
    index=False
)

pd.DataFrame(pr_rows).to_csv(
    OUT / "WEAR_CHAIN_PR_curve_data.csv",
    index=False
)

auc_df = pd.DataFrame(auc_rows)

auc_df.to_csv(
    OUT / "WEAR_CHAIN_AUC_summary.csv",
    index=False
)

print("\nAUC summary:")
print(auc_df.to_string(index=False))


# ============================================================
# 3. OPTIMIZED BOOTSTRAP 95% CONFIDENCE INTERVALS
# ============================================================

print("\n" + "=" * 90)
print("3. OPTIMIZED BOOTSTRAP 95% CONFIDENCE INTERVALS")
print("=" * 90)

N_BOOT = 1000

bootstrap_rows = []


def bootstrap_confusion_metrics(
    y_true,
    y_pred,
    n_boot=1000,
    seed=42
):

    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()

    n = (
        tn +
        fp +
        fn +
        tp
    )

    probs = np.array([
        tn,
        fp,
        fn,
        tp
    ], dtype=np.float64) / n

    rng_local = np.random.default_rng(
        seed
    )

    boot_counts = rng_local.multinomial(
        n,
        probs,
        size=n_boot
    )

    TN = boot_counts[:, 0]
    FP = boot_counts[:, 1]
    FN = boot_counts[:, 2]
    TP = boot_counts[:, 3]

    accuracy = (
        (TP + TN) / n
    )

    precision = np.divide(
        TP,
        TP + FP,
        out=np.zeros_like(
            TP,
            dtype=float
        ),
        where=(TP + FP) != 0
    )

    recall = np.divide(
        TP,
        TP + FN,
        out=np.zeros_like(
            TP,
            dtype=float
        ),
        where=(TP + FN) != 0
    )

    f1 = np.divide(
        2 * precision * recall,
        precision + recall,
        out=np.zeros_like(
            precision,
            dtype=float
        ),
        where=(precision + recall) != 0
    )

    fpr = np.divide(
        FP,
        FP + TN,
        out=np.zeros_like(
            FP,
            dtype=float
        ),
        where=(FP + TN) != 0
    )

    fnr = np.divide(
        FN,
        FN + TP,
        out=np.zeros_like(
            FN,
            dtype=float
        ),
        where=(FN + TP) != 0
    )

    return {

        "accuracy": accuracy,

        "precision": precision,

        "recall": recall,

        "f1": f1,

        "FPR": fpr,

        "FNR": fnr
    }


for model_name, info in models.items():

    if "pred" not in info:

        print(
            f"Skipping {model_name}: "
            "prediction unavailable."
        )

        continue

    print(
        f"Bootstrapping {model_name}..."
    )

    values = bootstrap_confusion_metrics(
        y,
        info["pred"],
        n_boot=N_BOOT,
        seed=42
    )

    for metric, vals in values.items():

        vals = np.asarray(vals)

        bootstrap_rows.append({

            "model": model_name,

            "metric": metric,

            "estimate": float(
                np.mean(vals)
            ),

            "CI_2.5": float(
                np.percentile(
                    vals,
                    2.5
                )
            ),

            "CI_97.5": float(
                np.percentile(
                    vals,
                    97.5
                )
            )
        })


bootstrap_df = pd.DataFrame(
    bootstrap_rows
)

bootstrap_df.to_csv(
    OUT / "WEAR_CHAIN_bootstrap_95CI.csv",
    index=False
)

print(
    "\nBootstrap complete."
)

print(
    bootstrap_df.to_string(
        index=False
    )
)


# ============================================================
# 4. PAIRED ERROR ANALYSIS
# ============================================================

print("\n" + "=" * 90)
print("4. PAIRED ERROR ANALYSIS")
print("=" * 90)

error_rows = []

model_names = [
    name
    for name, info in models.items()
    if "pred" in info
]


for i in range(
    len(model_names)
):

    for j in range(
        i + 1,
        len(model_names)
    ):

        a = model_names[i]
        b = model_names[j]

        pa = models[a]["pred"]
        pb = models[b]["pred"]

        a_correct = (
            pa == y
        )

        b_correct = (
            pb == y
        )

        both_correct = int(
            np.sum(
                a_correct &
                b_correct
            )
        )

        both_wrong = int(
            np.sum(
                (~a_correct) &
                (~b_correct)
            )
        )

        a_only_correct = int(
            np.sum(
                a_correct &
                (~b_correct)
            )
        )

        b_only_correct = int(
            np.sum(
                (~a_correct) &
                b_correct
            )
        )

        disagreement = (
            a_only_correct +
            b_only_correct
        )

        error_rows.append({

            "model_A": a,

            "model_B": b,

            "both_correct": both_correct,

            "both_wrong": both_wrong,

            "A_only_correct":
                a_only_correct,

            "B_only_correct":
                b_only_correct,

            "disagreement":
                disagreement
        })


paired_error_df = pd.DataFrame(
    error_rows
)

paired_error_df.to_csv(
    OUT /
    "WEAR_CHAIN_paired_error_analysis.csv",
    index=False
)

print(
    paired_error_df.to_string(
        index=False
    )
)


# ============================================================
# 5. TEST-SET CLASS DISTRIBUTION
# ============================================================

print("\n" + "=" * 90)
print("5. TEST-SET CLASS DISTRIBUTION")
print("=" * 90)

class_counts = (

    pd.Series(y)

    .value_counts()

    .sort_index()

    .rename_axis("label")

    .reset_index(
        name="records"
    )
)

class_counts["percentage"] = (

    class_counts["records"]

    / len(y)

    * 100
)

class_counts.to_csv(
    OUT /
    "WEAR_CHAIN_test_class_distribution.csv",
    index=False
)

print(
    class_counts.to_string(
        index=False
    )
)


# ============================================================
# 6. PER-SOURCE / CAPTURE ANALYSIS
# ============================================================

print("\n" + "=" * 90)
print("6. SOURCE / CAPTURE ANALYSIS")
print("=" * 90)

SOURCE_COL = None

for c in [
    "source_file",
    "Source",
    "source",
    "test_source",
    "capture",
    "capture_id"
]:

    if c in df.columns:

        SOURCE_COL = c

        break


if SOURCE_COL is not None:

    print(
        f"Using source column: "
        f"{SOURCE_COL}"
    )

    source_rows = []

    for source, g in df.groupby(
        SOURCE_COL,
        sort=False
    ):

        yy = pd.to_numeric(
            g[LABEL_COL],
            errors="coerce"
        ).fillna(0).astype(
            np.int8
        ).to_numpy()

        row = {

            "source": source,

            "records": len(g),

            "benign": int(
                (yy == 0).sum()
            ),

            "attack": int(
                (yy == 1).sum()
            )
        }


        for model_name, info in models.items():

            if "pred_col" not in info:
                continue

            pred = pd.to_numeric(
                g[info["pred_col"]],
                errors="coerce"
            ).fillna(0).astype(
                np.int8
            ).to_numpy()

            row[
                f"{model_name}_accuracy"
            ] = accuracy_score(
                yy,
                pred
            )

            row[
                f"{model_name}_precision"
            ] = precision_score(
                yy,
                pred,
                zero_division=0
            )

            row[
                f"{model_name}_recall"
            ] = (
                recall_score(
                    yy,
                    pred,
                    zero_division=0
                )
                if (yy == 1).sum()
                else np.nan
            )

            row[
                f"{model_name}_f1"
            ] = f1_score(
                yy,
                pred,
                zero_division=0
            )


        source_rows.append(row)


    source_df = pd.DataFrame(
        source_rows
    )

    source_df.to_csv(
        OUT /
        "WEAR_CHAIN_per_source_results.csv",
        index=False
    )

    print(
        source_df.to_string(
            index=False
        )
    )

else:

    print(
        "No source/capture column found."
    )

    print(
        "Per-source analysis skipped."
    )


# ============================================================
# 7. GENUINE TRUST SENSITIVITY ANALYSIS
# ============================================================
#
# IMPORTANT:
# The previous code only created a table containing
# the 18 configurations.
#
# This version actually replays the trust state machine
# for all 18 combinations using the frozen XGBoost score.
#
# NO MODEL RETRAINING.
# ============================================================

print("\n" + "=" * 90)
print("7. TRUST SENSITIVITY — 18 CONFIGURATIONS")
print("=" * 90)


# ------------------------------------------------------------
# Find XGBoost score
# ------------------------------------------------------------

xgb_score = None

for candidate in [
    "xgb_score",
    "XGBoost_score",
    "XGBoost_probability",
    "XGBoost_prob"
]:

    if candidate in df.columns:

        xgb_score = pd.to_numeric(
            df[candidate],
            errors="coerce"
        ).to_numpy(
            dtype=np.float64
        )

        print(
            "Trust replay score column:",
            candidate
        )

        break


if xgb_score is None:

    print(
        "WARNING: XGBoost score not found."
    )

    print(
        "Trust sensitivity replay skipped."
    )

    trust_sensitivity_df = pd.DataFrame()

else:

    # --------------------------------------------------------
    # Trust configuration
    # --------------------------------------------------------

    decay_values = [
        0.02,
        0.05,
        0.10
    ]

    recovery_values = [
        0.02,
        0.05
    ]

    block_threshold_values = [
        0.10,
        0.20,
        0.30
    ]


    trust_rows = []


    # --------------------------------------------------------
    # Trust state replay
    # --------------------------------------------------------

    def replay_trust(
        scores,
        y_true,
        decay,
        recovery,
        block_threshold
    ):

        # Start at neutral trust.
        trust = 0.5

        states = []

        for score in scores:

            # ----------------------------------------------
            # Detector-driven adaptive trust
            # ----------------------------------------------

            if score >= block_threshold:

                trust = max(
                    0.0,
                    trust - decay
                )

            else:

                trust = min(
                    1.0,
                    trust + recovery
                )


            # ----------------------------------------------
            # Map trust to state
            #
            # SAFE:
            # trust >= 0.70
            #
            # MONITOR:
            # 0.40 <= trust < 0.70
            #
            # ALERT:
            # 0.30 <= trust < 0.40
            #
            # BLOCK:
            # trust < 0.30
            # ----------------------------------------------

            if trust < 0.30:

                state = "BLOCK"

            elif trust < 0.40:

                state = "ALERT"

            elif trust < 0.70:

                state = "MONITOR"

            else:

                state = "SAFE"


            states.append(state)


        states = np.asarray(
            states,
            dtype=object
        )


        # ----------------------------------------------------
        # State counts
        # ----------------------------------------------------

        total = len(states)

        block_count = int(
            np.sum(states == "BLOCK")
        )

        alert_count = int(
            np.sum(states == "ALERT")
        )

        monitor_count = int(
            np.sum(states == "MONITOR")
        )

        safe_count = int(
            np.sum(states == "SAFE")
        )


        # ----------------------------------------------------
        # Attack / benign state behavior
        # ----------------------------------------------------

        attack_mask = (
            y_true == 1
        )

        benign_mask = (
            y_true == 0
        )


        attack_block_rate = (

            np.mean(
                states[attack_mask] ==
                "BLOCK"
            )

            if attack_mask.any()

            else np.nan
        )


        benign_block_rate = (

            np.mean(
                states[benign_mask] ==
                "BLOCK"
            )

            if benign_mask.any()

            else np.nan
        )


        # ----------------------------------------------------
        # Overall block rate
        # ----------------------------------------------------

        block_rate = (
            block_count / total
        )


        return {

            "decay": decay,

            "recovery": recovery,

            "block_threshold":
                block_threshold,

            "total_records":
                total,

            "SAFE":
                safe_count,

            "MONITOR":
                monitor_count,

            "ALERT":
                alert_count,

            "BLOCK":
                block_count,

            "safe_rate":
                safe_count / total,

            "monitor_rate":
                monitor_count / total,

            "alert_rate":
                alert_count / total,

            "block_rate":
                block_rate,

            "attack_block_rate":
                attack_block_rate,

            "benign_block_rate":
                benign_block_rate
        }


    # --------------------------------------------------------
    # Evaluate all 18 combinations
    # --------------------------------------------------------

    config_number = 0

    for decay in decay_values:

        for recovery in recovery_values:

            for block_threshold in (
                block_threshold_values
            ):

                config_number += 1

                print(
                    f"Trust configuration "
                    f"{config_number}/18: "
                    f"decay={decay}, "
                    f"recovery={recovery}, "
                    f"block_threshold="
                    f"{block_threshold}"
                )

                result = replay_trust(

                    xgb_score,

                    y,

                    decay,

                    recovery,

                    block_threshold
                )

                result[
                    "configuration"
                ] = config_number

                trust_rows.append(
                    result
                )


    trust_sensitivity_df = pd.DataFrame(
        trust_rows
    )


    # Put configuration first.
    cols = [
        "configuration",
        "decay",
        "recovery",
        "block_threshold",
        "total_records",
        "SAFE",
        "MONITOR",
        "ALERT",
        "BLOCK",
        "safe_rate",
        "monitor_rate",
        "alert_rate",
        "block_rate",
        "attack_block_rate",
        "benign_block_rate"
    ]

    trust_sensitivity_df = (
        trust_sensitivity_df[cols]
    )


    trust_sensitivity_df.to_csv(
        OUT /
        "WEAR_CHAIN_trust_sensitivity_18_configs.csv",
        index=False
    )


    print(
        "\n18-configuration trust sensitivity:"
    )

    print(
        trust_sensitivity_df.to_string(
            index=False
        )
    )


    # --------------------------------------------------------
    # Mark configurations satisfying the original criterion
    #
    # Original criterion:
    # calibration benign block rate <= 1%
    #
    # NOTE:
    # This test-set replay cannot reproduce the original
    # calibration selection criterion unless calibration
    # predictions are available in this analysis.
    #
    # Therefore this column is informational only.
    # --------------------------------------------------------

    trust_sensitivity_df[
        "test_benign_block_rate_le_1pct"
    ] = (

        trust_sensitivity_df[
            "benign_block_rate"
        ] <= 0.01
    )


    trust_sensitivity_df.to_csv(
        OUT /
        "WEAR_CHAIN_trust_sensitivity_18_configs.csv",
        index=False
    )


# ============================================================
# 8. TRUST TEST-STATE SUMMARY
# ============================================================

print("\n" + "=" * 90)
print("8. EXISTING TRUST TEST-STATE SUMMARY")
print("=" * 90)


if TRUST_FILE.exists():

    trust = pd.read_csv(
        TRUST_FILE
    )

    print(
        f"Trust records: "
        f"{len(trust):,}"
    )


    if "trust_state" in trust.columns:

        trust_summary = (

            trust["trust_state"]

            .value_counts()

            .rename_axis(
                "trust_state"
            )

            .reset_index(
                name="records"
            )
        )

        trust_summary[
            "percentage"
        ] = (

            trust_summary[
                "records"
            ]

            / len(trust)

            * 100
        )


        trust_summary.to_csv(
            OUT /
            "WEAR_CHAIN_trust_state_summary.csv",
            index=False
        )


        print(
            "\nTrust state distribution:"
        )

        print(
            trust_summary.to_string(
                index=False
            )
        )


        # -----------------------------------------------
        # State by true label
        # -----------------------------------------------

        if "label" in trust.columns:

            trust_label = pd.crosstab(
                trust["label"],
                trust["trust_state"]
            )

            trust_label.to_csv(
                OUT /
                "WEAR_CHAIN_trust_by_true_label.csv"
            )

            print(
                "\nTrust by true label:"
            )

            print(
                trust_label.to_string()
            )

else:

    print(
        "Existing trust prediction file not found."
    )


# ============================================================
# 9. BLOCKCHAIN STRUCTURAL AUDIT
# ============================================================

print("\n" + "=" * 90)
print("9. BLOCKCHAIN STRUCTURAL AUDIT")
print("=" * 90)


if MANIFEST_FILE.exists():

    manifest = pd.read_csv(
        MANIFEST_FILE
    )

    checks = {}


    # --------------------------------------------------------
    # Block count
    # --------------------------------------------------------

    checks[
        "block_count"
    ] = len(manifest)


    # --------------------------------------------------------
    # Sequence begins at 1
    # --------------------------------------------------------

    checks[
        "sequence_starts_at_1"
    ] = (

        int(
            manifest.iloc[0][
                "start_sequence"
            ]
        ) == 1
    )


    # --------------------------------------------------------
    # Sequence continuity
    # --------------------------------------------------------

    sequences_contiguous = True

    for i in range(
        1,
        len(manifest)
    ):

        previous_end = int(
            manifest.iloc[
                i - 1
            ][
                "end_sequence"
            ]
        )

        current_start = int(
            manifest.iloc[
                i
            ][
                "start_sequence"
            ]
        )

        if current_start != (
            previous_end + 1
        ):

            sequences_contiguous = False

            break


    checks[
        "sequences_contiguous"
    ] = sequences_contiguous


    # --------------------------------------------------------
    # Block numbers contiguous
    # --------------------------------------------------------

    checks[
        "block_numbers_contiguous"
    ] = (

        manifest[
            "block_number"
        ]
        .astype(int)
        .tolist()

        ==

        list(
            range(
                1,
                len(manifest) + 1
            )
        )
    )


    # --------------------------------------------------------
    # Event counts match ranges
    # --------------------------------------------------------

    checks[
        "event_counts_match_ranges"
    ] = (

        manifest[
            "event_count"
        ].astype(int)

        ==

        (
            manifest[
                "end_sequence"
            ].astype(int)

            -

            manifest[
                "start_sequence"
            ].astype(int)

            + 1
        )
    ).all()


    # --------------------------------------------------------
    # Total events
    # --------------------------------------------------------

    checks[
        "total_events"
    ] = int(
        manifest[
            "event_count"
        ].sum()
    )


    checks[
        "expected_total_events"
    ] = len(df)


    checks[
        "event_count_matches_test"
    ] = (

        checks[
            "total_events"
        ]

        ==

        len(df)
    )


    # --------------------------------------------------------
    # Previous-block hash chain
    # --------------------------------------------------------

    previous_hash_chain_valid = True

    for i in range(
        1,
        len(manifest)
    ):

        expected_previous = (
            manifest.iloc[
                i - 1
            ][
                "block_hash"
            ]
        )

        actual_previous = (
            manifest.iloc[
                i
            ][
                "previous_block_hash"
            ]
        )

        if (
            expected_previous
            !=
            actual_previous
        ):

            previous_hash_chain_valid = False

            break


    checks[
        "previous_hash_chain_valid"
    ] = previous_hash_chain_valid


    blockchain_audit_df = pd.DataFrame(
        list(
            checks.items()
        ),
        columns=[
            "check",
            "value"
        ]
    )


    blockchain_audit_df.to_csv(
        OUT /
        "WEAR_CHAIN_blockchain_structural_audit.csv",
        index=False
    )


    print(
        blockchain_audit_df.to_string(
            index=False
        )
    )

else:

    print(
        "Blockchain manifest not found."
    )


# ============================================================
# 10. CONTROLLED BLOCKCHAIN TAMPER-DETECTION TEST
# ============================================================
#
# This test does NOT modify the original ledger.
#
# It creates temporary copies in memory and changes:
#   A. one event hash
#   B. one block hash
#   C. one previous-block hash
#
# Then checks whether the integrity verification detects it.
# ============================================================

print("\n" + "=" * 90)
print("10. CONTROLLED BLOCKCHAIN TAMPER-DETECTION TEST")
print("=" * 90)


tamper_rows = []


if MANIFEST_FILE.exists():

    original_manifest = pd.read_csv(
        MANIFEST_FILE
    )


    # --------------------------------------------------------
    # Test A — tamper with block hash
    # --------------------------------------------------------

    tampered = original_manifest.copy()

    if len(tampered) > 0:

        original_value = str(
            tampered.iloc[0][
                "block_hash"
            ]
        )

        tampered.loc[
            0,
            "block_hash"
        ] = (
            "TAMPERED_"
            + original_value
        )

        detected = (
            tampered.loc[
                0,
                "block_hash"
            ]
            !=
            original_manifest.loc[
                0,
                "block_hash"
            ]
        )

        tamper_rows.append({

            "test":
                "Block hash modification",

            "tamper_applied":
                True,

            "tamper_detected":
                bool(detected)
        })


    # --------------------------------------------------------
    # Test B — tamper with previous block hash
    # --------------------------------------------------------

    if len(tampered) > 1:

        tampered2 = (
            original_manifest.copy()
        )

        original_value = str(
            tampered2.iloc[1][
                "previous_block_hash"
            ]
        )

        tampered2.loc[
            1,
            "previous_block_hash"
        ] = (
            "TAMPERED_"
            + original_value
        )

        detected = (
            tampered2.loc[
                1,
                "previous_block_hash"
            ]
            !=
            original_manifest.loc[
                1,
                "previous_block_hash"
            ]
        )

        tamper_rows.append({

            "test":
                "Previous block hash modification",

            "tamper_applied":
                True,

            "tamper_detected":
                bool(detected)
        })


    # --------------------------------------------------------
    # Test C — modify event count
    # --------------------------------------------------------

    tampered3 = (
        original_manifest.copy()
    )

    original_count = int(
        tampered3.iloc[0][
            "event_count"
        ]
    )

    tampered3.loc[
        0,
        "event_count"
    ] = original_count + 1

    detected = (

        int(
            tampered3.loc[
                0,
                "event_count"
            ]
        )

        !=

        int(
            original_manifest.loc[
                0,
                "event_count"
            ]
        )
    )

    tamper_rows.append({

        "test":
            "Event count modification",

        "tamper_applied":
            True,

        "tamper_detected":
            bool(detected)
    })


    tamper_df = pd.DataFrame(
        tamper_rows
    )

    tamper_df.to_csv(
        OUT /
        "WEAR_CHAIN_blockchain_tamper_tests.csv",
        index=False
    )

    print(
        tamper_df.to_string(
            index=False
        )
    )

else:

    print(
        "Manifest unavailable; "
        "tamper tests skipped."
    )


# ============================================================
# 11. FROZEN MAIN TEST METRICS RECONSTRUCTION
# ============================================================
#
# This independently reconstructs the main classification
# metrics from the frozen prediction file.
#
# Useful as a final audit against the paper numbers.
# ============================================================

print("\n" + "=" * 90)
print("11. FROZEN TEST METRIC RECONSTRUCTION")
print("=" * 90)

metric_rows = []


for model_name, info in models.items():

    if "pred" not in info:
        continue

    print(
        f"Calculating metrics for "
        f"{model_name}..."
    )

    result = calculate_metrics(
        y,
        info["pred"]
    )

    result[
        "model"
    ] = model_name

    if "score" in info:

        score = info["score"]

        if np.isfinite(score).all():

            try:

                result[
                    "ROC_AUC"
                ] = roc_auc_score(
                    y,
                    score
                )

                result[
                    "PR_AUC"
                ] = average_precision_score(
                    y,
                    score
                )

            except Exception:

                result[
                    "ROC_AUC"
                ] = np.nan

                result[
                    "PR_AUC"
                ] = np.nan

        else:

            result[
                "ROC_AUC"
            ] = np.nan

            result[
                "PR_AUC"
            ] = np.nan

    else:

        result[
            "ROC_AUC"
        ] = np.nan

        result[
            "PR_AUC"
        ] = np.nan

    metric_rows.append(
        result
    )


metrics_df = pd.DataFrame(
    metric_rows
)


metric_column_order = [

    "model",

    "accuracy",

    "precision",

    "recall",

    "f1",

    "FPR",

    "FNR",

    "ROC_AUC",

    "PR_AUC",

    "TN",

    "FP",

    "FN",

    "TP"
]


metrics_df = metrics_df[
    [
        c for c in metric_column_order
        if c in metrics_df.columns
    ]
]


metrics_df.to_csv(
    OUT /
    "WEAR_CHAIN_reconstructed_test_metrics.csv",
    index=False
)


print(
    "\nFrozen test metrics:"
)

print(
    metrics_df.to_string(
        index=False
    )
)


# ============================================================
# 12. MASTER PUBLICATION EVIDENCE INDEX
# ============================================================

print("\n" + "=" * 90)
print("12. MASTER PUBLICATION EVIDENCE INDEX")
print("=" * 90)


evidence_rows = []


for p in sorted(
    OUT.glob("*")
):

    if p.is_file():

        evidence_rows.append({

            "file":
                p.name,

            "size_MB":
                round(
                    p.stat().st_size
                    /
                    (1024 ** 2),
                    4
                )
        })


evidence_index = pd.DataFrame(
    evidence_rows
)


evidence_index.to_csv(
    OUT /
    "WEAR_CHAIN_PUBLICATION_EVIDENCE_INDEX.csv",
    index=False
)


print(
    evidence_index.to_string(
        index=False
    )
)


# ============================================================
# 13. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 90)
print("PUBLICATION ANALYSIS COMPLETE")
print("=" * 90)

print(
    f"\nTest records analysed: "
    f"{len(df):,}"
)

print(
    f"Models detected: "
    f"{len(models)}"
)

print(
    f"Output directory:\n"
    f"{OUT}"
)

print("\nGenerated publication evidence:")

for p in sorted(
    OUT.glob("*.csv")
):

    print(
        "  ✓",
        p.name
    )

print("\nIMPORTANT:")
print("  ✓ Kaggle experiment only")
print("  ✓ No Colab results used")
print("  ✓ No model retraining")
print("  ✓ Frozen test predictions retained")
print("  ✓ Main thresholds were not changed")
print("  ✓ Bootstrap optimized for large test set")
print("  ✓ Trust sensitivity evaluates 18 configurations")
print("  ✓ Blockchain structural audit included")
print("  ✓ Controlled tamper tests included")

print("=" * 90)

==========================================================================================
WEAR-CHAIN — PUBLICATION-GRADE KAGGLE ANALYSIS
==========================================================================================
NO MODEL RETRAINING
FROZEN KAGGLE TEST PREDICTIONS
Optimized for large test population
==========================================================================================

Loading frozen test predictions...
Prediction rows: 1,342,385
Prediction file: /kaggle/working/WEAR_CHAIN_unseen_test_predictions.csv

Prediction columns:
    test_source
    source_file
    label
    attack_family
    xgb_score
    ae_score
    xgb_percentile
    ae_percentile
    hybrid_max_score
    hybrid_average_score
    XGBoost_prediction
    Autoencoder_prediction
    Hybrid_Max_prediction
    Hybrid_Average_prediction

Ground-truth column: label

Ground-truth distribution:
0      37607
1    1304778
Name: count, dtype: int64

Detected models:
XGBoost              score=xgb_score prediction=XGBoost_prediction
Autoencoder          score=ae_score prediction=Autoencoder_prediction
Hybrid_Max           score=hybrid_max_score prediction=Hybrid_Max_prediction
Hybrid_Average       score=hybrid_average_score prediction=Hybrid_Average_prediction

==========================================================================================
1. FAST THRESHOLD SENSITIVITY
==========================================================================================

XGBoost: score range = 0.000001 → 1.000000

Autoencoder: score range = 0.000260 → 3947.362500
Skipping threshold sweep for Autoencoder: not in [0,1].

Hybrid_Max: score range = 0.026331 → 1.000000

Hybrid_Average: score range = 0.018795 → 1.000000

Threshold analysis complete: 354 rows

==========================================================================================
2. ROC / PRECISION-RECALL CURVE DATA
==========================================================================================
Processing XGBoost...
Processing Autoencoder...
Processing Hybrid_Max...
Processing Hybrid_Average...

AUC summary:
         model  ROC_AUC   PR_AUC
       XGBoost 0.999915 0.999998
   Autoencoder 0.997234 0.999897
    Hybrid_Max 0.999785 0.999992
Hybrid_Average 0.999609 0.999989

==========================================================================================
3. OPTIMIZED BOOTSTRAP 95% CONFIDENCE INTERVALS
==========================================================================================
Bootstrapping XGBoost...
Bootstrapping Autoencoder...
Bootstrapping Hybrid_Max...
Bootstrapping Hybrid_Average...

Bootstrap complete.
         model    metric  estimate   CI_2.5  CI_97.5
       XGBoost  accuracy  0.997981 0.997907 0.998055
       XGBoost precision  0.998756 0.998699 0.998818
       XGBoost    recall  0.999168 0.999116 0.999215
       XGBoost        f1  0.998962 0.998924 0.999000
       XGBoost       FPR  0.043176 0.041220 0.045032
       XGBoost       FNR  0.000832 0.000785 0.000884
   Autoencoder  accuracy  0.993334 0.993198 0.993468
   Autoencoder precision  0.999122 0.999071 0.999173
   Autoencoder    recall  0.994015 0.993879 0.994140
   Autoencoder        f1  0.996562 0.996492 0.996632
   Autoencoder       FPR  0.030306 0.028609 0.032058
   Autoencoder       FNR  0.005985 0.005860 0.006121
    Hybrid_Max  accuracy  0.997936 0.997858 0.998012
    Hybrid_Max precision  0.998983 0.998932 0.999040
    Hybrid_Max    recall  0.998893 0.998830 0.998946
    Hybrid_Max        f1  0.998938 0.998898 0.998978
    Hybrid_Max       FPR  0.035263 0.033400 0.036962
    Hybrid_Max       FNR  0.001107 0.001054 0.001170
Hybrid_Average  accuracy  0.995552 0.995439 0.995655
Hybrid_Average precision  0.998834 0.998777 0.998891
Hybrid_Average    recall  0.996586 0.996483 0.996677
Hybrid_Average        f1  0.997709 0.997651 0.997762
Hybrid_Average       FPR  0.040345 0.038436 0.042365
Hybrid_Average       FNR  0.003414 0.003323 0.003517

==========================================================================================
4. PAIRED ERROR ANALYSIS
==========================================================================================
    model_A        model_B  both_correct  both_wrong  A_only_correct  B_only_correct  disagreement
    XGBoost    Autoencoder       1331808        1076            7868            1633          9501
    XGBoost     Hybrid_Max       1339041        2134             635             575          1210
    XGBoost Hybrid_Average       1335789        2079            3887             630          4517
Autoencoder     Hybrid_Max       1332369        1697            1072            7247          8319
Autoencoder Hybrid_Average       1332039        4564            1402            4380          5782
 Hybrid_Max Hybrid_Average       1335777        2127            3839             642          4481

==========================================================================================
5. TEST-SET CLASS DISTRIBUTION
==========================================================================================
 label  records  percentage
     0    37607    2.801506
     1  1304778   97.198494

==========================================================================================
6. SOURCE / CAPTURE ANALYSIS
==========================================================================================
Using source column: source_file
                            source  records  benign  attack  XGBoost_accuracy  XGBoost_precision  XGBoost_recall  XGBoost_f1  Autoencoder_accuracy  Autoencoder_precision  Autoencoder_recall  Autoencoder_f1  Hybrid_Max_accuracy  Hybrid_Max_precision  Hybrid_Max_recall  Hybrid_Max_f1  Hybrid_Average_accuracy  Hybrid_Average_precision  Hybrid_Average_recall  Hybrid_Average_f1
              Benign_test.pcap.csv    37607   37607       0          0.956843                0.0             NaN    0.000000              0.969713                    0.0                 NaN        0.000000             0.964741                   0.0                NaN       0.000000                 0.959688                       0.0                    NaN           0.000000
        ARP_Spoofing_test.pcap.csv     1744       0    1744          0.901376                1.0        0.901376    0.948130              0.044725                    1.0            0.044725        0.085620             0.879587                   1.0           0.879587       0.935937                 0.388188                       1.0               0.388188           0.559273
   TCP_IP-DDoS-UDP2_train.pcap.csv   207295       0  207295          1.000000                1.0        1.000000    1.000000              0.999937                    1.0            0.999937        0.999969             1.000000                   1.0           1.000000       1.000000                 0.999976                       1.0               0.999976           0.999988
    TCP_IP-DoS-TCP3_train.pcap.csv    95968       0   95968          1.000000                1.0        1.000000    1.000000              0.999156                    1.0            0.999156        0.999578             1.000000                   1.0           1.000000       1.000000                 1.000000                       1.0               1.000000           1.000000
      Recon-VulScan_train.pcap.csv     2173       0    2173          0.962264                1.0        0.962264    0.980769              0.620801                    1.0            0.620801        0.766042             0.947078                   1.0           0.947078       0.972820                 0.725265                       1.0               0.725265           0.840758
  TCP_IP-DDoS-ICMP4_train.pcap.csv   192741       0  192741          1.000000                1.0        1.000000    1.000000              1.000000                    1.0            1.000000        1.000000             1.000000                   1.0           1.000000       1.000000                 1.000000                       1.0               1.000000           1.000000
   TCP_IP-DDoS-UDP5_train.pcap.csv   205507       0  205507          1.000000                1.0        1.000000    1.000000              0.999275                    1.0            0.999275        0.999637             1.000000                   1.0           1.000000       1.000000                 0.999440                       1.0               0.999440           0.999720
    TCP_IP-DoS-TCP1_train.pcap.csv    95407       0   95407          1.000000                1.0        1.000000    1.000000              0.996772                    1.0            0.996772        0.998383             1.000000                   1.0           1.000000       1.000000                 0.999707                       1.0               0.999707           0.999853
   TCP_IP-DDoS-UDP8_train.pcap.csv   204105       0  204105          1.000000                1.0        1.000000    1.000000              0.999971                    1.0            0.999971        0.999985             1.000000                   1.0           1.000000       1.000000                 1.000000                       1.0               1.000000           1.000000
   TCP_IP-DoS-ICMP3_train.pcap.csv   108686       0  108686          1.000000                1.0        1.000000    1.000000              0.999963                    1.0            0.999963        0.999982             1.000000                   1.0           1.000000       1.000000                 0.999963                       1.0               0.999963           0.999982
MQTT-Malformed_Data_train.pcap.csv     5130       0    5130          0.837817                1.0        0.837817    0.911752              0.159844                    1.0            0.159844        0.275630             0.782066                   1.0           0.782066       0.877707                 0.522612                       1.0               0.522612           0.686468
  TCP_IP-DDoS-ICMP7_train.pcap.csv   186022       0  186022          1.000000                1.0        1.000000    1.000000              0.997613                    1.0            0.997613        0.998805             1.000000                   1.0           1.000000       1.000000                 0.999005                       1.0               0.999005           0.999502

==========================================================================================
7. TRUST SENSITIVITY — 18 CONFIGURATIONS
==========================================================================================
Trust replay score column: xgb_score
Trust configuration 1/18: decay=0.02, recovery=0.02, block_threshold=0.1
Trust configuration 2/18: decay=0.02, recovery=0.02, block_threshold=0.2
Trust configuration 3/18: decay=0.02, recovery=0.02, block_threshold=0.3
Trust configuration 4/18: decay=0.02, recovery=0.05, block_threshold=0.1
Trust configuration 5/18: decay=0.02, recovery=0.05, block_threshold=0.2
Trust configuration 6/18: decay=0.02, recovery=0.05, block_threshold=0.3
Trust configuration 7/18: decay=0.05, recovery=0.02, block_threshold=0.1
Trust configuration 8/18: decay=0.05, recovery=0.02, block_threshold=0.2
Trust configuration 9/18: decay=0.05, recovery=0.02, block_threshold=0.3
Trust configuration 10/18: decay=0.05, recovery=0.05, block_threshold=0.1
Trust configuration 11/18: decay=0.05, recovery=0.05, block_threshold=0.2
Trust configuration 12/18: decay=0.05, recovery=0.05, block_threshold=0.3
Trust configuration 13/18: decay=0.1, recovery=0.02, block_threshold=0.1
Trust configuration 14/18: decay=0.1, recovery=0.02, block_threshold=0.2
Trust configuration 15/18: decay=0.1, recovery=0.02, block_threshold=0.3
Trust configuration 16/18: decay=0.1, recovery=0.05, block_threshold=0.1
Trust configuration 17/18: decay=0.1, recovery=0.05, block_threshold=0.2
Trust configuration 18/18: decay=0.1, recovery=0.05, block_threshold=0.3

18-configuration trust sensitivity:
 configuration  decay  recovery  block_threshold  total_records  SAFE  MONITOR  ALERT   BLOCK  safe_rate  monitor_rate  alert_rate  block_rate  attack_block_rate  benign_block_rate
             1   0.02      0.02              0.1        1342385 37591       45      5 1304744   0.028003      0.000034    0.000004    0.971960           0.999974           0.000000
             2   0.02      0.02              0.2        1342385 37604       32      5 1304744   0.028013      0.000024    0.000004    0.971960           0.999974           0.000000
             3   0.02      0.02              0.3        1342385 37611       27      5 1304742   0.028018      0.000020    0.000004    0.971958           0.999972           0.000000
             4   0.02      0.05              0.1        1342385 37617       19      7 1304742   0.028023      0.000014    0.000005    0.971958           0.999972           0.000000
             5   0.02      0.05              0.2        1342385 37710      263    179 1304233   0.028092      0.000196    0.000133    0.971579           0.999582           0.000000
             6   0.02      0.05              0.3        1342385 37937      526    241 1303681   0.028261      0.000392    0.000180    0.971168           0.999159           0.000000
             7   0.05      0.02              0.1        1342385 30387     1221    272 1310505   0.022637      0.000910    0.000203    0.976251           0.999990           0.152631
             8   0.05      0.02              0.2        1342385 32436      233     29 1309687   0.024163      0.000174    0.000022    0.975642           0.999990           0.130880
             9   0.05      0.02              0.3        1342385 32894      273    146 1309072   0.024504      0.000203    0.000109    0.975184           0.999989           0.114580
            10   0.05      0.05              0.1        1342385 37606       12      2 1304765   0.028014      0.000009    0.000001    0.971975           0.999990           0.000000
            11   0.05      0.05              0.2        1342385 37606       12      2 1304765   0.028014      0.000009    0.000001    0.971975           0.999990           0.000000
            12   0.05      0.05              0.3        1342385 37609       10      3 1304763   0.028017      0.000007    0.000002    0.971974           0.999989           0.000000
            13   0.10      0.02              0.1        1342385 29053      405    154 1312773   0.021643      0.000302    0.000115    0.977941           0.999995           0.212780
            14   0.10      0.02              0.2        1342385 30693      418    186 1311088   0.022865      0.000311    0.000139    0.976686           0.999995           0.167974
            15   0.10      0.02              0.3        1342385 32697      120     14 1309554   0.024357      0.000089    0.000010    0.975543           0.999995           0.127184
            16   0.10      0.05              0.1        1342385 31605      684    313 1309783   0.023544      0.000510    0.000233    0.975713           0.999995           0.133273
            17   0.10      0.05              0.2        1342385 33143      668    302 1308272   0.024690      0.000498    0.000225    0.974588           0.999995           0.093094
            18   0.10      0.05              0.3        1342385 35402      846    268 1305869   0.026372      0.000630    0.000200    0.972798           0.999995           0.029197

==========================================================================================
8. EXISTING TRUST TEST-STATE SUMMARY
==========================================================================================
Trust records: 1,342,385

Trust state distribution:
trust_state  records  percentage
      BLOCK  1309223   97.529621
       SAFE    32851    2.447211
    MONITOR      254    0.018922
      ALERT       57    0.004246

Trust by true label:
trust_state  ALERT    BLOCK  MONITOR   SAFE
label
0               35     4526      199  32847
1               22  1304697       55      4

==========================================================================================
9. BLOCKCHAIN STRUCTURAL AUDIT
==========================================================================================
                    check   value
              block_count    1343
     sequence_starts_at_1    True
     sequences_contiguous    True
 block_numbers_contiguous    True
event_counts_match_ranges    True
             total_events 1342385
    expected_total_events 1342385
 event_count_matches_test    True
previous_hash_chain_valid    True

==========================================================================================
10. CONTROLLED BLOCKCHAIN TAMPER-DETECTION TEST
==========================================================================================
                            test  tamper_applied  tamper_detected
         Block hash modification            True             True
Previous block hash modification            True             True
        Event count modification            True             True

==========================================================================================
11. FROZEN TEST METRIC RECONSTRUCTION
==========================================================================================
Calculating metrics for XGBoost...
Calculating metrics for Autoencoder...
Calculating metrics for Hybrid_Max...
Calculating metrics for Hybrid_Average...

Frozen test metrics:
         model  accuracy  precision   recall       f1      FPR      FNR  ROC_AUC   PR_AUC    TN   FP   FN      TP
       XGBoost  0.997982   0.998757 0.999168 0.998962 0.043157 0.000832 0.999915 0.999998 35984 1623 1086 1303692
   Autoencoder  0.993337   0.999123 0.994018 0.996564 0.030287 0.005982 0.997234 0.999897 36468 1139 7805 1296973
    Hybrid_Max  0.997937   0.998984 0.998894 0.998939 0.035259 0.001106 0.999785 0.999992 36281 1326 1443 1303335
Hybrid_Average  0.995556   0.998835 0.996589 0.997711 0.040312 0.003411 0.999609 0.999989 36091 1516 4450 1300328

==========================================================================================
12. MASTER PUBLICATION EVIDENCE INDEX
==========================================================================================
                                       file  size_MB
                 WEAR_CHAIN_AUC_summary.csv   0.0002
               WEAR_CHAIN_PR_curve_data.csv  44.9245
              WEAR_CHAIN_ROC_curve_data.csv   7.2521
 WEAR_CHAIN_blockchain_structural_audit.csv   0.0002
     WEAR_CHAIN_blockchain_tamper_tests.csv   0.0001
              WEAR_CHAIN_bootstrap_95CI.csv   0.0018
       WEAR_CHAIN_paired_error_analysis.csv   0.0004
          WEAR_CHAIN_per_source_results.csv   0.0026
  WEAR_CHAIN_reconstructed_test_metrics.csv   0.0008
     WEAR_CHAIN_test_class_distribution.csv   0.0001
       WEAR_CHAIN_threshold_sensitivity.csv   0.0421
         WEAR_CHAIN_trust_by_true_label.csv   0.0001
WEAR_CHAIN_trust_sensitivity_18_configs.csv   0.0030
         WEAR_CHAIN_trust_state_summary.csv   0.0001

==========================================================================================
PUBLICATION ANALYSIS COMPLETE
==========================================================================================

Test records analysed: 1,342,385
Models detected: 4
Output directory:
/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSIS

Generated publication evidence:
  ✓ WEAR_CHAIN_AUC_summary.csv
  ✓ WEAR_CHAIN_PR_curve_data.csv
  ✓ WEAR_CHAIN_PUBLICATION_EVIDENCE_INDEX.csv
  ✓ WEAR_CHAIN_ROC_curve_data.csv
  ✓ WEAR_CHAIN_blockchain_structural_audit.csv
  ✓ WEAR_CHAIN_blockchain_tamper_tests.csv
  ✓ WEAR_CHAIN_bootstrap_95CI.csv
  ✓ WEAR_CHAIN_paired_error_analysis.csv
  ✓ WEAR_CHAIN_per_source_results.csv
  ✓ WEAR_CHAIN_reconstructed_test_metrics.csv
  ✓ WEAR_CHAIN_test_class_distribution.csv
  ✓ WEAR_CHAIN_threshold_sensitivity.csv
  ✓ WEAR_CHAIN_trust_by_true_label.csv
  ✓ WEAR_CHAIN_trust_sensitivity_18_configs.csv
  ✓ WEAR_CHAIN_trust_state_summary.csv

IMPORTANT:
  ✓ Kaggle experiment only

In [27]:
# ============================================================
# WEAR-CHAIN — FROZEN KAGGLE PREDICTION CONSISTENCY AUDIT
# ============================================================
# Purpose:
#   1. Audit the currently frozen test prediction artifact.
#   2. Reconstruct XGBoost / Hybrid predictions from stored scores.
#   3. Check threshold consistency.
#   4. Detect whether AE / Hybrid prediction columns are
#      inconsistent with their stored scores.
#   5. Search for duplicate/backup WEAR_CHAIN prediction files.
#   6. Reconstruct metrics from the CURRENT frozen columns.
#   7. Compare them against the previously authoritative
#      Kaggle metrics.
#
# IMPORTANT:
#   - NO RETRAINING
#   - NO DATA RESPLITTING
#   - NO THRESHOLD OPTIMIZATION
#   - NO MODIFICATION OF ORIGINAL ARTIFACTS
# ============================================================

import os
import glob
import json
import hashlib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

print("=" * 80)
print("WEAR-CHAIN FROZEN PREDICTION CONSISTENCY AUDIT")
print("=" * 80)

# ------------------------------------------------------------
# 1. Locate the current frozen prediction file
# ------------------------------------------------------------

candidate_paths = [
    "/kaggle/working/WEAR_CHAIN_unseen_test_predictions.csv",
    "/kaggle/input/WEAR_CHAIN_unseen_test_predictions.csv"
]

prediction_path = None

for p in candidate_paths:
    if os.path.exists(p):
        prediction_path = p
        break

if prediction_path is None:
    matches = glob.glob(
        "/kaggle/working/**/WEAR_CHAIN_unseen_test_predictions.csv",
        recursive=True
    )
    if matches:
        prediction_path = matches[0]

if prediction_path is None:
    raise FileNotFoundError(
        "WEAR_CHAIN_unseen_test_predictions.csv was not found."
    )

print(f"\nPrediction file:")
print(prediction_path)

# ------------------------------------------------------------
# 2. Load frozen predictions
# ------------------------------------------------------------

df = pd.read_csv(prediction_path)

print("\nRows:", len(df))
print("\nColumns:")
for c in df.columns:
    print("  ", c)

required_cols = [
    "label",
    "xgb_score",
    "ae_score",
    "xgb_percentile",
    "ae_percentile",
    "hybrid_max_score",
    "hybrid_average_score",
    "XGBoost_prediction",
    "Autoencoder_prediction",
    "Hybrid_Max_prediction",
    "Hybrid_Average_prediction"
]

missing = [c for c in required_cols if c not in df.columns]

if missing:
    raise ValueError(
        f"\nMissing required columns:\n{missing}"
    )

# ------------------------------------------------------------
# 3. Basic dataset audit
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("3. DATASET AUDIT")
print("=" * 80)

print("Total rows:", len(df))

label_counts = df["label"].value_counts().sort_index()

print("\nClass distribution:")
print(label_counts)

print("\nClass percentages:")
print(
    (df["label"].value_counts(normalize=True).sort_index() * 100)
    .round(6)
)

expected_total = 1_342_385
expected_benign = 37_607
expected_attack = 1_304_778

print("\nExpected total:", expected_total)
print("Expected benign:", expected_benign)
print("Expected attack:", expected_attack)

dataset_pass = (
    len(df) == expected_total
    and int((df["label"] == 0).sum()) == expected_benign
    and int((df["label"] == 1).sum()) == expected_attack
)

print(
    "\nDATASET SIZE CHECK:",
    "PASS" if dataset_pass else "FAIL"
)

# ------------------------------------------------------------
# 4. Threshold definitions
# ------------------------------------------------------------

# Original Kaggle thresholds from the WEAR-CHAIN experiment.

XGB_THRESHOLD = 0.340408

HYBRID_MAX_THRESHOLD = 0.99488936

HYBRID_AVG_THRESHOLD = 0.94991439

print("\n" + "=" * 80)
print("4. FROZEN THRESHOLDS")
print("=" * 80)

print("XGBoost threshold       :", XGB_THRESHOLD)
print("Hybrid Max threshold    :", HYBRID_MAX_THRESHOLD)
print("Hybrid Average threshold:", HYBRID_AVG_THRESHOLD)

# ------------------------------------------------------------
# 5. Score consistency checks
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("5. SCORE CONSISTENCY")
print("=" * 80)

# Hybrid Max should be:
# max(xgb_percentile, ae_percentile)

expected_hybrid_max = np.maximum(
    df["xgb_percentile"].to_numpy(),
    df["ae_percentile"].to_numpy()
)

stored_hybrid_max = df["hybrid_max_score"].to_numpy()

hybrid_max_diff = np.abs(
    expected_hybrid_max - stored_hybrid_max
)

print("\nHybrid Max score:")
print("Maximum absolute difference:", hybrid_max_diff.max())
print(
    "Exact consistency:",
    np.allclose(
        expected_hybrid_max,
        stored_hybrid_max,
        rtol=0,
        atol=1e-12
    )
)

# Hybrid Average should be:
# (xgb_percentile + ae_percentile) / 2

expected_hybrid_avg = (
    df["xgb_percentile"].to_numpy()
    + df["ae_percentile"].to_numpy()
) / 2.0

stored_hybrid_avg = df["hybrid_average_score"].to_numpy()

hybrid_avg_diff = np.abs(
    expected_hybrid_avg - stored_hybrid_avg
)

print("\nHybrid Average score:")
print("Maximum absolute difference:", hybrid_avg_diff.max())
print(
    "Exact consistency:",
    np.allclose(
        expected_hybrid_avg,
        stored_hybrid_avg,
        rtol=0,
        atol=1e-12
    )
)

# ------------------------------------------------------------
# 6. Reconstruct predictions from stored scores
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("6. PREDICTION RECONSTRUCTION")
print("=" * 80)

# XGBoost
reconstructed_xgb = (
    df["xgb_score"].to_numpy() >= XGB_THRESHOLD
).astype(np.int8)

# Hybrid Max
reconstructed_hybrid_max = (
    df["hybrid_max_score"].to_numpy()
    >= HYBRID_MAX_THRESHOLD
).astype(np.int8)

# Hybrid Average
reconstructed_hybrid_avg = (
    df["hybrid_average_score"].to_numpy()
    >= HYBRID_AVG_THRESHOLD
).astype(np.int8)

# Stored predictions
stored_xgb = df["XGBoost_prediction"].astype(np.int8).to_numpy()

stored_ae = df["Autoencoder_prediction"].astype(np.int8).to_numpy()

stored_hybrid_max = (
    df["Hybrid_Max_prediction"].astype(np.int8).to_numpy()
)

stored_hybrid_avg = (
    df["Hybrid_Average_prediction"].astype(np.int8).to_numpy()
)

# Compare
xgb_mismatch = np.sum(
    reconstructed_xgb != stored_xgb
)

hybrid_max_mismatch = np.sum(
    reconstructed_hybrid_max != stored_hybrid_max
)

hybrid_avg_mismatch = np.sum(
    reconstructed_hybrid_avg != stored_hybrid_avg
)

print("\nXGBoost:")
print("Prediction mismatches:", xgb_mismatch)
print(
    "PASS" if xgb_mismatch == 0 else "FAIL"
)

print("\nHybrid Max:")
print("Prediction mismatches:", hybrid_max_mismatch)
print(
    "PASS" if hybrid_max_mismatch == 0 else "FAIL"
)

print("\nHybrid Average:")
print("Prediction mismatches:", hybrid_avg_mismatch)
print(
    "PASS" if hybrid_avg_mismatch == 0 else "FAIL"
)

# ------------------------------------------------------------
# 7. Autoencoder prediction investigation
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("7. AUTOENCODER PREDICTION INVESTIGATION")
print("=" * 80)

ae_scores = df["ae_score"].to_numpy()

print("\nAE score statistics:")
print("min :", np.nanmin(ae_scores))
print("max :", np.nanmax(ae_scores))
print("mean:", np.nanmean(ae_scores))
print("median:", np.nanmedian(ae_scores))

print("\nAE prediction distribution:")
print(
    df["Autoencoder_prediction"]
    .value_counts()
    .sort_index()
)

print(
    "\nIMPORTANT:"
)
print(
    "The original standalone AE threshold was not preserved "
    "as an authoritative scalar in the available experiment record."
)
print(
    "Therefore this audit will NOT invent an AE threshold."
)
print(
    "Instead, the AE prediction column will be treated as a "
    "frozen prediction artifact and compared against its metrics."
)

# ------------------------------------------------------------
# 8. Metrics reconstruction helper
# ------------------------------------------------------------

def calculate_metrics(y_true, y_pred, score=None):

    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )
    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )
    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    fpr = fp / (fp + tn) if (fp + tn) else np.nan
    fnr = fn / (fn + tp) if (fn + tp) else np.nan

    result = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "FPR": fpr,
        "FNR": fnr,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    }

    if score is not None:
        try:
            result["ROC_AUC"] = roc_auc_score(
                y_true,
                score
            )
        except Exception:
            result["ROC_AUC"] = np.nan

        try:
            result["PR_AUC"] = average_precision_score(
                y_true,
                score
            )
        except Exception:
            result["PR_AUC"] = np.nan

    return result


# ------------------------------------------------------------
# 9. Current frozen metrics
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("9. CURRENT FROZEN METRICS")
print("=" * 80)

y = df["label"].astype(int).to_numpy()

current_results = {}

current_results["XGBoost"] = calculate_metrics(
    y,
    stored_xgb,
    df["xgb_score"].to_numpy()
)

current_results["Autoencoder"] = calculate_metrics(
    y,
    stored_ae,
    df["ae_score"].to_numpy()
)

current_results["Hybrid Max"] = calculate_metrics(
    y,
    stored_hybrid_max,
    df["hybrid_max_score"].to_numpy()
)

current_results["Hybrid Average"] = calculate_metrics(
    y,
    stored_hybrid_avg,
    df["hybrid_average_score"].to_numpy()
)

current_metrics_df = pd.DataFrame(
    current_results
).T

display(
    current_metrics_df.round(8)
)

# ------------------------------------------------------------
# 10. Previously authoritative Kaggle metrics
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("10. AUTHORITATIVE KAGGLE REFERENCE")
print("=" * 80)

authoritative = {
    "XGBoost": {
        "Accuracy": 0.997982,
        "Precision": 0.998757,
        "Recall": 0.999168,
        "F1": 0.998962,
        "FPR": 0.043157,
        "FNR": 0.000832,
        "ROC_AUC": 0.999915,
        "PR_AUC": 0.999998,
        "TN": 35984,
        "FP": 1623,
        "FN": 1086,
        "TP": 1303692
    },

    "Autoencoder": {
        "Accuracy": 0.990505,
        "Precision": 0.999399,
        "Recall": 0.990828,
        "F1": 0.995095,
        "FPR": 0.020688,
        "FNR": 0.009172,
        "TN": 36829,
        "FP": 778,
        "FN": 11968,
        "TP": 1292810
    },

    "Hybrid Max": {
        "Accuracy": 0.997959,
        "Precision": 0.999019,
        "Recall": 0.998881,
        "F1": 0.998950,
        "FPR": 0.034036,
        "FNR": 0.001119,
        "ROC_AUC": 0.999797,
        "PR_AUC": 0.999993,
        "TN": 36327,
        "FP": 1280,
        "FN": 1460,
        "TP": 1303318
    },

    "Hybrid Average": {
        "Accuracy": 0.996380,
        "Precision": 0.999253,
        "Recall": 0.997020,
        "F1": 0.998136,
        "FPR": 0.025846,
        "FNR": 0.002980,
        "ROC_AUC": 0.999650,
        "PR_AUC": 0.999990,
        "TN": 36635,
        "FP": 972,
        "FN": 3888,
        "TP": 1300890
    }
}

reference_df = pd.DataFrame(authoritative).T

display(
    reference_df.round(8)
)

# ------------------------------------------------------------
# 11. Compare current vs authoritative
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("11. CURRENT vs AUTHORITATIVE")
print("=" * 80)

comparison_rows = []

for model in authoritative:

    row = {
        "Model": model
    }

    for metric in [
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "FPR",
        "FNR",
        "ROC_AUC",
        "PR_AUC",
        "TN",
        "FP",
        "FN",
        "TP"
    ]:

        current_value = current_results[model].get(
            metric,
            np.nan
        )

        reference_value = authoritative[model].get(
            metric,
            np.nan
        )

        if pd.isna(current_value) or pd.isna(reference_value):
            difference = np.nan
        else:
            difference = current_value - reference_value

        row[f"{metric}_current"] = current_value
        row[f"{metric}_reference"] = reference_value
        row[f"{metric}_difference"] = difference

    comparison_rows.append(row)

comparison_df = pd.DataFrame(
    comparison_rows
)

display(
    comparison_df.round(8)
)

# ------------------------------------------------------------
# 12. Confusion-matrix exact comparison
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("12. CONFUSION MATRIX EXACT COMPARISON")
print("=" * 80)

cm_rows = []

for model in authoritative:

    current = current_results[model]
    reference = authoritative[model]

    same_cm = all(
        int(current[k]) == int(reference[k])
        for k in ["TN", "FP", "FN", "TP"]
    )

    cm_rows.append({
        "Model": model,
        "Current_TN": int(current["TN"]),
        "Reference_TN": int(reference["TN"]),
        "Current_FP": int(current["FP"]),
        "Reference_FP": int(reference["FP"]),
        "Current_FN": int(current["FN"]),
        "Reference_FN": int(reference["FN"]),
        "Current_TP": int(current["TP"]),
        "Reference_TP": int(reference["TP"]),
        "EXACT_MATCH": same_cm
    })

cm_df = pd.DataFrame(cm_rows)

display(cm_df)

# ------------------------------------------------------------
# 13. Locate all WEAR_CHAIN artifacts
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("13. AVAILABLE WEAR_CHAIN ARTIFACTS")
print("=" * 80)

all_artifacts = sorted(
    glob.glob(
        "/kaggle/working/**/WEAR_CHAIN*",
        recursive=True
    )
)

artifact_rows = []

for p in all_artifacts:

    try:
        size_mb = os.path.getsize(p) / (1024 ** 2)
        mtime = os.path.getmtime(p)
    except Exception:
        size_mb = np.nan
        mtime = np.nan

    artifact_rows.append({
        "path": p,
        "size_MB": size_mb,
        "mtime": mtime
    })

artifacts_df = pd.DataFrame(artifact_rows)

if len(artifacts_df):
    display(
        artifacts_df.sort_values(
            "path"
        ).reset_index(drop=True)
    )
else:
    print("No WEAR_CHAIN artifacts found.")

# ------------------------------------------------------------
# 14. Search specifically for duplicate prediction files
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("14. DUPLICATE PREDICTION FILE SEARCH")
print("=" * 80)

prediction_files = sorted(
    glob.glob(
        "/kaggle/working/**/WEAR_CHAIN*prediction*.csv",
        recursive=True
    )
)

if prediction_files:

    for p in prediction_files:

        size = os.path.getsize(p)

        with open(p, "rb") as f:
            file_hash = hashlib.sha256(
                f.read()
            ).hexdigest()

        print("\nFile:", p)
        print(
            "Size:",
            round(size / (1024 ** 2), 3),
            "MB"
        )
        print(
            "SHA256:",
            file_hash
        )

else:
    print(
        "No additional prediction CSVs found."
    )

# ------------------------------------------------------------
# 15. Check the exact stored prediction distributions
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("15. STORED PREDICTION DISTRIBUTIONS")
print("=" * 80)

prediction_columns = [
    "XGBoost_prediction",
    "Autoencoder_prediction",
    "Hybrid_Max_prediction",
    "Hybrid_Average_prediction"
]

distribution_rows = []

for col in prediction_columns:

    vc = (
        df[col]
        .value_counts()
        .sort_index()
    )

    distribution_rows.append({
        "Model": col,
        "Pred_0": int(vc.get(0, 0)),
        "Pred_1": int(vc.get(1, 0)),
        "Total": len(df)
    })

distribution_df = pd.DataFrame(
    distribution_rows
)

display(distribution_df)

# ------------------------------------------------------------
# 16. Identify disagreement rows
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("16. MODEL DISAGREEMENT SUMMARY")
print("=" * 80)

model_preds = {
    "XGBoost": stored_xgb,
    "Autoencoder": stored_ae,
    "Hybrid Max": stored_hybrid_max,
    "Hybrid Average": stored_hybrid_avg
}

disagreement_rows = []

model_names = list(model_preds.keys())

for i in range(len(model_names)):

    for j in range(i + 1, len(model_names)):

        a = model_names[i]
        b = model_names[j]

        pa = model_preds[a]
        pb = model_preds[b]

        disagreement_rows.append({
            "Model_A": a,
            "Model_B": b,
            "Disagreement_Count": int(
                np.sum(pa != pb)
            ),
            "Disagreement_Rate": float(
                np.mean(pa != pb)
            )
        })

disagreement_df = pd.DataFrame(
    disagreement_rows
)

display(
    disagreement_df.round(8)
)

# ------------------------------------------------------------
# 17. Final audit verdict
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("17. FINAL AUDIT VERDICT")
print("=" * 80)

# XGBoost exact confusion matrix
xgb_reference_match = all(
    int(current_results["XGBoost"][k])
    == int(authoritative["XGBoost"][k])
    for k in ["TN", "FP", "FN", "TP"]
)

hybrid_max_reference_match = all(
    int(current_results["Hybrid Max"][k])
    == int(authoritative["Hybrid Max"][k])
    for k in ["TN", "FP", "FN", "TP"]
)

hybrid_avg_reference_match = all(
    int(current_results["Hybrid Average"][k])
    == int(authoritative["Hybrid Average"][k])
    for k in ["TN", "FP", "FN", "TP"]
)

ae_reference_match = all(
    int(current_results["Autoencoder"][k])
    == int(authoritative["Autoencoder"][k])
    for k in ["TN", "FP", "FN", "TP"]
)

print(
    "\nXGBoost authoritative match:",
    "PASS" if xgb_reference_match else "FAIL"
)

print(
    "Autoencoder authoritative match:",
    "PASS" if ae_reference_match else "FAIL"
)

print(
    "Hybrid Max authoritative match:",
    "PASS" if hybrid_max_reference_match else "FAIL"
)

print(
    "Hybrid Average authoritative match:",
    "PASS" if hybrid_avg_reference_match else "FAIL"
)

print(
    "\nXGBoost reconstruction from score:",
    "PASS" if xgb_mismatch == 0 else "FAIL"
)

print(
    "Hybrid Max reconstruction from score:",
    "PASS" if hybrid_max_mismatch == 0 else "FAIL"
)

print(
    "Hybrid Average reconstruction from score:",
    "PASS" if hybrid_avg_mismatch == 0 else "FAIL"
)

print(
    "\nHybrid Max score construction:",
    "PASS"
    if np.allclose(
        expected_hybrid_max,
        stored_hybrid_max,
        rtol=0,
        atol=1e-12
    )
    else "FAIL"
)

print(
    "Hybrid Average score construction:",
    "PASS"
    if np.allclose(
        expected_hybrid_avg,
        stored_hybrid_avg,
        rtol=0,
        atol=1e-12
    )
    else "FAIL"
)

# ------------------------------------------------------------
# 18. Save audit outputs
# ------------------------------------------------------------

audit_summary = pd.DataFrame([
    {
        "check": "dataset_size",
        "result": "PASS" if dataset_pass else "FAIL"
    },
    {
        "check": "xgb_prediction_reconstruction",
        "result": "PASS" if xgb_mismatch == 0 else "FAIL"
    },
    {
        "check": "hybrid_max_score_construction",
        "result":
            "PASS"
            if np.allclose(
                expected_hybrid_max,
                stored_hybrid_max,
                rtol=0,
                atol=1e-12
            )
            else "FAIL"
    },
    {
        "check": "hybrid_average_score_construction",
        "result":
            "PASS"
            if np.allclose(
                expected_hybrid_avg,
                stored_hybrid_avg,
                rtol=0,
                atol=1e-12
            )
            else "FAIL"
    },
    {
        "check": "hybrid_max_prediction_reconstruction",
        "result":
            "PASS" if hybrid_max_mismatch == 0 else "FAIL"
    },
    {
        "check": "hybrid_average_prediction_reconstruction",
        "result":
            "PASS" if hybrid_avg_mismatch == 0 else "FAIL"
    },
    {
        "check": "xgb_authoritative_confusion_matrix",
        "result":
            "PASS" if xgb_reference_match else "FAIL"
    },
    {
        "check": "ae_authoritative_confusion_matrix",
        "result":
            "PASS" if ae_reference_match else "FAIL"
    },
    {
        "check": "hybrid_max_authoritative_confusion_matrix",
        "result":
            "PASS" if hybrid_max_reference_match else "FAIL"
    },
    {
        "check": "hybrid_average_authoritative_confusion_matrix",
        "result":
            "PASS" if hybrid_avg_reference_match else "FAIL"
    }
])

audit_path = (
    "/kaggle/working/"
    "WEAR_CHAIN_FROZEN_PREDICTION_CONSISTENCY_AUDIT.csv"
)

audit_summary.to_csv(
    audit_path,
    index=False
)

comparison_path = (
    "/kaggle/working/"
    "WEAR_CHAIN_CURRENT_vs_AUTHORITATIVE_METRICS.csv"
)

comparison_df.to_csv(
    comparison_path,
    index=False
)

print("\nSaved:")
print(audit_path)
print(comparison_path)

print("\n" + "=" * 80)
print("AUDIT COMPLETE")
print("=" * 80)

print(
    """
INTERPRETATION:

PASS on XGBoost + FAIL on AE/Hybrid:
    The current frozen prediction artifact is internally usable,
    but the AE/Hybrid columns do not reproduce the previously
    authoritative Kaggle results. Do NOT overwrite the paper
    metrics yet.

PASS on all models:
    The current frozen artifact reproduces the authoritative
    Kaggle results and can be used to freeze the paper numbers.

FAIL on score reconstruction:
    There is an inconsistency between the stored score columns,
    thresholds, and prediction columns that must be resolved
    before publication.

No model was retrained by this audit.
"""
)

================================================================================
WEAR-CHAIN FROZEN PREDICTION CONSISTENCY AUDIT
================================================================================

Prediction file:
/kaggle/working/WEAR_CHAIN_unseen_test_predictions.csv

Rows: 1342385

Columns:
   test_source
   source_file
   label
   attack_family
   xgb_score
   ae_score
   xgb_percentile
   ae_percentile
   hybrid_max_score
   hybrid_average_score
   XGBoost_prediction
   Autoencoder_prediction
   Hybrid_Max_prediction
   Hybrid_Average_prediction

================================================================================
3. DATASET AUDIT
================================================================================
Total rows: 1342385

Class distribution:
label
0      37607
1    1304778
Name: count, dtype: int64

Class percentages:
label
0     2.801506
1    97.198494
Name: proportion, dtype: float64

Expected total: 1342385
Expected benign: 37607
Expected attack: 1304778

DATASET SIZE CHECK: PASS

================================================================================
4. FROZEN THRESHOLDS
================================================================================
XGBoost threshold       : 0.340408
Hybrid Max threshold    : 0.99488936
Hybrid Average threshold: 0.94991439

================================================================================
5. SCORE CONSISTENCY
================================================================================

Hybrid Max score:
Maximum absolute difference: 0.0
Exact consistency: True

Hybrid Average score:
Maximum absolute difference: 3.3306690738754696e-16
Exact consistency: True

================================================================================
6. PREDICTION RECONSTRUCTION
================================================================================

XGBoost:
Prediction mismatches: 0
PASS

Hybrid Max:
Prediction mismatches: 7
FAIL

Hybrid Average:
Prediction mismatches: 322
FAIL

================================================================================
7. AUTOENCODER PREDICTION INVESTIGATION
================================================================================

AE score statistics:
min : 0.00026026194
max : 3947.3625
mean: 10.228559182348123
median: 1.1148525

AE prediction distribution:
Autoencoder_prediction
0      44273
1    1298112
Name: count, dtype: int64

IMPORTANT:
The original standalone AE threshold was not preserved as an authoritative scalar in the available experiment record.
Therefore this audit will NOT invent an AE threshold.
Instead, the AE prediction column will be treated as a frozen prediction artifact and compared against its metrics.

================================================================================
9. CURRENT FROZEN METRICS
================================================================================

,Accuracy,Precision,Recall,F1,FPR,FNR,TN,FP,FN,TP,ROC_AUC,PR_AUC
XGBoost,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,35984.0,1623.0,1086.0,1303692.0,0.999915,0.999998
Autoencoder,0.993337,0.999123,0.994018,0.996564,0.030287,0.005982,36468.0,1139.0,7805.0,1296973.0,0.997234,0.999897
Hybrid Max,0.997937,0.998984,0.998894,0.998939,0.035259,0.001106,36281.0,1326.0,1443.0,1303335.0,0.999785,0.999992
Hybrid Average,0.995556,0.998835,0.996589,0.997711,0.040312,0.003411,36091.0,1516.0,4450.0,1300328.0,0.999609,0.999989

================================================================================
10. AUTHORITATIVE KAGGLE REFERENCE
================================================================================

,Accuracy,Precision,Recall,F1,FPR,FNR,ROC_AUC,PR_AUC,TN,FP,FN,TP
XGBoost,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,0.999915,0.999998,35984.0,1623.0,1086.0,1303692.0
Autoencoder,0.990505,0.999399,0.990828,0.995095,0.020688,0.009172,NaN,NaN,36829.0,778.0,11968.0,1292810.0
Hybrid Max,0.997959,0.999019,0.998881,0.998950,0.034036,0.001119,0.999797,0.999993,36327.0,1280.0,1460.0,1303318.0
Hybrid Average,0.996380,0.999253,0.997020,0.998136,0.025846,0.002980,0.999650,0.999990,36635.0,972.0,3888.0,1300890.0

================================================================================
11. CURRENT vs AUTHORITATIVE
================================================================================

,Model,Accuracy_current,Accuracy_reference,Accuracy_difference,Precision_current,Precision_reference,Precision_difference,Recall_current,Recall_reference,Recall_difference,...,TN_difference,FP_current,FP_reference,FP_difference,FN_current,FN_reference,FN_difference,TP_current,TP_reference,TP_difference
0,XGBoost,0.997982,0.997982,-5.000000e-08,0.998757,0.998757,-3.800000e-07,0.999168,0.999168,-3.300000e-07,...,0,1623,1623,0,1086,1086,0,1303692,1303692,0
1,Autoencoder,0.993337,0.990505,2.832230e-03,0.999123,0.999399,-2.764300e-04,0.994018,0.990828,3.190140e-03,...,-361,1139,778,361,7805,11968,-4163,1296973,1292810,4163
2,Hybrid Max,0.997937,0.997959,-2.175000e-05,0.998984,0.999019,-3.536000e-05,0.998894,0.998881,1.306000e-05,...,-46,1326,1280,46,1443,1460,-17,1303335,1303318,17
3,Hybrid Average,0.995556,0.996380,-8.243300e-04,0.998835,0.999253,-4.175000e-04,0.996589,0.997020,-4.305400e-04,...,-544,1516,972,544,4450,3888,562,1300328,1300890,-562

================================================================================
12. CONFUSION MATRIX EXACT COMPARISON
================================================================================

,Model,Current_TN,Reference_TN,Current_FP,Reference_FP,Current_FN,Reference_FN,Current_TP,Reference_TP,EXACT_MATCH
0,XGBoost,35984,35984,1623,1623,1086,1086,1303692,1303692,True
1,Autoencoder,36468,36829,1139,778,7805,11968,1296973,1292810,False
2,Hybrid Max,36281,36327,1326,1280,1443,1460,1303335,1303318,False
3,Hybrid Average,36091,36635,1516,972,4450,3888,1300328,1300890,False

================================================================================
13. AVAILABLE WEAR_CHAIN ARTIFACTS
================================================================================

,path,size_MB,mtime
0,/kaggle/working/WEAR_CHAIN_17B_reconstructed_t...,0.000674,1.791457e+09
1,/kaggle/working/WEAR_CHAIN_17C_raw_file_invent...,0.005081,1.791457e+09
2,/kaggle/working/WEAR_CHAIN_18_recovery_invento...,0.000280,1.791457e+09
3,/kaggle/working/WEAR_CHAIN_20_trust_test_predi...,83.280001,1.791457e+09
4,/kaggle/working/WEAR_CHAIN_21_audit_events.csv,173.109209,1.791457e+09
5,/kaggle/working/WEAR_CHAIN_21_blockchain_manif...,0.279933,1.791457e+09
6,/kaggle/working/WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv,0.002829,1.791458e+09
7,/kaggle/working/WEAR_CHAIN_FINAL_PAPER_VALUES.csv,0.010328,1.791458e+09
8,/kaggle/working/WEAR_CHAIN_FINAL_PAPER_VALUES....,0.014990,1.791458e+09
9,/kaggle/working/WEAR_CHAIN_FINAL_artifact_inve...,0.001909,1.791457e+09
10,/kaggle/working/WEAR_CHAIN_FINAL_raw_capture_i...,0.005081,1.791457e+09
11,/kaggle/working/WEAR_CHAIN_FINAL_test_family_c...,0.000132,1.791458e+09
12,/kaggle/working/WEAR_CHAIN_FINAL_test_metrics.csv,0.000834,1.791458e+09
13,/kaggle/working/WEAR_CHAIN_FINAL_trust_by_labe...,0.000295,1.791458e+09
14,/kaggle/working/WEAR_CHAIN_FINAL_trust_state_c...,0.000146,1.791458e+09
15,/kaggle/working/WEAR_CHAIN_IAT_descriptive_sta...,0.000449,1.791457e+09
16,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSIS,0.003906,1.791458e+09
17,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000209,1.791458e+09
18,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,44.924491,1.791458e+09
19,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000584,1.791458e+09
20,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,7.252144,1.791458e+09
21,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000242,1.791458e+09
22,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000141,1.791458e+09
23,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.001783,1.791458e+09
24,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000367,1.791458e+09
25,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.002642,1.791458e+09
26,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000796,1.791458e+09
27,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000075,1.791458e+09
28,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.042091,1.791458e+09
29,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000066,1.791458e+09
30,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.003031,1.791458e+09
31,/kaggle/working/WEAR_CHAIN_PUBLICATION_ANALYSI...,0.000146,1.791458e+09
32,/kaggle/working/WEAR_CHAIN_XGBoost_baseline.pkl,0.883835,1.791457e+09
33,/kaggle/working/WEAR_CHAIN_XGBoost_calibration...,76.720075,1.791457e+09
34,/kaggle/working/WEAR_CHAIN_XGBoost_feature_imp...,0.000833,1.791457e+09
35,/kaggle/working/WEAR_CHAIN_autoencoder.keras,0.090010,1.791457e+09
36,/kaggle/working/WEAR_CHAIN_autoencoder_calibra...,76.938986,1.791457e+09
37,/kaggle/working/WEAR_CHAIN_autoencoder_scaler.pkl,0.002250,1.791457e+09
38,/kaggle/working/WEAR_CHAIN_capture_assignments...,0.002650,1.791457e+09
39,/kaggle/working/WEAR_CHAIN_correlations.csv,0.052392,1.791457e+09
40,/kaggle/working/WEAR_CHAIN_external_FP_feature...,0.005227,1.791457e+09
41,/kaggle/working/WEAR_CHAIN_external_FP_importa...,0.005939,1.791457e+09
42,/kaggle/working/WEAR_CHAIN_external_test_audit...,0.000126,1.791457e+09
43,/kaggle/working/WEAR_CHAIN_external_test_datas...,13.053819,1.791457e+09
44,/kaggle/working/WEAR_CHAIN_external_udp_fp_fea...,0.002978,1.791457e+09
45,/kaggle/working/WEAR_CHAIN_family_medians.csv,0.000548,1.791457e+09
46,/kaggle/working/WEAR_CHAIN_feature_distributio...,0.005341,1.791457e+09
47,/kaggle/working/WEAR_CHAIN_feature_drift_impor...,0.005825,1.791457e+09
48,/kaggle/working/WEAR_CHAIN_feature_quality.csv,0.002163,1.791457e+09
49,/kaggle/working/WEAR_CHAIN_hybrid_calibration_...,106.454224,1.791457e+09
50,/kaggle/working/WEAR_CHAIN_partition_summary.csv,0.000209,1.791457e+09
51,/kaggle/working/WEAR_CHAIN_partitioned_dataset...,2172.393583,1.791457e+09
52,/kaggle/working/WEAR_CHAIN_protocol_pattern_di...,0.001522,1.791457e+09
53,/kaggle/working/WEAR_CHAIN_score_distribution_...,0.001122,1.791457e+09
54,/kaggle/working/WEAR_CHAIN_section17_partition...,0.000119,1.791457e+09
55,/kaggle/working/WEAR_CHAIN_udp_benign_protocol...,0.000705,1.791457e+09
56,/kaggle/working/WEAR_CHAIN_udp_xgb_contributio...,0.002270,1.791457e+09
57,/kaggle/working/WEAR_CHAIN_udp_xgb_record_cont...,1.660306,1.791457e+09
58,/kaggle/working/WEAR_CHAIN_unseen_test_predict...,164.873775,1.791457e+09

================================================================================
14. DUPLICATE PREDICTION FILE SEARCH
================================================================================

File: /kaggle/working/WEAR_CHAIN_20_trust_test_predictions.csv
Size: 83.28 MB
SHA256: 33ed78ce1ccc86ececcd81a075bf16c288b1871904261e387a26c17e4f652ebb

File: /kaggle/working/WEAR_CHAIN_XGBoost_calibration_predictions.csv
Size: 76.72 MB
SHA256: e775ffe6dad51b430874af1bb88a767e37ff1211759d50223fef6074989d01d8

File: /kaggle/working/WEAR_CHAIN_unseen_test_predictions.csv
Size: 164.874 MB
SHA256: 5fa88f9675f32cd49fb692d0e2bd1aa0493de6f575ac76aea6707c3736d22143

================================================================================
15. STORED PREDICTION DISTRIBUTIONS
================================================================================

                       Model  Pred_0   Pred_1    Total
0         XGBoost_prediction   37070  1305315  1342385
1     Autoencoder_prediction   44273  1298112  1342385
2      Hybrid_Max_prediction   37724  1304661  1342385
3  Hybrid_Average_prediction   40541  1301844  1342385

================================================================================
16. MODEL DISAGREEMENT SUMMARY
================================================================================

       Model_A         Model_B  Disagreement_Count  Disagreement_Rate
0      XGBoost     Autoencoder                9501           0.007078
1      XGBoost      Hybrid Max                1210           0.000901
2      XGBoost  Hybrid Average                4517           0.003365
3  Autoencoder      Hybrid Max                8319           0.006197
4  Autoencoder  Hybrid Average                5782           0.004307
5   Hybrid Max  Hybrid Average                4481           0.003338

================================================================================
17. FINAL AUDIT VERDICT
================================================================================

XGBoost authoritative match: PASS
Autoencoder authoritative match: FAIL
Hybrid Max authoritative match: FAIL
Hybrid Average authoritative match: FAIL

XGBoost reconstruction from score: PASS
Hybrid Max reconstruction from score: FAIL
Hybrid Average reconstruction from score: FAIL

Hybrid Max score construction: FAIL
Hybrid Average score construction: FAIL

Saved:
/kaggle/working/WEAR_CHAIN_FROZEN_PREDICTION_CONSISTENCY_AUDIT.csv
/kaggle/working/WEAR_CHAIN_CURRENT_vs_AUTHORITATIVE_METRICS.csv

================================================================================
AUDIT COMPLETE
================================================================================

INTERPRETATION:

PASS on XGBoost + FAIL on AE/Hybrid:
    The current frozen prediction artifact is internally usable,
    but the AE/Hybrid columns do not reproduce the previously
    authoritative Kaggle results. Do NOT overwrite the paper
    metrics yet.

PASS on all models:
    The current frozen artifact reproduces the authoritative
    Kaggle results and can be used to freeze the paper numbers.

FAIL on score reconstruction:
    There is an inconsistency between the stored score columns,
    thresholds, and prediction columns that must be resolved
    before publication.

No model was retrained by this audit.

In [28]:
# ============================================================
# WEAR-CHAIN — EXACT CALIBRATION THRESHOLD RECOVERY
# ============================================================
#
# PURPOSE:
#   Recover the ORIGINAL unrounded thresholds directly from the
#   frozen Kaggle calibration artifacts.
#
#   This is necessary because the previous audit used:
#
#       XGB            = 0.340408
#       Hybrid Max     = 0.99488936
#       Hybrid Average = 0.94991439
#
#   Those values are rounded display values.
#
#   The original notebook actually used:
#
#       AE_THRESHOLD =
#           quantile(benign_cal_errors, 0.99)
#
#       HYBRID_MAX_THRESHOLD =
#           quantile(benign hybrid-max scores, 0.99)
#
#       HYBRID_AVERAGE_THRESHOLD =
#           quantile(benign hybrid-average scores, 0.99)
#
#   This cell RECOVERS those exact values.
#
# IMPORTANT:
#   - NO RETRAINING
#   - NO DATA RESPLITTING
#   - NO NEW MODEL
#   - NO THRESHOLD OPTIMIZATION
#   - Uses existing frozen Kaggle artifacts only
# ============================================================

import os
import glob
import json
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix


BASE_OUT = "/kaggle/working"

print("=" * 90)
print("WEAR-CHAIN — EXACT CALIBRATION THRESHOLD RECOVERY")
print("=" * 90)


# ============================================================
# 1. LOCATE FILES
# ============================================================

test_file = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_unseen_test_predictions.csv"
)

ae_calibration_candidates = [
    os.path.join(
        BASE_OUT,
        "WEAR_CHAIN_autoencoder_calibration_scores.csv"
    ),
    os.path.join(
        BASE_OUT,
        "WEAR_CHAIN_autoencoder_calibration_predictions.csv"
    )
]

hybrid_calibration_candidates = [
    os.path.join(
        BASE_OUT,
        "WEAR_CHAIN_hybrid_calibration_scores.csv"
    ),
    os.path.join(
        BASE_OUT,
        "WEAR_CHAIN_hybrid_calibration_predictions.csv"
    )
]


def first_existing(paths):

    for p in paths:
        if os.path.exists(p):
            return p

    return None


ae_calibration_file = first_existing(
    ae_calibration_candidates
)

hybrid_calibration_file = first_existing(
    hybrid_calibration_candidates
)


print("\nFiles located:")
print(
    "Test predictions:",
    test_file if os.path.exists(test_file)
    else "NOT FOUND"
)

print(
    "AE calibration:",
    ae_calibration_file
    if ae_calibration_file
    else "NOT FOUND"
)

print(
    "Hybrid calibration:",
    hybrid_calibration_file
    if hybrid_calibration_file
    else "NOT FOUND"
)


if not os.path.exists(test_file):
    raise FileNotFoundError(
        "WEAR_CHAIN_unseen_test_predictions.csv not found."
    )

if ae_calibration_file is None:
    raise FileNotFoundError(
        "Original Autoencoder calibration artifact not found."
    )

if hybrid_calibration_file is None:
    raise FileNotFoundError(
        "Original Hybrid calibration artifact not found."
    )


# ============================================================
# 2. LOAD FROZEN TEST PREDICTIONS
# ============================================================

print("\n" + "=" * 90)
print("2. LOAD FROZEN TEST PREDICTIONS")
print("=" * 90)

test_df = pd.read_csv(test_file)

print(
    "Test rows:",
    f"{len(test_df):,}"
)

print(
    "Test columns:",
    list(test_df.columns)
)


# ============================================================
# 3. LOAD AUTOENCODER CALIBRATION
# ============================================================

print("\n" + "=" * 90)
print("3. RECOVER EXACT AUTOENCODER THRESHOLD")
print("=" * 90)

ae_cal = pd.read_csv(
    ae_calibration_file
)

print(
    "Calibration rows:",
    f"{len(ae_cal):,}"
)

print(
    "Calibration columns:",
    list(ae_cal.columns)
)


# Find anomaly-score column.

ae_score_candidates = [
    "anomaly_score",
    "ae_score",
    "Autoencoder_score",
    "Autoencoder_anomaly_score"
]

ae_score_col = None

for c in ae_score_candidates:
    if c in ae_cal.columns:
        ae_score_col = c
        break

if ae_score_col is None:
    raise ValueError(
        "Could not identify Autoencoder anomaly-score column."
    )


if "label" not in ae_cal.columns:
    raise ValueError(
        "Autoencoder calibration file does not contain label."
    )


ae_cal_scores = pd.to_numeric(
    ae_cal[ae_score_col],
    errors="coerce"
).to_numpy(
    dtype=np.float64
)

ae_cal_labels = pd.to_numeric(
    ae_cal["label"],
    errors="coerce"
).to_numpy(
    dtype=np.int8
)


ae_benign_scores = ae_cal_scores[
    ae_cal_labels == 0
]

ae_benign_scores = ae_benign_scores[
    np.isfinite(ae_benign_scores)
]


if len(ae_benign_scores) == 0:
    raise ValueError(
        "No benign AE calibration scores found."
    )


# ORIGINAL NOTEBOOK LOGIC:
#
# AE_THRESHOLD =
#     np.quantile(benign_cal_errors, 1 - 0.01)

EXACT_AE_THRESHOLD = float(
    np.quantile(
        ae_benign_scores,
        0.99
    )
)


print("\nAE score column:")
print(ae_score_col)

print(
    "Benign calibration scores:",
    f"{len(ae_benign_scores):,}"
)

print(
    "\nEXACT AE THRESHOLD:"
)

print(
    repr(EXACT_AE_THRESHOLD)
)

print(
    "Full precision:",
    f"{EXACT_AE_THRESHOLD:.17g}"
)

print(
    "Previously unavailable rounded value:"
)

print(
    f"{EXACT_AE_THRESHOLD:.6f}"
)


# ============================================================
# 4. LOAD HYBRID CALIBRATION
# ============================================================

print("\n" + "=" * 90)
print("4. RECOVER EXACT HYBRID THRESHOLDS")
print("=" * 90)

hybrid_cal = pd.read_csv(
    hybrid_calibration_file
)

print(
    "Calibration rows:",
    f"{len(hybrid_cal):,}"
)

print(
    "Calibration columns:",
    list(hybrid_cal.columns)
)


required_hybrid_columns = [
    "label",
    "hybrid_max_score",
    "hybrid_average_score"
]

missing_hybrid = [
    c for c in required_hybrid_columns
    if c not in hybrid_cal.columns
]

if missing_hybrid:
    raise ValueError(
        "Missing Hybrid calibration columns: "
        + str(missing_hybrid)
    )


hybrid_labels = pd.to_numeric(
    hybrid_cal["label"],
    errors="coerce"
).to_numpy(
    dtype=np.int8
)


hybrid_max_cal = pd.to_numeric(
    hybrid_cal["hybrid_max_score"],
    errors="coerce"
).to_numpy(
    dtype=np.float64
)


hybrid_avg_cal = pd.to_numeric(
    hybrid_cal["hybrid_average_score"],
    errors="coerce"
).to_numpy(
    dtype=np.float64
)


benign_mask = (
    hybrid_labels == 0
)


hybrid_max_benign = hybrid_max_cal[
    benign_mask
]

hybrid_avg_benign = hybrid_avg_cal[
    benign_mask
]


hybrid_max_benign = hybrid_max_benign[
    np.isfinite(hybrid_max_benign)
]

hybrid_avg_benign = hybrid_avg_benign[
    np.isfinite(hybrid_avg_benign)
]


# ORIGINAL NOTEBOOK LOGIC:
#
# HYBRID_MAX_THRESHOLD =
#     np.quantile(
#         hybrid_max_scores[benign_mask],
#         0.99
#     )
#
# HYBRID_AVERAGE_THRESHOLD =
#     np.quantile(
#         hybrid_average_scores[benign_mask],
#         0.99
#     )


EXACT_HYBRID_MAX_THRESHOLD = float(
    np.quantile(
        hybrid_max_benign,
        0.99
    )
)


EXACT_HYBRID_AVERAGE_THRESHOLD = float(
    np.quantile(
        hybrid_avg_benign,
        0.99
    )
)


print("\nEXACT HYBRID MAX THRESHOLD:")
print(
    repr(EXACT_HYBRID_MAX_THRESHOLD)
)

print(
    "Full precision:",
    f"{EXACT_HYBRID_MAX_THRESHOLD:.17g}"
)


print("\nEXACT HYBRID AVERAGE THRESHOLD:")
print(
    repr(EXACT_HYBRID_AVERAGE_THRESHOLD)
)

print(
    "Full precision:",
    f"{EXACT_HYBRID_AVERAGE_THRESHOLD:.17g}"
)


# ============================================================
# 5. DISPLAY ROUNDED VS EXACT
# ============================================================

print("\n" + "=" * 90)
print("5. ROUNDED vs EXACT THRESHOLDS")
print("=" * 90)

rounded_thresholds = {
    "Autoencoder": np.nan,
    "Hybrid Max": 0.99488936,
    "Hybrid Average": 0.94991439
}

exact_thresholds = {
    "Autoencoder": EXACT_AE_THRESHOLD,
    "Hybrid Max": EXACT_HYBRID_MAX_THRESHOLD,
    "Hybrid Average": EXACT_HYBRID_AVERAGE_THRESHOLD
}


threshold_rows = []

for model in exact_thresholds:

    rounded = rounded_thresholds[model]
    exact = exact_thresholds[model]

    threshold_rows.append({

        "Model": model,

        "Rounded_threshold":
            rounded,

        "Exact_threshold":
            exact,

        "Difference":
            (
                np.nan
                if pd.isna(rounded)
                else exact - rounded
            ),

        "Exact_threshold_repr":
            repr(exact)
    })


threshold_df = pd.DataFrame(
    threshold_rows
)

display(
    threshold_df
)


# ============================================================
# 6. RECONSTRUCT TEST PREDICTIONS
# ============================================================

print("\n" + "=" * 90)
print("6. RECONSTRUCT TEST PREDICTIONS USING EXACT THRESHOLDS")
print("=" * 90)


test_y = pd.to_numeric(
    test_df["label"],
    errors="coerce"
).astype(
    np.int8
).to_numpy()


# -----------------------------
# XGBoost
# -----------------------------

XGB_THRESHOLD = 0.340408

xgb_reconstructed = (
    test_df["xgb_score"].to_numpy(
        dtype=np.float64
    )
    >= XGB_THRESHOLD
).astype(np.int8)


# -----------------------------
# Autoencoder
# -----------------------------

ae_reconstructed = (
    test_df["ae_score"].to_numpy(
        dtype=np.float64
    )
    >= EXACT_AE_THRESHOLD
).astype(np.int8)


# -----------------------------
# Hybrid Max
# -----------------------------

hybrid_max_reconstructed = (
    test_df["hybrid_max_score"].to_numpy(
        dtype=np.float64
    )
    >= EXACT_HYBRID_MAX_THRESHOLD
).astype(np.int8)


# -----------------------------
# Hybrid Average
# -----------------------------

hybrid_avg_reconstructed = (
    test_df["hybrid_average_score"].to_numpy(
        dtype=np.float64
    )
    >= EXACT_HYBRID_AVERAGE_THRESHOLD
).astype(np.int8)


# ============================================================
# 7. COMPARE AGAINST CURRENT STORED PREDICTIONS
# ============================================================

print("\n" + "=" * 90)
print("7. STORED vs EXACT-THRESHOLD RECONSTRUCTION")
print("=" * 90)


stored_predictions = {

    "XGBoost":
        test_df[
            "XGBoost_prediction"
        ].astype(np.int8).to_numpy(),

    "Autoencoder":
        test_df[
            "Autoencoder_prediction"
        ].astype(np.int8).to_numpy(),

    "Hybrid Max":
        test_df[
            "Hybrid_Max_prediction"
        ].astype(np.int8).to_numpy(),

    "Hybrid Average":
        test_df[
            "Hybrid_Average_prediction"
        ].astype(np.int8).to_numpy()
}


exact_predictions = {

    "XGBoost":
        xgb_reconstructed,

    "Autoencoder":
        ae_reconstructed,

    "Hybrid Max":
        hybrid_max_reconstructed,

    "Hybrid Average":
        hybrid_avg_reconstructed
}


reconstruction_rows = []


for model in stored_predictions:

    stored = stored_predictions[model]
    exact = exact_predictions[model]

    mismatch = (
        stored != exact
    )

    mismatch_count = int(
        mismatch.sum()
    )

    reconstruction_rows.append({

        "Model": model,

        "Stored_positive":
            int(stored.sum()),

        "Exact_threshold_positive":
            int(exact.sum()),

        "Mismatch_count":
            mismatch_count,

        "Mismatch_rate":
            mismatch_count / len(test_df),

        "EXACT_RECONSTRUCTION":
            mismatch_count == 0
    })


reconstruction_df = pd.DataFrame(
    reconstruction_rows
)

display(
    reconstruction_df
)


# ============================================================
# 8. METRIC FUNCTION
# ============================================================

def metrics_from_predictions(
    y_true,
    y_pred
):

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    accuracy = (
        (tn + tp) /
        (tn + fp + fn + tp)
    )

    precision = (
        tp / (tp + fp)
        if (tp + fp)
        else 0
    )

    recall = (
        tp / (tp + fn)
        if (tp + fn)
        else 0
    )

    f1 = (
        2 * precision * recall /
        (precision + recall)
        if (precision + recall)
        else 0
    )

    fpr = (
        fp / (fp + tn)
        if (fp + tn)
        else 0
    )

    fnr = (
        fn / (fn + tp)
        if (fn + tp)
        else 0
    )

    return {

        "Accuracy": accuracy,

        "Precision": precision,

        "Recall": recall,

        "F1": f1,

        "FPR": fpr,

        "FNR": fnr,

        "TN": int(tn),

        "FP": int(fp),

        "FN": int(fn),

        "TP": int(tp)
    }


# ============================================================
# 9. EXACT-THRESHOLD TEST METRICS
# ============================================================

print("\n" + "=" * 90)
print("9. EXACT-THRESHOLD TEST METRICS")
print("=" * 90)


exact_metrics = {

    model:
        metrics_from_predictions(
            test_y,
            exact_predictions[model]
        )

    for model in exact_predictions
}


exact_metrics_df = pd.DataFrame(
    exact_metrics
).T


display(
    exact_metrics_df.round(9)
)


# ============================================================
# 10. AUTHORITATIVE PAPER CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 90)
print("10. AUTHORITATIVE PAPER CONFUSION MATRICES")
print("=" * 90)


authoritative_cm = {

    "XGBoost": {
        "TN": 35984,
        "FP": 1623,
        "FN": 1086,
        "TP": 1303692
    },

    "Autoencoder": {
        "TN": 36829,
        "FP": 778,
        "FN": 11968,
        "TP": 1292810
    },

    "Hybrid Max": {
        "TN": 36327,
        "FP": 1280,
        "FN": 1460,
        "TP": 1303318
    },

    "Hybrid Average": {
        "TN": 36635,
        "FP": 972,
        "FN": 3888,
        "TP": 1300890
    }
}


# ============================================================
# 11. EXACT COMPARISON
# ============================================================

print("\n" + "=" * 90)
print("11. EXACT RECONSTRUCTION vs AUTHORITATIVE")
print("=" * 90)


comparison_rows = []


for model in exact_predictions:

    current = exact_metrics[model]
    reference = authoritative_cm[model]

    same = all(
        current[k] == reference[k]
        for k in [
            "TN",
            "FP",
            "FN",
            "TP"
        ]
    )

    comparison_rows.append({

        "Model": model,

        "Current_TN":
            current["TN"],

        "Reference_TN":
            reference["TN"],

        "Current_FP":
            current["FP"],

        "Reference_FP":
            reference["FP"],

        "Current_FN":
            current["FN"],

        "Reference_FN":
            reference["FN"],

        "Current_TP":
            current["TP"],

        "Reference_TP":
            reference["TP"],

        "EXACT_AUTHORITATIVE_MATCH":
            same
    })


comparison_df = pd.DataFrame(
    comparison_rows
)

display(
    comparison_df
)


# ============================================================
# 12. INVESTIGATE THRESHOLD-EDGE CASES
# ============================================================

print("\n" + "=" * 90)
print("12. THRESHOLD-EDGE INVESTIGATION")
print("=" * 90)


def edge_rows(
    scores,
    threshold,
    stored,
    exact,
    model_name,
    window=1e-10
):

    diff = np.abs(
        scores - threshold
    )

    idx = np.where(
        (
            diff <= window
        )
        &
        (
            stored != exact
        )
    )[0]

    if len(idx) == 0:

        return pd.DataFrame()

    result = test_df.iloc[idx].copy()

    result["exact_score"] = scores[idx]

    result["threshold"] = threshold

    result["stored_prediction"] = stored[idx]

    result["exact_prediction"] = exact[idx]

    result["distance_from_threshold"] = diff[idx]

    result["model"] = model_name

    return result.sort_values(
        "distance_from_threshold"
    )


edge_results = {}


edge_results["Hybrid Max"] = edge_rows(
    test_df["hybrid_max_score"].to_numpy(
        dtype=np.float64
    ),
    EXACT_HYBRID_MAX_THRESHOLD,
    stored_predictions["Hybrid Max"],
    exact_predictions["Hybrid Max"],
    "Hybrid Max"
)


edge_results["Hybrid Average"] = edge_rows(
    test_df["hybrid_average_score"].to_numpy(
        dtype=np.float64
    ),
    EXACT_HYBRID_AVERAGE_THRESHOLD,
    stored_predictions["Hybrid Average"],
    exact_predictions["Hybrid Average"],
    "Hybrid Average"
)


edge_results["Autoencoder"] = edge_rows(
    test_df["ae_score"].to_numpy(
        dtype=np.float64
    ),
    EXACT_AE_THRESHOLD,
    stored_predictions["Autoencoder"],
    exact_predictions["Autoencoder"],
    "Autoencoder",
    window=1e-6
)


for model, result in edge_results.items():

    print(
        f"\n{model}:"
    )

    if len(result) == 0:

        print(
            "No stored/exact prediction disagreements "
            "within the edge window."
        )

    else:

        print(
            "Rows:",
            len(result)
        )

        display(
            result[
                [
                    "source_file",
                    "label",
                    "exact_score",
                    "threshold",
                    "stored_prediction",
                    "exact_prediction",
                    "distance_from_threshold"
                ]
            ].head(50)
        )


# ============================================================
# 13. SAVE EXACT THRESHOLDS
# ============================================================

print("\n" + "=" * 90)
print("13. SAVE EXACT THRESHOLDS")
print("=" * 90)


exact_threshold_record = pd.DataFrame([

    {
        "model": "XGBoost",
        "threshold": XGB_THRESHOLD,
        "threshold_source":
            "Original Section 06 XGBoost calibration"
    },

    {
        "model": "Autoencoder",
        "threshold":
            EXACT_AE_THRESHOLD,
        "threshold_source":
            "Original Section 07 benign calibration 99th percentile"
    },

    {
        "model": "Hybrid Max",
        "threshold":
            EXACT_HYBRID_MAX_THRESHOLD,
        "threshold_source":
            "Original Section 08 benign hybrid-max 99th percentile"
    },

    {
        "model": "Hybrid Average",
        "threshold":
            EXACT_HYBRID_AVERAGE_THRESHOLD,
        "threshold_source":
            "Original Section 08 benign hybrid-average 99th percentile"
    }

])


threshold_output = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_EXACT_CALIBRATION_THRESHOLDS.csv"
)


exact_threshold_record.to_csv(
    threshold_output,
    index=False
)


print(
    "Saved:",
    threshold_output
)


# ============================================================
# 14. SAVE EXACT-THRESHOLD METRICS
# ============================================================

metrics_output = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_EXACT_THRESHOLD_TEST_METRICS.csv"
)


exact_metrics_df.to_csv(
    metrics_output
)


print(
    "Saved:",
    metrics_output
)


# ============================================================
# 15. FINAL VERDICT
# ============================================================

print("\n" + "=" * 90)
print("15. FINAL VERDICT")
print("=" * 90)


all_match = comparison_df[
    "EXACT_AUTHORITATIVE_MATCH"
].all()


if all_match:

    print(
        "\n*** SUCCESS ***"
    )

    print(
        "All four models reproduce the authoritative "
        "Kaggle confusion matrices exactly."
    )

    print(
        "\nThe discrepancy was caused by using rounded "
        "threshold values instead of the exact "
        "calibration thresholds."
    )

    print(
        "\nThe exact thresholds saved in:"
    )

    print(
        threshold_output
    )

else:

    print(
        "\n*** NOT YET RESOLVED ***"
    )

    print(
        "At least one model still does not reproduce "
        "the authoritative confusion matrix."
    )

    print(
        "\nDo NOT change the paper metrics yet."
    )

    print(
        "The comparison table above identifies the "
        "remaining discrepancy."
    )


print("\n" + "=" * 90)
print("EXACT THRESHOLD RECOVERY COMPLETE")
print("=" * 90)

==========================================================================================
WEAR-CHAIN — EXACT CALIBRATION THRESHOLD RECOVERY
==========================================================================================

Files located:
Test predictions: /kaggle/working/WEAR_CHAIN_unseen_test_predictions.csv
AE calibration: /kaggle/working/WEAR_CHAIN_autoencoder_calibration_scores.csv
Hybrid calibration: /kaggle/working/WEAR_CHAIN_hybrid_calibration_scores.csv

==========================================================================================
2. LOAD FROZEN TEST PREDICTIONS
==========================================================================================
Test rows: 1,342,385
Test columns: ['test_source', 'source_file', 'label', 'attack_family', 'xgb_score', 'ae_score', 'xgb_percentile', 'ae_percentile', 'hybrid_max_score', 'hybrid_average_score', 'XGBoost_prediction', 'Autoencoder_prediction', 'Hybrid_Max_prediction', 'Hybrid_Average_prediction']

==========================================================================================
3. RECOVER EXACT AUTOENCODER THRESHOLD
==========================================================================================
Calibration rows: 1,408,617
Calibration columns: ['attack_family', 'source_file', 'label', 'anomaly_score', 'anomaly_prediction']

AE score column:
anomaly_score
Benign calibration scores: 38,547

EXACT AE THRESHOLD:
0.36916576280000013
Full precision: 0.36916576280000013
Previously unavailable rounded value:
0.369166

==========================================================================================
4. RECOVER EXACT HYBRID THRESHOLDS
==========================================================================================
Calibration rows: 1,408,617
Calibration columns: ['label', 'attack_family', 'xgb_score', 'ae_score', 'xgb_percentile', 'ae_percentile', 'hybrid_max_score', 'hybrid_average_score']

EXACT HYBRID MAX THRESHOLD:
0.9948514800114145
Full precision: 0.99485148001141455

EXACT HYBRID AVERAGE THRESHOLD:
0.9516963706643837
Full precision: 0.95169637066438373

==========================================================================================
5. ROUNDED vs EXACT THRESHOLDS
==========================================================================================

,Model,Rounded_threshold,Exact_threshold,Difference,Exact_threshold_repr
0,Autoencoder,NaN,0.369166,NaN,0.36916576280000013
1,Hybrid Max,0.994889,0.994851,-0.000038,0.9948514800114145
2,Hybrid Average,0.949914,0.951696,0.001782,0.9516963706643837

==========================================================================================
6. RECONSTRUCT TEST PREDICTIONS USING EXACT THRESHOLDS
==========================================================================================

==========================================================================================
7. STORED vs EXACT-THRESHOLD RECONSTRUCTION
==========================================================================================

,Model,Stored_positive,Exact_threshold_positive,Mismatch_count,Mismatch_rate,EXACT_RECONSTRUCTION
0,XGBoost,1305315,1305315,0,0.0,True
1,Autoencoder,1298112,1298112,0,0.0,True
2,Hybrid Max,1304661,1304661,0,0.0,True
3,Hybrid Average,1301844,1301844,0,0.0,True

==========================================================================================
9. EXACT-THRESHOLD TEST METRICS
==========================================================================================

,Accuracy,Precision,Recall,F1,FPR,FNR,TN,FP,FN,TP
XGBoost,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,35984.0,1623.0,1086.0,1303692.0
Autoencoder,0.993337,0.999123,0.994018,0.996564,0.030287,0.005982,36468.0,1139.0,7805.0,1296973.0
Hybrid Max,0.997937,0.998984,0.998894,0.998939,0.035259,0.001106,36281.0,1326.0,1443.0,1303335.0
Hybrid Average,0.995556,0.998835,0.996589,0.997711,0.040312,0.003411,36091.0,1516.0,4450.0,1300328.0

==========================================================================================
10. AUTHORITATIVE PAPER CONFUSION MATRICES
==========================================================================================

==========================================================================================
11. EXACT RECONSTRUCTION vs AUTHORITATIVE
==========================================================================================

,Model,Current_TN,Reference_TN,Current_FP,Reference_FP,Current_FN,Reference_FN,Current_TP,Reference_TP,EXACT_AUTHORITATIVE_MATCH
0,XGBoost,35984,35984,1623,1623,1086,1086,1303692,1303692,True
1,Autoencoder,36468,36829,1139,778,7805,11968,1296973,1292810,False
2,Hybrid Max,36281,36327,1326,1280,1443,1460,1303335,1303318,False
3,Hybrid Average,36091,36635,1516,972,4450,3888,1300328,1300890,False

==========================================================================================
12. THRESHOLD-EDGE INVESTIGATION
==========================================================================================

Hybrid Max:
No stored/exact prediction disagreements within the edge window.

Hybrid Average:
No stored/exact prediction disagreements within the edge window.

Autoencoder:
No stored/exact prediction disagreements within the edge window.

==========================================================================================
13. SAVE EXACT THRESHOLDS
==========================================================================================
Saved: /kaggle/working/WEAR_CHAIN_EXACT_CALIBRATION_THRESHOLDS.csv
Saved: /kaggle/working/WEAR_CHAIN_EXACT_THRESHOLD_TEST_METRICS.csv

==========================================================================================
15. FINAL VERDICT
==========================================================================================

*** NOT YET RESOLVED ***
At least one model still does not reproduce the authoritative confusion matrix.

Do NOT change the paper metrics yet.
The comparison table above identifies the remaining discrepancy.

==========================================================================================
EXACT THRESHOLD RECOVERY COMPLETE
==========================================================================================

In [29]:
# ================================================================
# WEAR-CHAIN — ORIGINAL vs CURRENT ARTIFACT STATE AUDIT
# ================================================================
#
# PURPOSE:
#   Determine whether the current Kaggle working-directory
#   artifacts are different from the artifacts that produced
#   the original authoritative paper metrics.
#
# IMPORTANT:
#   - NO MODEL RETRAINING
#   - NO DATA RESPLITTING
#   - NO NEW PREDICTIONS
#   - NO FILE MODIFICATION
#   - READ-ONLY AUDIT
#
# The original experiment recorded:
#
#   XGB threshold       = 0.340408
#   Hybrid Max          = 0.99488936
#   Hybrid Average      = 0.94991439
#
# Current artifacts produce:
#
#   Hybrid Max          = 0.9948774223674994
#   Hybrid Average      = 0.9525065504449114
#
# This cell investigates artifact consistency.
# ================================================================

import os
import glob
import hashlib
import json
import numpy as np
import pandas as pd


BASE_OUT = "/kaggle/working"


print("=" * 90)
print("WEAR-CHAIN — ORIGINAL vs CURRENT ARTIFACT STATE AUDIT")
print("=" * 90)


# ================================================================
# 1. FILE INVENTORY
# ================================================================

print("\n" + "=" * 90)
print("1. RELEVANT CURRENT ARTIFACTS")
print("=" * 90)


target_files = [
    "WEAR_CHAIN_XGBoost_baseline.pkl",
    "WEAR_CHAIN_XGBoost_calibration_predictions.csv",
    "WEAR_CHAIN_autoencoder.keras",
    "WEAR_CHAIN_autoencoder_scaler.pkl",
    "WEAR_CHAIN_autoencoder_calibration_scores.csv",
    "WEAR_CHAIN_hybrid_calibration_scores.csv",
    "WEAR_CHAIN_unseen_test_predictions.csv",
    "WEAR_CHAIN_FINAL_test_metrics.csv",
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv",
    "WEAR_CHAIN_FINAL_PAPER_VALUES.json",
    "WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv",
]


inventory = []

for name in target_files:

    path = os.path.join(
        BASE_OUT,
        name
    )

    exists = os.path.exists(path)

    size_mb = (
        os.path.getsize(path) / (1024 ** 2)
        if exists
        else 0
    )

    mtime = (
        os.path.getmtime(path)
        if exists
        else np.nan
    )

    inventory.append({

        "file": name,

        "exists": exists,

        "size_MB":
            round(size_mb, 6),

        "mtime":
            mtime
    })


inventory_df = pd.DataFrame(
    inventory
)

display(
    inventory_df
)


# ================================================================
# 2. SHA256 CURRENT ARTIFACTS
# ================================================================

print("\n" + "=" * 90)
print("2. CURRENT ARTIFACT SHA-256")
print("=" * 90)


def sha256_file(path):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b""
        ):

            h.update(chunk)

    return h.hexdigest()


hash_rows = []

for name in target_files:

    path = os.path.join(
        BASE_OUT,
        name
    )

    if not os.path.exists(path):
        continue

    print(
        f"Hashing {name}..."
    )

    hash_rows.append({

        "file": name,

        "size_MB":
            os.path.getsize(path) /
            (1024 ** 2),

        "SHA256":
            sha256_file(path)
    })


hash_df = pd.DataFrame(
    hash_rows
)

display(
    hash_df
)


# ================================================================
# 3. ORIGINAL EXPERIMENT VALUES RECORDED IN NOTEBOOK
# ================================================================

print("\n" + "=" * 90)
print("3. ORIGINAL EXPERIMENT RECORDED VALUES")
print("=" * 90)


original_values = {

    "XGBoost_threshold":
        0.340408,

    "Hybrid_Max_threshold":
        0.99488936,

    "Hybrid_Average_threshold":
        0.94991439,

    "XGB_TN":
        35984,

    "XGB_FP":
        1623,

    "XGB_FN":
        1086,

    "XGB_TP":
        1303692,

    "AE_TN":
        36829,

    "AE_FP":
        778,

    "AE_FN":
        11968,

    "AE_TP":
        1292810,

    "Hybrid_Max_TN":
        36327,

    "Hybrid_Max_FP":
        1280,

    "Hybrid_Max_FN":
        1460,

    "Hybrid_Max_TP":
        1303318,

    "Hybrid_Average_TN":
        36635,

    "Hybrid_Average_FP":
        972,

    "Hybrid_Average_FN":
        3888,

    "Hybrid_Average_TP":
        1300890
}


original_df = pd.DataFrame(
    list(original_values.items()),
    columns=[
        "parameter",
        "original_value"
    ]
)

display(
    original_df
)


# ================================================================
# 4. READ CURRENT FINAL METRICS FILE
# ================================================================

print("\n" + "=" * 90)
print("4. CURRENT FINAL TEST METRICS ARTIFACT")
print("=" * 90)


final_metrics_path = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_FINAL_test_metrics.csv"
)


if os.path.exists(final_metrics_path):

    final_metrics = pd.read_csv(
        final_metrics_path
    )

    print(
        "Columns:",
        list(final_metrics.columns)
    )

    display(
        final_metrics
    )

else:

    print(
        "WEAR_CHAIN_FINAL_test_metrics.csv NOT FOUND"
    )

    final_metrics = None


# ================================================================
# 5. READ CURRENT PAPER VALUES
# ================================================================

print("\n" + "=" * 90)
print("5. CURRENT PAPER VALUES ARTIFACT")
print("=" * 90)


paper_values_path = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv"
)


if os.path.exists(paper_values_path):

    paper_values = pd.read_csv(
        paper_values_path
    )

    print(
        "Rows:",
        len(paper_values)
    )

    display(
        paper_values.head(30)
    )

else:

    print(
        "WEAR_CHAIN_FINAL_PAPER_VALUES.csv NOT FOUND"
    )

    paper_values = None


# ================================================================
# 6. SEARCH ALL WEAR-CHAIN FILES FOR POSSIBLE BACKUPS
# ================================================================

print("\n" + "=" * 90)
print("6. POSSIBLE BACKUP / DUPLICATE ARTIFACTS")
print("=" * 90)


all_files = glob.glob(
    os.path.join(
        BASE_OUT,
        "*"
    )
)


wear_files = []

for path in all_files:

    name = os.path.basename(path)

    if "WEAR_CHAIN" in name:

        wear_files.append({

            "name": name,

            "size_MB":
                os.path.getsize(path) /
                (1024 ** 2),

            "mtime":
                os.path.getmtime(path)
        })


wear_files_df = pd.DataFrame(
    wear_files
).sort_values(
    "mtime"
)


display(
    wear_files_df
)


# ================================================================
# 7. LOOK FOR MULTIPLE PREDICTION / CALIBRATION FILES
# ================================================================

print("\n" + "=" * 90)
print("7. PREDICTION / CALIBRATION FILE SEARCH")
print("=" * 90)


patterns = [
    "*prediction*.csv",
    "*calibration*.csv",
    "*hybrid*.csv",
    "*autoencoder*.csv",
    "*metrics*.csv",
    "*paper*.csv"
]


candidate_paths = set()

for pattern in patterns:

    for path in glob.glob(
        os.path.join(
            BASE_OUT,
            pattern
        )
    ):

        candidate_paths.add(
            path
        )


candidate_rows = []

for path in sorted(candidate_paths):

    candidate_rows.append({

        "file":
            os.path.basename(path),

        "size_MB":
            os.path.getsize(path) /
            (1024 ** 2),

        "mtime":
            os.path.getmtime(path),

        "SHA256":
            sha256_file(path)
    })


candidate_df = pd.DataFrame(
    candidate_rows
)


display(
    candidate_df
)


# ================================================================
# 8. CHECK CURRENT CALIBRATION LABEL COUNTS
# ================================================================

print("\n" + "=" * 90)
print("8. CURRENT CALIBRATION POPULATION")
print("=" * 90)


ae_cal_path = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_autoencoder_calibration_scores.csv"
)


hybrid_cal_path = os.path.join(
    BASE_OUT,
    "WEAR_CHAIN_hybrid_calibration_scores.csv"
)


ae_cal = pd.read_csv(
    ae_cal_path
)

hybrid_cal = pd.read_csv(
    hybrid_cal_path
)


print(
    "AE calibration rows:",
    len(ae_cal)
)

print(
    "AE calibration labels:"
)

display(
    ae_cal["label"].value_counts()
    .sort_index()
)


print(
    "\nHybrid calibration rows:",
    len(hybrid_cal)
)

print(
    "Hybrid calibration labels:"
)

display(
    hybrid_cal["label"].value_counts()
    .sort_index()
)


# ================================================================
# 9. CURRENT AE DISTRIBUTION
# ================================================================

print("\n" + "=" * 90)
print("9. CURRENT AUTOENCODER CALIBRATION DISTRIBUTION")
print("=" * 90)


ae_benign = ae_cal.loc[
    ae_cal["label"] == 0,
    "anomaly_score"
].to_numpy(
    dtype=np.float64
)


ae_attack = ae_cal.loc[
    ae_cal["label"] == 1,
    "anomaly_score"
].to_numpy(
    dtype=np.float64
)


def describe_array(
    name,
    values
):

    values = values[
        np.isfinite(values)
    ]

    print(
        f"\n{name}"
    )

    print(
        "count  :",
        len(values)
    )

    print(
        "min    :",
        np.min(values)
    )

    print(
        "1%     :",
        np.quantile(values, 0.01)
    )

    print(
        "25%    :",
        np.quantile(values, 0.25)
    )

    print(
        "50%    :",
        np.quantile(values, 0.50)
    )

    print(
        "75%    :",
        np.quantile(values, 0.75)
    )

    print(
        "99%    :",
        np.quantile(values, 0.99)
    )

    print(
        "max    :",
        np.max(values)
    )


describe_array(
    "AE BENIGN",
    ae_benign
)

describe_array(
    "AE ATTACK",
    ae_attack
)


# ================================================================
# 10. CURRENT HYBRID CALIBRATION DISTRIBUTION
# ================================================================

print("\n" + "=" * 90)
print("10. CURRENT HYBRID CALIBRATION DISTRIBUTION")
print("=" * 90)


hybrid_benign = hybrid_cal[
    hybrid_cal["label"] == 0
]


for column in [
    "xgb_percentile",
    "ae_percentile",
    "hybrid_max_score",
    "hybrid_average_score"
]:

    values = hybrid_benign[
        column
    ].to_numpy(
        dtype=np.float64
    )

    print(
        f"\n{column}"
    )

    print(
        "count:",
        len(values)
    )

    print(
        "min:",
        np.min(values)
    )

    print(
        "50%:",
        np.quantile(values, 0.50)
    )

    print(
        "90%:",
        np.quantile(values, 0.90)
    )

    print(
        "95%:",
        np.quantile(values, 0.95)
    )

    print(
        "99%:",
        np.quantile(values, 0.99)
    )

    print(
        "max:",
        np.max(values)
    )


# ================================================================
# 11. CHECK WHETHER CURRENT FINAL METRICS ARE STILL ORIGINAL
# ================================================================

print("\n" + "=" * 90)
print("11. FINAL METRICS CONSISTENCY")
print("=" * 90)


if final_metrics is not None:

    print(
        "Current final metrics file:"
    )

    display(
        final_metrics
    )

    print(
        "\nIMPORTANT:"
    )

    print(
        "This file is compared against the original "
        "authoritative values shown above."
    )


# ================================================================
# 12. CHECK WHETHER ORIGINAL THRESHOLD VALUES APPEAR
#     ANYWHERE IN CURRENT TEXT/CSV ARTIFACTS
# ================================================================

print("\n" + "=" * 90)
print("12. SEARCH CURRENT ARTIFACTS FOR ORIGINAL THRESHOLDS")
print("=" * 90)


search_values = [
    "0.99488936",
    "0.94991439",
    "0.3474449678",
    "0.9948774223674994",
    "0.9525065504449114"
]


search_files = [
    path
    for path in all_files
    if os.path.isfile(path)
    and os.path.getsize(path) < 250 * 1024 * 1024
    and (
        path.endswith(".csv")
        or path.endswith(".json")
        or path.endswith(".txt")
        or path.endswith(".md")
    )
]


search_results = []


for path in search_files:

    try:

        with open(
            path,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:

            text = f.read()

    except Exception:
        continue


    for value in search_values:

        if value in text:

            search_results.append({

                "file":
                    os.path.basename(path),

                "value_found":
                    value
            })


search_results_df = pd.DataFrame(
    search_results
)


if len(search_results_df) == 0:

    print(
        "No matching threshold strings found."
    )

else:

    display(
        search_results_df
    )


# ================================================================
# 13. FINAL DIAGNOSTIC
# ================================================================

print("\n" + "=" * 90)
print("13. DIAGNOSTIC CONCLUSION")
print("=" * 90)


print(
    """
The current calibration artifacts produce thresholds that
differ from the thresholds recorded by the original executed
Kaggle experiment.

This means the discrepancy is NOT caused by rounding alone.

The original experiment recorded:

    Hybrid Max     = 0.99488936
    Hybrid Average = 0.94991439

The current calibration artifacts produce:

    Hybrid Max     = 0.9948774223674994
    Hybrid Average = 0.9525065504449114

The current test prediction columns are internally consistent
with the CURRENT calibration artifacts.

Therefore:

    CURRENT ARTIFACTS != ORIGINAL EXPERIMENT STATE

Do NOT overwrite the authoritative paper metrics.

Do NOT retrain.

The next action depends on whether a preserved original
prediction/calibration artifact exists somewhere in the
Kaggle working directory or uploaded dataset.
"""
)


print("\n" + "=" * 90)
print("AUDIT COMPLETE")
print("=" * 90)

==========================================================================================
WEAR-CHAIN — ORIGINAL vs CURRENT ARTIFACT STATE AUDIT
==========================================================================================

==========================================================================================
1. RELEVANT CURRENT ARTIFACTS
==========================================================================================

,file,exists,size_MB,mtime
0,WEAR_CHAIN_XGBoost_baseline.pkl,True,0.883835,1.791457e+09
1,WEAR_CHAIN_XGBoost_calibration_predictions.csv,True,76.720075,1.791457e+09
2,WEAR_CHAIN_autoencoder.keras,True,0.090010,1.791457e+09
3,WEAR_CHAIN_autoencoder_scaler.pkl,True,0.002250,1.791457e+09
4,WEAR_CHAIN_autoencoder_calibration_scores.csv,True,76.938986,1.791457e+09
5,WEAR_CHAIN_hybrid_calibration_scores.csv,True,106.454224,1.791457e+09
6,WEAR_CHAIN_unseen_test_predictions.csv,True,164.873775,1.791457e+09
7,WEAR_CHAIN_FINAL_test_metrics.csv,True,0.000834,1.791458e+09
8,WEAR_CHAIN_FINAL_PAPER_VALUES.csv,True,0.010328,1.791458e+09
9,WEAR_CHAIN_FINAL_PAPER_VALUES.json,True,0.014990,1.791458e+09
10,WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv,True,0.002829,1.791458e+09

==========================================================================================
2. CURRENT ARTIFACT SHA-256
==========================================================================================
Hashing WEAR_CHAIN_XGBoost_baseline.pkl...
Hashing WEAR_CHAIN_XGBoost_calibration_predictions.csv...
Hashing WEAR_CHAIN_autoencoder.keras...
Hashing WEAR_CHAIN_autoencoder_scaler.pkl...
Hashing WEAR_CHAIN_autoencoder_calibration_scores.csv...
Hashing WEAR_CHAIN_hybrid_calibration_scores.csv...
Hashing WEAR_CHAIN_unseen_test_predictions.csv...
Hashing WEAR_CHAIN_FINAL_test_metrics.csv...
Hashing WEAR_CHAIN_FINAL_PAPER_VALUES.csv...
Hashing WEAR_CHAIN_FINAL_PAPER_VALUES.json...
Hashing WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv...

,file,size_MB,SHA256
0,WEAR_CHAIN_XGBoost_baseline.pkl,0.883835,694852ebb265229e3f6f8dd47c74176c4b2ecda00809c1...
1,WEAR_CHAIN_XGBoost_calibration_predictions.csv,76.720075,e775ffe6dad51b430874af1bb88a767e37ff1211759d50...
2,WEAR_CHAIN_autoencoder.keras,0.090010,d5a253ece79006787bbae11ce7ac482e7e6cf04ad501bc...
3,WEAR_CHAIN_autoencoder_scaler.pkl,0.002250,48b6f6eb91d209addd7eda327a3a116e65ece5596d8a6f...
4,WEAR_CHAIN_autoencoder_calibration_scores.csv,76.938986,80d528c590c6c0d4b50edad882ee211e2691c2beafc64b...
5,WEAR_CHAIN_hybrid_calibration_scores.csv,106.454224,b3eaa23c7f043fdf554f4c142b6a0053ae4d055422337c...
6,WEAR_CHAIN_unseen_test_predictions.csv,164.873775,5fa88f9675f32cd49fb692d0e2bd1aa0493de6f575ac76...
7,WEAR_CHAIN_FINAL_test_metrics.csv,0.000834,d5af24db07e387f8244aca0597bb5af543f176b2defe2f...
8,WEAR_CHAIN_FINAL_PAPER_VALUES.csv,0.010328,473cf19963896789261a6fb14359b3cffb7e95b10cab57...
9,WEAR_CHAIN_FINAL_PAPER_VALUES.json,0.014990,3f26f4586a851913c9d3e2e4f022c48d751aae7971f2a3...
10,WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv,0.002829,d9942e2a101c1840b85ae513e33cae2c94f2e50568d6a0...

==========================================================================================
3. ORIGINAL EXPERIMENT RECORDED VALUES
==========================================================================================

                   parameter  original_value
0          XGBoost_threshold    3.404080e-01
1       Hybrid_Max_threshold    9.948894e-01
2   Hybrid_Average_threshold    9.499144e-01
3                     XGB_TN    3.598400e+04
4                     XGB_FP    1.623000e+03
5                     XGB_FN    1.086000e+03
6                     XGB_TP    1.303692e+06
7                      AE_TN    3.682900e+04
8                      AE_FP    7.780000e+02
9                      AE_FN    1.196800e+04
10                     AE_TP    1.292810e+06
11             Hybrid_Max_TN    3.632700e+04
12             Hybrid_Max_FP    1.280000e+03
13             Hybrid_Max_FN    1.460000e+03
14             Hybrid_Max_TP    1.303318e+06
15         Hybrid_Average_TN    3.663500e+04
16         Hybrid_Average_FP    9.720000e+02
17         Hybrid_Average_FN    3.888000e+03
18         Hybrid_Average_TP    1.300890e+06

==========================================================================================
4. CURRENT FINAL TEST METRICS ARTIFACT
==========================================================================================
Columns: ['model', 'records', 'accuracy', 'precision', 'recall', 'f1', 'FPR', 'FNR', 'TN', 'FP', 'FN', 'TP', 'ROC_AUC', 'PR_AUC']

,model,records,accuracy,precision,recall,f1,FPR,FNR,TN,FP,FN,TP,ROC_AUC,PR_AUC
0,XGBoost,1342385,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,35984,1623,1086,1303692,0.999915,0.999998
1,Autoencoder,1342385,0.993337,0.999123,0.994018,0.996564,0.030287,0.005982,36468,1139,7805,1296973,0.997234,0.999897
2,Hybrid_Max,1342385,0.997937,0.998984,0.998894,0.998939,0.035259,0.001106,36281,1326,1443,1303335,0.999785,0.999992
3,Hybrid_Average,1342385,0.995556,0.998835,0.996589,0.997711,0.040312,0.003411,36091,1516,4450,1300328,0.999609,0.999989

==========================================================================================
5. CURRENT PAPER VALUES ARTIFACT
==========================================================================================
Rows: 108

,section,metric,value,source
0,Dataset,Raw training captures,51,WEAR_CHAIN_FINAL_raw_capture_inventory.csv
1,Dataset,raw_training_rows,7160831,Executed Kaggle experiment / audit records
2,Dataset,clean_training_rows,7160827,Executed Kaggle experiment / audit records
3,Dataset,excluded_malformed_rows,4,Executed Kaggle experiment / audit records
4,Dataset,raw_capture_count,51,Executed Kaggle experiment / audit records
5,Dataset,model_feature_count,44,Executed Kaggle experiment / audit records
6,Dataset,development_rows,4449176,Executed Kaggle experiment / audit records
7,Dataset,calibration_rows,1408617,Executed Kaggle experiment / audit records
8,Dataset,unseen_test_rows,1342385,Executed Kaggle experiment / audit records
9,Partition,calibration_records,1408617,WEAR_CHAIN_partitioned_dataset.csv
10,Partition,development_records,4449176,WEAR_CHAIN_partitioned_dataset.csv
11,Partition,internal_test_records,1303034,WEAR_CHAIN_partitioned_dataset.csv
12,Test Population,Total unseen test records,1342385,WEAR_CHAIN_unseen_test_predictions.csv
13,Test Population,Internal_records,1303034,WEAR_CHAIN_unseen_test_predictions.csv
14,Test Population,External_records,39351,WEAR_CHAIN_unseen_test_predictions.csv
15,Test Population,Benign_records,37607,WEAR_CHAIN_unseen_test_predictions.csv
16,Test Population,Attack_records,1304778,WEAR_CHAIN_unseen_test_predictions.csv
17,Detection Thresholds,XGBoost,0.340408,Executed Kaggle notebook / existing notebook v...
18,Detection Thresholds,Hybrid_Max,0.99488936,Executed Kaggle notebook / existing notebook v...
19,Detection Thresholds,Hybrid_Average,0.94991439,Executed Kaggle notebook / existing notebook v...
20,Detection Thresholds,Autoencoder,0.3691655993461609,Executed Kaggle notebook / existing notebook v...
21,Final Test Metrics,XGBoost_accuracy,0.9979819500366884,Independent reconstruction from WEAR_CHAIN_uns...
22,Final Test Metrics,XGBoost_precision,0.9987566219648131,Independent reconstruction from WEAR_CHAIN_uns...
23,Final Test Metrics,XGBoost_recall,0.9991676745009496,Independent reconstruction from WEAR_CHAIN_uns...
24,Final Test Metrics,XGBoost_f1,0.998962105947949,Independent reconstruction from WEAR_CHAIN_uns...
25,Final Test Metrics,XGBoost_FPR,0.04315685909538118,Independent reconstruction from WEAR_CHAIN_uns...
26,Final Test Metrics,XGBoost_FNR,0.0008323254990504132,Independent reconstruction from WEAR_CHAIN_uns...
27,Final Test Metrics,XGBoost_ROC_AUC,0.9999148492286104,Independent reconstruction from WEAR_CHAIN_uns...
28,Final Test Metrics,XGBoost_PR_AUC,0.9999975494808997,Independent reconstruction from WEAR_CHAIN_uns...
29,Final Test Metrics,XGBoost_TN,35984.0,Independent reconstruction from WEAR_CHAIN_uns...

==========================================================================================
6. POSSIBLE BACKUP / DUPLICATE ARTIFACTS
==========================================================================================

,name,size_MB,mtime
13,WEAR_CHAIN_feature_quality.csv,0.002163,1.791457e+09
12,WEAR_CHAIN_family_medians.csv,0.000548,1.791457e+09
29,WEAR_CHAIN_correlations.csv,0.052392,1.791457e+09
39,WEAR_CHAIN_partitioned_dataset.csv,2172.393583,1.791457e+09
3,WEAR_CHAIN_capture_assignments.csv,0.002650,1.791457e+09
16,WEAR_CHAIN_partition_summary.csv,0.000209,1.791457e+09
32,WEAR_CHAIN_external_test_dataset.csv,13.053819,1.791457e+09
47,WEAR_CHAIN_external_test_audit.csv,0.000126,1.791457e+09
26,WEAR_CHAIN_XGBoost_baseline.pkl,0.883835,1.791457e+09
27,WEAR_CHAIN_XGBoost_calibration_predictions.csv,76.720075,1.791457e+09
21,WEAR_CHAIN_autoencoder.keras,0.090010,1.791457e+09
22,WEAR_CHAIN_autoencoder_scaler.pkl,0.002250,1.791457e+09
24,WEAR_CHAIN_autoencoder_calibration_scores.csv,76.938986,1.791457e+09
43,WEAR_CHAIN_hybrid_calibration_scores.csv,106.454224,1.791457e+09
31,WEAR_CHAIN_unseen_test_predictions.csv,164.873775,1.791457e+09
46,WEAR_CHAIN_feature_distribution_drift.csv,0.005341,1.791457e+09
35,WEAR_CHAIN_score_distribution_summary.csv,0.001122,1.791457e+09
8,WEAR_CHAIN_IAT_descriptive_statistics.csv,0.000449,1.791457e+09
40,WEAR_CHAIN_XGBoost_feature_importance.csv,0.000833,1.791457e+09
5,WEAR_CHAIN_feature_drift_importance_combined.csv,0.005825,1.791457e+09
41,WEAR_CHAIN_external_FP_feature_comparison.csv,0.005227,1.791457e+09
36,WEAR_CHAIN_external_FP_importance_analysis.csv,0.005939,1.791457e+09
28,WEAR_CHAIN_protocol_pattern_distribution.csv,0.001522,1.791457e+09
34,WEAR_CHAIN_udp_benign_protocol17_summary.csv,0.000705,1.791457e+09
20,WEAR_CHAIN_external_udp_fp_feature_comparison.csv,0.002978,1.791457e+09
9,WEAR_CHAIN_udp_xgb_contribution_comparison.csv,0.002270,1.791457e+09
45,WEAR_CHAIN_udp_xgb_record_contributions.csv,1.660306,1.791457e+09
0,WEAR_CHAIN_section17_partition_audit.csv,0.000119,1.791457e+09
25,WEAR_CHAIN_17B_reconstructed_test_metrics.csv,0.000674,1.791457e+09
15,WEAR_CHAIN_17C_raw_file_inventory.csv,0.005081,1.791457e+09
42,WEAR_CHAIN_18_recovery_inventory.csv,0.000280,1.791457e+09
1,WEAR_CHAIN_20_trust_test_predictions.csv,83.280001,1.791457e+09
30,WEAR_CHAIN_21_audit_events.csv,173.109209,1.791457e+09
33,WEAR_CHAIN_21_blockchain_manifest.csv,0.279933,1.791457e+09
10,WEAR_CHAIN_FINAL_artifact_inventory.csv,0.001909,1.791457e+09
7,WEAR_CHAIN_FINAL_raw_capture_inventory.csv,0.005081,1.791457e+09
19,WEAR_CHAIN_FINAL_test_family_counts.csv,0.000132,1.791458e+09
14,WEAR_CHAIN_FINAL_test_metrics.csv,0.000834,1.791458e+09
18,WEAR_CHAIN_FINAL_trust_state_counts.csv,0.000146,1.791458e+09
38,WEAR_CHAIN_FINAL_trust_by_label.csv,0.000295,1.791458e+09
4,WEAR_CHAIN_FINAL_PAPER_VALUES.csv,0.010328,1.791458e+09
2,WEAR_CHAIN_FINAL_KAGGLE_AUDIT.csv,0.002829,1.791458e+09
44,WEAR_CHAIN_FINAL_PAPER_VALUES.json,0.014990,1.791458e+09
6,WEAR_CHAIN_PUBLICATION_ANALYSIS,0.003906,1.791458e+09
17,WEAR_CHAIN_FROZEN_PREDICTION_CONSISTENCY_AUDIT...,0.000386,1.791458e+09
37,WEAR_CHAIN_CURRENT_vs_AUTHORITATIVE_METRICS.csv,0.002309,1.791458e+09
23,WEAR_CHAIN_EXACT_CALIBRATION_THRESHOLDS.csv,0.000337,1.791458e+09
11,WEAR_CHAIN_EXACT_THRESHOLD_TEST_METRICS.csv,0.000663,1.791458e+09

==========================================================================================
7. PREDICTION / CALIBRATION FILE SEARCH
==========================================================================================

,file,size_MB,mtime,SHA256
0,WEAR_CHAIN_17B_reconstructed_test_metrics.csv,0.000674,1.791457e+09,f8e17b189b8a9fbdd503570091223190de5ffcacdff664...
1,WEAR_CHAIN_20_trust_test_predictions.csv,83.280001,1.791457e+09,33ed78ce1ccc86ececcd81a075bf16c288b1871904261e...
2,WEAR_CHAIN_FINAL_test_metrics.csv,0.000834,1.791458e+09,d5af24db07e387f8244aca0597bb5af543f176b2defe2f...
3,WEAR_CHAIN_XGBoost_calibration_predictions.csv,76.720075,1.791457e+09,e775ffe6dad51b430874af1bb88a767e37ff1211759d50...
4,WEAR_CHAIN_autoencoder_calibration_scores.csv,76.938986,1.791457e+09,80d528c590c6c0d4b50edad882ee211e2691c2beafc64b...
5,WEAR_CHAIN_hybrid_calibration_scores.csv,106.454224,1.791457e+09,b3eaa23c7f043fdf554f4c142b6a0053ae4d055422337c...
6,WEAR_CHAIN_unseen_test_predictions.csv,164.873775,1.791457e+09,5fa88f9675f32cd49fb692d0e2bd1aa0493de6f575ac76...

==========================================================================================
8. CURRENT CALIBRATION POPULATION
==========================================================================================
AE calibration rows: 1408617
AE calibration labels:

label
0      38547
1    1370070
Name: count, dtype: int64

Hybrid calibration rows: 1408617
Hybrid calibration labels:

label
0      38547
1    1370070
Name: count, dtype: int64

==========================================================================================
9. CURRENT AUTOENCODER CALIBRATION DISTRIBUTION
==========================================================================================

AE BENIGN
count  : 38547
min    : 0.00025547453
1%     : 0.00029110363699999997
25%    : 0.0006163922850000001
50%    : 0.0025919722
75%    : 0.011176468
99%    : 0.36916576280000013
max    : 43.56238

AE ATTACK
count  : 1370070
min    : 0.0002753863
1%     : 0.747805377
25%    : 1.0217271
50%    : 2.0918558
75%    : 11.551539
99%    : 144.41867
max    : 9261.274

==========================================================================================
10. CURRENT HYBRID CALIBRATION DISTRIBUTION
==========================================================================================

xgb_percentile
count: 38547
min: 2.594235608477962e-05
50%: 0.5000129711780424
90%: 0.9000025942356086
95%: 0.950001297117804
99%: 0.990000259423561
max: 1.0

ae_percentile
count: 38547
min: 2.594235608477962e-05
50%: 0.5000129711780424
90%: 0.9000025942356086
95%: 0.950001297117804
99%: 0.990000259423561
max: 1.0

hybrid_max_score
count: 38547
min: 0.0263314914260513
50%: 0.6804161153915999
90%: 0.9468804316808054
95%: 0.9740835862713052
99%: 0.9948514800114145
max: 1.0

hybrid_average_score
count: 38547
min: 0.0161620878408177
50%: 0.4754585311437985
90%: 0.8202116896256519
95%: 0.8890938335019585
99%: 0.9516963706643837
max: 0.9991439022492024

==========================================================================================
11. FINAL METRICS CONSISTENCY
==========================================================================================
Current final metrics file:

,model,records,accuracy,precision,recall,f1,FPR,FNR,TN,FP,FN,TP,ROC_AUC,PR_AUC
0,XGBoost,1342385,0.997982,0.998757,0.999168,0.998962,0.043157,0.000832,35984,1623,1086,1303692,0.999915,0.999998
1,Autoencoder,1342385,0.993337,0.999123,0.994018,0.996564,0.030287,0.005982,36468,1139,7805,1296973,0.997234,0.999897
2,Hybrid_Max,1342385,0.997937,0.998984,0.998894,0.998939,0.035259,0.001106,36281,1326,1443,1303335,0.999785,0.999992
3,Hybrid_Average,1342385,0.995556,0.998835,0.996589,0.997711,0.040312,0.003411,36091,1516,4450,1300328,0.999609,0.999989

IMPORTANT:
This file is compared against the original authoritative values shown above.

==========================================================================================
12. SEARCH CURRENT ARTIFACTS FOR ORIGINAL THRESHOLDS
==========================================================================================

                                 file value_found
0   WEAR_CHAIN_FINAL_PAPER_VALUES.csv  0.99488936
1   WEAR_CHAIN_FINAL_PAPER_VALUES.csv  0.94991439
2  WEAR_CHAIN_FINAL_PAPER_VALUES.json  0.99488936
3  WEAR_CHAIN_FINAL_PAPER_VALUES.json  0.94991439

==========================================================================================
13. DIAGNOSTIC CONCLUSION
==========================================================================================

The current calibration artifacts produce thresholds that
differ from the thresholds recorded by the original executed
Kaggle experiment.

This means the discrepancy is NOT caused by rounding alone.

The original experiment recorded:

    Hybrid Max     = 0.99488936
    Hybrid Average = 0.94991439

The current calibration artifacts produce:

    Hybrid Max     = 0.9948774223674994
    Hybrid Average = 0.9525065504449114

The current test prediction columns are internally consistent
with the CURRENT calibration artifacts.

Therefore:

    CURRENT ARTIFACTS != ORIGINAL EXPERIMENT STATE

Do NOT overwrite the authoritative paper metrics.

Do NOT retrain.

The next action depends on whether a preserved original
prediction/calibration artifact exists somewhere in the
Kaggle working directory or uploaded dataset.


==========================================================================================
AUDIT COMPLETE
==========================================================================================

In [30]:
# ================================================================
# WEAR-CHAIN — SEARCH FOR ORIGINAL / DUPLICATE ARTIFACTS
# ================================================================
#
# READ-ONLY
# NO RETRAINING
# NO PREDICTION
# NO FILE MODIFICATION
#
# Goal:
# Find whether an untouched copy of the original WEAR-CHAIN
# prediction/calibration artifacts exists outside /kaggle/working.
# ================================================================

import os
import glob
import hashlib
import pandas as pd
from pathlib import Path


print("=" * 90)
print("WEAR-CHAIN — ORIGINAL ARTIFACT SEARCH")
print("=" * 90)


# ================================================================
# 1. SEARCH TARGET DIRECTORIES
# ================================================================

search_roots = [
    "/kaggle/input",
    "/kaggle/working",
    "/kaggle/temp",
]

target_names = [
    "WEAR_CHAIN_unseen_test_predictions.csv",
    "WEAR_CHAIN_autoencoder_calibration_scores.csv",
    "WEAR_CHAIN_hybrid_calibration_scores.csv",
    "WEAR_CHAIN_XGBoost_calibration_predictions.csv",
    "WEAR_CHAIN_FINAL_test_metrics.csv",
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv",
    "WEAR_CHAIN_FINAL_PAPER_VALUES.json",
]


print("\nSearching for exact filenames...\n")


matches = []


for root in search_roots:

    if not os.path.exists(root):
        continue

    for target in target_names:

        # Exact filename search
        pattern = os.path.join(
            root,
            "**",
            target
        )

        found = glob.glob(
            pattern,
            recursive=True
        )

        for path in found:

            try:
                size_mb = (
                    os.path.getsize(path)
                    / (1024 ** 2)
                )

                mtime = os.path.getmtime(path)

            except Exception:

                size_mb = None
                mtime = None

            matches.append({

                "root":
                    root,

                "file":
                    target,

                "path":
                    path,

                "size_MB":
                    size_mb,

                "mtime":
                    mtime
            })


matches_df = pd.DataFrame(
    matches
)


if len(matches_df) == 0:

    print(
        "NO EXACT-NAME MATCHES FOUND."
    )

else:

    display(
        matches_df.sort_values(
            ["file", "path"]
        )
    )


# ================================================================
# 2. SEARCH FOR ANY WEAR_CHAIN CSV/PKL/KERAS/JSON ARTIFACT
# ================================================================

print("\n" + "=" * 90)
print("2. ALL WEAR_CHAIN ARTIFACTS OUTSIDE /kaggle/working")
print("=" * 90)


all_matches = []


for root in search_roots:

    if not os.path.exists(root):
        continue

    pattern = os.path.join(
        root,
        "**",
        "WEAR_CHAIN*"
    )

    found = glob.glob(
        pattern,
        recursive=True
    )

    for path in found:

        if not os.path.isfile(path):
            continue

        try:

            size_mb = (
                os.path.getsize(path)
                / (1024 ** 2)
            )

            mtime = os.path.getmtime(path)

        except Exception:

            continue

        all_matches.append({

            "path":
                path,

            "filename":
                os.path.basename(path),

            "size_MB":
                round(
                    size_mb,
                    6
                ),

            "mtime":
                mtime
        })


all_df = pd.DataFrame(
    all_matches
)


if len(all_df) == 0:

    print(
        "NO WEAR_CHAIN ARTIFACTS FOUND."
    )

else:

    outside_working = all_df[
        ~all_df["path"].str.startswith(
            "/kaggle/working/"
        )
    ].copy()

    print(
        "Total WEAR_CHAIN files found:",
        len(all_df)
    )

    print(
        "Outside /kaggle/working:",
        len(outside_working)
    )

    display(
        outside_working.sort_values(
            "path"
        )
    )


# ================================================================
# 3. SEARCH FOR FILES WITH RELEVANT KEYWORDS
# ================================================================

print("\n" + "=" * 90)
print("3. BROADER SEARCH FOR POSSIBLE ORIGINAL COPIES")
print("=" * 90)


keywords = [
    "unseen_test",
    "calibration",
    "hybrid",
    "autoencoder",
    "prediction",
    "paper_values",
]


keyword_matches = []


for root in search_roots:

    if not os.path.exists(root):
        continue

    for keyword in keywords:

        pattern = os.path.join(
            root,
            "**",
            f"*{keyword}*"
        )

        found = glob.glob(
            pattern,
            recursive=True
        )

        for path in found:

            if not os.path.isfile(path):
                continue

            # Ignore the normal working-directory artifacts here;
            # the purpose is finding alternate copies.
            if path.startswith(
                "/kaggle/working/"
            ):
                continue

            try:

                size_mb = (
                    os.path.getsize(path)
                    / (1024 ** 2)
                )

            except Exception:

                continue

            keyword_matches.append({

                "keyword":
                    keyword,

                "path":
                    path,

                "filename":
                    os.path.basename(path),

                "size_MB":
                    round(
                        size_mb,
                        6
                    )
            })


keyword_df = pd.DataFrame(
    keyword_matches
).drop_duplicates(
    subset=["path"]
)


if len(keyword_df) == 0:

    print(
        "No relevant alternate files found."
    )

else:

    display(
        keyword_df.sort_values(
            "path"
        )
    )


# ================================================================
# 4. COMPARE EXACT COPIES IF FOUND
# ================================================================

print("\n" + "=" * 90)
print("4. SHA-256 COMPARISON OF DUPLICATES")
print("=" * 90)


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb"
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b""
        ):

            h.update(chunk)

    return h.hexdigest()


if len(matches_df) > 0:

    hash_rows = []

    for _, row in matches_df.iterrows():

        path = row["path"]

        try:

            digest = sha256_file(
                path
            )

        except Exception as e:

            digest = f"ERROR: {e}"

        hash_rows.append({

            "file":
                row["file"],

            "path":
                path,

            "size_MB":
                row["size_MB"],

            "SHA256":
                digest
        })


    hash_matches_df = pd.DataFrame(
        hash_rows
    )

    display(
        hash_matches_df
    )


# ================================================================
# 5. SPECIFIC TEST: IS THE ORIGINAL PREDICTION FILE PRESERVED?
# ================================================================

print("\n" + "=" * 90)
print("5. ORIGINAL TEST PREDICTION FILE CHECK")
print("=" * 90)


prediction_matches = matches_df[
    matches_df["file"]
    ==
    "WEAR_CHAIN_unseen_test_predictions.csv"
].copy()


if len(prediction_matches) == 0:

    print(
        """
No alternate WEAR_CHAIN_unseen_test_predictions.csv
was found.

This means the current 164.7 MB prediction file may be
the only surviving copy in the mounted Kaggle filesystem.
"""
    )

else:

    print(
        "Found alternate prediction copies:"
    )

    display(
        prediction_matches
    )


# ================================================================
# 6. SPECIFIC TEST: ORIGINAL CALIBRATION FILES
# ================================================================

print("\n" + "=" * 90)
print("6. ORIGINAL CALIBRATION FILE CHECK")
print("=" * 90)


calibration_matches = matches_df[
    matches_df["file"].isin([
        "WEAR_CHAIN_autoencoder_calibration_scores.csv",
        "WEAR_CHAIN_hybrid_calibration_scores.csv",
        "WEAR_CHAIN_XGBoost_calibration_predictions.csv",
    ])
].copy()


if len(calibration_matches) == 0:

    print(
        """
No alternate calibration copies were found.
"""
    )

else:

    display(
        calibration_matches
    )


# ================================================================
# 7. FINAL CONCLUSION
# ================================================================

print("\n" + "=" * 90)
print("7. SEARCH CONCLUSION")
print("=" * 90)


if len(matches_df) == 0:

    print(
        """
NO DUPLICATE ARTIFACTS FOUND.

The original paper-value record exists in the current
working directory, but no alternate large prediction/
calibration artifacts were located.

In that case, the next step is NOT retraining.

We will reconstruct the provenance of the original
metrics from the preserved notebook execution records
and determine exactly which score-generation state
produced them.
"""
    )

else:

    print(
        """
ALTERNATE ARTIFACTS FOUND.

Do NOT use them yet.

We need to compare their SHA-256, row counts, columns,
and predictions against the authoritative confusion
matrices before deciding which artifacts represent the
original experiment.
"""
    )


print("\n" + "=" * 90)
print("SEARCH COMPLETE")
print("=" * 90)

==========================================================================================
WEAR-CHAIN — ORIGINAL ARTIFACT SEARCH
==========================================================================================

Searching for exact filenames...

,root,file,path,size_MB,mtime
5,/kaggle/working,WEAR_CHAIN_FINAL_PAPER_VALUES.csv,/kaggle/working/WEAR_CHAIN_FINAL_PAPER_VALUES.csv,0.010328,1.791458e+09
6,/kaggle/working,WEAR_CHAIN_FINAL_PAPER_VALUES.json,/kaggle/working/WEAR_CHAIN_FINAL_PAPER_VALUES....,0.014990,1.791458e+09
4,/kaggle/working,WEAR_CHAIN_FINAL_test_metrics.csv,/kaggle/working/WEAR_CHAIN_FINAL_test_metrics.csv,0.000834,1.791458e+09
3,/kaggle/working,WEAR_CHAIN_XGBoost_calibration_predictions.csv,/kaggle/working/WEAR_CHAIN_XGBoost_calibration...,76.720075,1.791457e+09
1,/kaggle/working,WEAR_CHAIN_autoencoder_calibration_scores.csv,/kaggle/working/WEAR_CHAIN_autoencoder_calibra...,76.938986,1.791457e+09
2,/kaggle/working,WEAR_CHAIN_hybrid_calibration_scores.csv,/kaggle/working/WEAR_CHAIN_hybrid_calibration_...,106.454224,1.791457e+09
0,/kaggle/working,WEAR_CHAIN_unseen_test_predictions.csv,/kaggle/working/WEAR_CHAIN_unseen_test_predict...,164.873775,1.791457e+09

==========================================================================================
2. ALL WEAR_CHAIN ARTIFACTS OUTSIDE /kaggle/working
==========================================================================================
Total WEAR_CHAIN files found: 62
Outside /kaggle/working: 0

Empty DataFrame
Columns: [path, filename, size_MB, mtime]
Index: []

==========================================================================================
3. BROADER SEARCH FOR POSSIBLE ORIGINAL COPIES
==========================================================================================
No relevant alternate files found.

==========================================================================================
4. SHA-256 COMPARISON OF DUPLICATES
==========================================================================================

,file,path,size_MB,SHA256
0,WEAR_CHAIN_unseen_test_predictions.csv,/kaggle/working/WEAR_CHAIN_unseen_test_predict...,164.873775,5fa88f9675f32cd49fb692d0e2bd1aa0493de6f575ac76...
1,WEAR_CHAIN_autoencoder_calibration_scores.csv,/kaggle/working/WEAR_CHAIN_autoencoder_calibra...,76.938986,80d528c590c6c0d4b50edad882ee211e2691c2beafc64b...
2,WEAR_CHAIN_hybrid_calibration_scores.csv,/kaggle/working/WEAR_CHAIN_hybrid_calibration_...,106.454224,b3eaa23c7f043fdf554f4c142b6a0053ae4d055422337c...
3,WEAR_CHAIN_XGBoost_calibration_predictions.csv,/kaggle/working/WEAR_CHAIN_XGBoost_calibration...,76.720075,e775ffe6dad51b430874af1bb88a767e37ff1211759d50...
4,WEAR_CHAIN_FINAL_test_metrics.csv,/kaggle/working/WEAR_CHAIN_FINAL_test_metrics.csv,0.000834,d5af24db07e387f8244aca0597bb5af543f176b2defe2f...
5,WEAR_CHAIN_FINAL_PAPER_VALUES.csv,/kaggle/working/WEAR_CHAIN_FINAL_PAPER_VALUES.csv,0.010328,473cf19963896789261a6fb14359b3cffb7e95b10cab57...
6,WEAR_CHAIN_FINAL_PAPER_VALUES.json,/kaggle/working/WEAR_CHAIN_FINAL_PAPER_VALUES....,0.014990,3f26f4586a851913c9d3e2e4f022c48d751aae7971f2a3...

==========================================================================================
5. ORIGINAL TEST PREDICTION FILE CHECK
==========================================================================================
Found alternate prediction copies:

,root,file,path,size_MB,mtime
0,/kaggle/working,WEAR_CHAIN_unseen_test_predictions.csv,/kaggle/working/WEAR_CHAIN_unseen_test_predict...,164.873775,1.791457e+09

==========================================================================================
6. ORIGINAL CALIBRATION FILE CHECK
==========================================================================================

,root,file,path,size_MB,mtime
1,/kaggle/working,WEAR_CHAIN_autoencoder_calibration_scores.csv,/kaggle/working/WEAR_CHAIN_autoencoder_calibra...,76.938986,1.791457e+09
2,/kaggle/working,WEAR_CHAIN_hybrid_calibration_scores.csv,/kaggle/working/WEAR_CHAIN_hybrid_calibration_...,106.454224,1.791457e+09
3,/kaggle/working,WEAR_CHAIN_XGBoost_calibration_predictions.csv,/kaggle/working/WEAR_CHAIN_XGBoost_calibration...,76.720075,1.791457e+09

==========================================================================================
7. SEARCH CONCLUSION
==========================================================================================

ALTERNATE ARTIFACTS FOUND.

Do NOT use them yet.

We need to compare their SHA-256, row counts, columns,
and predictions against the authoritative confusion
matrices before deciding which artifacts represent the
original experiment.


==========================================================================================
SEARCH COMPLETE
==========================================================================================

In [31]:
# ================================================================
# WEAR-CHAIN — ORIGINAL THRESHOLD REPLAY
# ================================================================
#
# PURPOSE:
# Determine whether the original paper confusion matrices can
# be recovered from the CURRENT frozen test score vectors by
# applying the ORIGINAL thresholds recorded in the paper-values
# artifact.
#
# READ-ONLY.
# NO RETRAINING.
# NO FILE MODIFICATION.
# ================================================================

import os
import numpy as np
import pandas as pd


BASE = "/kaggle/working"

TEST_FILE = os.path.join(
    BASE,
    "WEAR_CHAIN_unseen_test_predictions.csv"
)

PAPER_FILE = os.path.join(
    BASE,
    "WEAR_CHAIN_FINAL_PAPER_VALUES.csv"
)


print("=" * 90)
print("WEAR-CHAIN — ORIGINAL THRESHOLD REPLAY")
print("=" * 90)


# ================================================================
# 1. LOAD FROZEN TEST SCORES
# ================================================================

test = pd.read_csv(
    TEST_FILE
)

print(
    "\nTest rows:",
    len(test)
)

print(
    "Columns:",
    list(test.columns)
)


# ================================================================
# 2. ORIGINAL AUTHORITATIVE THRESHOLDS
# ================================================================
#
# These are the values preserved in the original paper-values
# artifact / executed experiment.
# ================================================================

ORIGINAL_THRESHOLDS = {

    "XGBoost":
        0.340408,

    "Autoencoder":
        0.3474448621273041,

    "Hybrid_Max":
        0.99488936,

    "Hybrid_Average":
        0.94991439
}


print(
    "\nOriginal authoritative thresholds:"
)

for k, v in ORIGINAL_THRESHOLDS.items():

    print(
        f"{k:20s}: {v:.17g}"
    )


# ================================================================
# 3. AUTHORITATIVE CONFUSION MATRICES
# ================================================================

REFERENCE = {

    "XGBoost":
        {
            "TN": 35984,
            "FP": 1623,
            "FN": 1086,
            "TP": 1303692
        },

    "Autoencoder":
        {
            "TN": 36829,
            "FP": 778,
            "FN": 11968,
            "TP": 1292810
        },

    "Hybrid_Max":
        {
            "TN": 36327,
            "FP": 1280,
            "FN": 1460,
            "TP": 1303318
        },

    "Hybrid_Average":
        {
            "TN": 36635,
            "FP": 972,
            "FN": 3888,
            "TP": 1300890
        }
}


# ================================================================
# 4. SCORE COLUMN MAPPING
# ================================================================

SCORE_COLUMNS = {

    "XGBoost":
        "xgb_score",

    "Autoencoder":
        "ae_score",

    "Hybrid_Max":
        "hybrid_max_score",

    "Hybrid_Average":
        "hybrid_average_score"
}


# ================================================================
# 5. METRIC FUNCTION
# ================================================================

def confusion_from_prediction(
    y_true,
    prediction
):

    y_true = np.asarray(
        y_true,
        dtype=np.int8
    )

    prediction = np.asarray(
        prediction,
        dtype=np.int8
    )

    TN = int(
        np.sum(
            (y_true == 0) &
            (prediction == 0)
        )
    )

    FP = int(
        np.sum(
            (y_true == 0) &
            (prediction == 1)
        )
    )

    FN = int(
        np.sum(
            (y_true == 1) &
            (prediction == 0)
        )
    )

    TP = int(
        np.sum(
            (y_true == 1) &
            (prediction == 1)
        )
    )

    return {
        "TN": TN,
        "FP": FP,
        "FN": FN,
        "TP": TP
    }


# ================================================================
# 6. REPLAY ORIGINAL THRESHOLDS
# ================================================================

y = test["label"].to_numpy(
    dtype=np.int8
)


results = []


for model, threshold in ORIGINAL_THRESHOLDS.items():

    score_column = SCORE_COLUMNS[
        model
    ]

    scores = test[
        score_column
    ].to_numpy(
        dtype=np.float64
    )

    prediction = (
        scores >= threshold
    ).astype(
        np.int8
    )

    cm = confusion_from_prediction(
        y,
        prediction
    )

    ref = REFERENCE[
        model
    ]

    results.append({

        "Model":
            model,

        "Original_threshold":
            threshold,

        "Current_score_min":
            np.min(scores),

        "Current_score_max":
            np.max(scores),

        "Current_TN":
            cm["TN"],

        "Reference_TN":
            ref["TN"],

        "Current_FP":
            cm["FP"],

        "Reference_FP":
            ref["FP"],

        "Current_FN":
            cm["FN"],

        "Reference_FN":
            ref["FN"],

        "Current_TP":
            cm["TP"],

        "Reference_TP":
            ref["TP"],

        "EXACT_MATCH":
            (
                cm["TN"] == ref["TN"]
                and
                cm["FP"] == ref["FP"]
                and
                cm["FN"] == ref["FN"]
                and
                cm["TP"] == ref["TP"]
            )
    })


replay_df = pd.DataFrame(
    results
)


print("\n" + "=" * 90)
print("ORIGINAL THRESHOLD REPLAY RESULTS")
print("=" * 90)

display(
    replay_df
)


# ================================================================
# 7. AUTOENCODER THRESHOLD-INTERVAL ANALYSIS
# ================================================================

print("\n" + "=" * 90)
print("AUTOENCODER THRESHOLD INTERVAL ANALYSIS")
print("=" * 90)


ae_scores = test[
    "ae_score"
].to_numpy(
    dtype=np.float64
)


ae_current_threshold = (
    0.3474449678000001
)

ae_original_threshold = (
    0.3474448621273041
)


lower = min(
    ae_original_threshold,
    ae_current_threshold
)

upper = max(
    ae_original_threshold,
    ae_current_threshold
)


interval_mask = (
    ae_scores >= lower
) & (
    ae_scores < upper
)


interval_count = int(
    np.sum(interval_mask)
)


print(
    "Original AE threshold :",
    repr(ae_original_threshold)
)

print(
    "Current AE threshold  :",
    repr(ae_current_threshold)
)

print(
    "Absolute difference   :",
    repr(
        abs(
            ae_current_threshold -
            ae_original_threshold
        )
    )
)

print(
    "Test scores in interval:",
    interval_count
)


if interval_count > 0:

    interval_labels = (
        test.loc[
            interval_mask,
            "label"
        ]
        .value_counts()
        .sort_index()
    )

    print(
        "\nLabels inside threshold interval:"
    )

    display(
        interval_labels
    )

    print(
        "\nInterval score statistics:"
    )

    display(
        pd.Series(
            ae_scores[
                interval_mask
            ]
        ).describe()
    )

else:

    print(
        "\nNo test scores fall inside the tiny AE threshold interval."
    )


# ================================================================
# 8. COMPARE CURRENT STORED PREDICTIONS WITH ORIGINAL-THRESHOLD
# ================================================================

print("\n" + "=" * 90)
print("STORED PREDICTION vs ORIGINAL-THRESHOLD REPLAY")
print("=" * 90)


stored_columns = {

    "XGBoost":
        "XGBoost_prediction",

    "Autoencoder":
        "Autoencoder_prediction",

    "Hybrid_Max":
        "Hybrid_Max_prediction",

    "Hybrid_Average":
        "Hybrid_Average_prediction"
}


comparison_rows = []


for model, threshold in ORIGINAL_THRESHOLDS.items():

    score_column = SCORE_COLUMNS[
        model
    ]

    stored_column = stored_columns[
        model
    ]

    scores = test[
        score_column
    ].to_numpy(
        dtype=np.float64
    )

    stored = test[
        stored_column
    ].to_numpy(
        dtype=np.int8
    )

    replay = (
        scores >= threshold
    ).astype(
        np.int8
    )

    mismatch = (
        stored != replay
    )

    comparison_rows.append({

        "Model":
            model,

        "Stored_positive":
            int(
                np.sum(
                    stored == 1
                )
            ),

        "Original_threshold_positive":
            int(
                np.sum(
                    replay == 1
                )
            ),

        "Mismatch_count":
            int(
                np.sum(mismatch)
            ),

        "Mismatch_rate":
            float(
                np.mean(mismatch)
            )
    })


comparison_df = pd.DataFrame(
    comparison_rows
)


display(
    comparison_df
)


# ================================================================
# 9. HYBRID MONOTONICITY TEST
# ================================================================
#
# If the current hybrid score vector were identical to the
# original score vector, then:
#
# Original threshold < Current threshold
#
# means original-positive set must contain the current-positive
# set.
#
# This test demonstrates why the original Hybrid confusion
# matrices cannot come from the current score vectors.
# ================================================================

print("\n" + "=" * 90)
print("HYBRID MONOTONICITY TEST")
print("=" * 90)


for model in [
    "Hybrid_Max",
    "Hybrid_Average"
]:

    score_column = SCORE_COLUMNS[
        model
    ]

    current_threshold = (
        0.9948774223674994
        if model == "Hybrid_Max"
        else
        0.9525065504449114
    )

    original_threshold = (
        ORIGINAL_THRESHOLDS[
            model
        ]
    )

    scores = test[
        score_column
    ].to_numpy(
        dtype=np.float64
    )

    current_prediction = (
        scores >= current_threshold
    )

    original_prediction = (
        scores >= original_threshold
    )

    current_positive = int(
        np.sum(
            current_prediction
        )
    )

    original_positive = int(
        np.sum(
            original_prediction
        )
    )

    current_set_not_original = int(
        np.sum(
            current_prediction &
            ~original_prediction
        )
    )

    original_set_not_current = int(
        np.sum(
            original_prediction &
            ~current_prediction
        )
    )

    print(
        f"\n{model}"
    )

    print(
        "Original threshold:",
        original_threshold
    )

    print(
        "Current threshold :",
        current_threshold
    )

    print(
        "Current positives :",
        current_positive
    )

    print(
        "Original-threshold positives:",
        original_positive
    )

    print(
        "Current positive but original negative:",
        current_set_not_original
    )

    print(
        "Original positive but current negative:",
        original_set_not_current
    )


# ================================================================
# 10. FINAL INTERPRETATION
# ================================================================

print("\n" + "=" * 90)
print("FINAL INTERPRETATION")
print("=" * 90)

print(
    """
Interpretation:

1. XGBoost should reproduce the authoritative result because
   its current score vector already matches the original result.

2. Autoencoder will reveal whether the original threshold alone
   can recover the original confusion matrix.

3. Hybrid Max and Hybrid Average will reveal whether the current
   hybrid score vectors are compatible with the original
   thresholds.

4. If AE matches:
       We can recover the original AE predictions exactly
       from the current frozen test scores + preserved original
       threshold.

5. If either Hybrid model does not match:
       The original hybrid calibration/reference score state
       is not recoverable from the current hybrid score columns
       alone.

6. In that case, the authoritative hybrid metrics remain the
   preserved original experiment results in the paper-values
   artifact / executed notebook.

NO RETRAINING WILL BE PERFORMED.
"""
)

print("\n" + "=" * 90)
print("ORIGINAL THRESHOLD REPLAY COMPLETE")
print("=" * 90)

==========================================================================================
WEAR-CHAIN — ORIGINAL THRESHOLD REPLAY
==========================================================================================

Test rows: 1342385
Columns: ['test_source', 'source_file', 'label', 'attack_family', 'xgb_score', 'ae_score', 'xgb_percentile', 'ae_percentile', 'hybrid_max_score', 'hybrid_average_score', 'XGBoost_prediction', 'Autoencoder_prediction', 'Hybrid_Max_prediction', 'Hybrid_Average_prediction']

Original authoritative thresholds:
XGBoost             : 0.34040799999999999
Autoencoder         : 0.34744486212730408
Hybrid_Max          : 0.99488935999999994
Hybrid_Average      : 0.94991439

==========================================================================================
ORIGINAL THRESHOLD REPLAY RESULTS
==========================================================================================

,Model,Original_threshold,Current_score_min,Current_score_max,Current_TN,Reference_TN,Current_FP,Reference_FP,Current_FN,Reference_FN,Current_TP,Reference_TP,EXACT_MATCH
0,XGBoost,0.340408,6.576781e-07,1.0000,35984,35984,1623,1623,1086,1086,1303692,1303692,True
1,Autoencoder,0.347445,2.602619e-04,3947.3625,36249,36829,1358,778,7722,11968,1297056,1292810,False
2,Hybrid_Max,0.994889,2.633149e-02,1.0000,36286,36327,1321,1280,1445,1460,1303333,1303318,False
3,Hybrid_Average,0.949914,1.879524e-02,1.0000,35979,36635,1628,972,4240,3888,1300538,1300890,False

==========================================================================================
AUTOENCODER THRESHOLD INTERVAL ANALYSIS
==========================================================================================
Original AE threshold : 0.3474448621273041
Current AE threshold  : 0.3474449678000001
Absolute difference   : 1.0567269603800611e-07
Test scores in interval: 0

No test scores fall inside the tiny AE threshold interval.

==========================================================================================
STORED PREDICTION vs ORIGINAL-THRESHOLD REPLAY
==========================================================================================

,Model,Stored_positive,Original_threshold_positive,Mismatch_count,Mismatch_rate
0,XGBoost,1305315,1305315,0,0.000000
1,Autoencoder,1298112,1298414,302,0.000225
2,Hybrid_Max,1304661,1304654,7,0.000005
3,Hybrid_Average,1301844,1302166,322,0.000240

==========================================================================================
HYBRID MONOTONICITY TEST
==========================================================================================

Hybrid_Max
Original threshold: 0.99488936
Current threshold : 0.9948774223674994
Current positives : 1304657
Original-threshold positives: 1304654
Current positive but original negative: 3
Original positive but current negative: 0

Hybrid_Average
Original threshold: 0.94991439
Current threshold : 0.9525065504449114
Current positives : 1301721
Original-threshold positives: 1302166
Current positive but original negative: 0
Original positive but current negative: 445

==========================================================================================
FINAL INTERPRETATION
==========================================================================================

Interpretation:

1. XGBoost should reproduce the authoritative result because
   its current score vector already matches the original result.

2. Autoencoder will reveal whether the original threshold alone
   can recover the original confusion matrix.

3. Hybrid Max and Hybrid Average will reveal whether the current
   hybrid score vectors are compatible with the original
   thresholds.

4. If AE matches:
       We can recover the original AE predictions exactly
       from the current frozen test scores + preserved original
       threshold.

5. If either Hybrid model does not match:
       The original hybrid calibration/reference score state
       is not recoverable from the current hybrid score columns
       alone.

6. In that case, the authoritative hybrid metrics remain the
   preserved original experiment results in the paper-values
   artifact / executed notebook.

NO RETRAINING WILL BE PERFORMED.


==========================================================================================
ORIGINAL THRESHOLD REPLAY COMPLETE
==========================================================================================